<?php

/**
 * Implements hook_init().
 */
function checkdesk_core_init() {
  drupal_add_library('system', 'ui.draggable');
  drupal_add_library('system', 'ui.droppable');
  drupal_add_library('system', 'drupal.ajax');

  drupal_add_js(drupal_get_path('module', 'checkdesk_core') . '/js/checkdesk_core.js');

  // HACK: This enables the #ajax submission of the node form. Currently
  //       there does not appear to be a clean way to do this.
  //       See similar: http://drupal.org/node/1167076
  module_load_include('inc', 'node', 'node.pages');
}

/**
 * Implements hook_permission().
 */
function checkdesk_core_permission() {
  return array(
    'add report to story' => array(
      'title' => t('Add report to story'),
      'description' => t('User can add a report to a story. Otherwise, only allowed to suggest the addition.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function checkdesk_core_menu() {
  $items = array();

  $items['<sub>'] = array(
    'page callback' => 'drupal_goto',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['<nolink>'] = array(
    'page callback' => 'drupal_not_found',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['node/%checkdesk_report/checkdesk/suggest'] = array(
    'title' => 'Add report to story',
    'title callback' => '_checkdesk_core_report_suggest_title',
    'title arguments' => array(1),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_checkdesk_core_report_suggest', 1),
    'access callback' => '_checkdesk_core_report_can_suggest',
    'access arguments' => array(1),
  );
  $items['node/%checkdesk_report/checkdesk/modal/suggest/%ctools_js'] = array(
    'title' => 'Add report to story',
    'title callback' => '_checkdesk_core_report_suggest_title',
    'title arguments' => array(1),
    'page callback' => '_checkdesk_core_report_suggest_modal',
    'page arguments' => array(1, 5),
    'access callback' => '_checkdesk_core_report_can_suggest',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );
  $items['node/flag/confirm/%/%flag/%/%ctools_js'] = array(
    'title' => 'Confirm',
    'page callback' => '_checkdesk_core_flags_confirm_modal',
    'page arguments' => array(3, 4, 5, 6),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['core/messages'] = array(
    'title' => 'Invoke message',
    'page callback' => '_checkdesk_core_invoke_messages',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  /*
  $items['node/%checkdesk_report/checkdesk/publish'] = array(
    'title' => 'Publish a report',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_checkdesk_core_report_publish', 1),
    'access arguments' => array('create post content'),
  );
  */
  $items['admin/config/system/checkdesk'] = array(
    'title' => 'Checkdesk',
    'description' => 'Manage general Checkdesk configuration.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_checkdesk_core_settings'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/config/system/activity-formatter'] = array(
    'title' => 'Checkdesk',
    'description' => 'Manage hearbeat activity type and formatter.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_checkdesk_activity_formatter_mapping'),
    'access arguments' => array('administer site configuration'),
  );
  $items['report-view-modal/%ctools_js'] = array(
    'title' => 'Report view (modal)',
    'page callback' => '_checkdesk_modal_report_view',
    'page arguments' => array(1),
    'access callback' => TRUE,
    //'modal' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['modal/%ctools_js'] = array(
    'page callback' => 'checkdesk_core_modal_callback',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items['checkdesk_validation/unique_field'] = array(
    'title' => 'Client-side validation ajax callback to validate unique fields',
    'page callback' => '_checkdesk_validation_ajax_unique_field',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['checkdesk_take_tour'] = array(
    'title' => 'Take a tour based on role',
    'page callback' => '_checkdesk_core_take_tour',
    'access callback' => '_checkdesk_core_can_take_tour',
    'type' => MENU_CALLBACK,
  );
  $items['node/%node/collaboration'] = array(
    'page callback' => '_checkdesk_story_collaboration',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'file' => 'checkdesk_core.pages.inc',
  );
  $items['story-collaboration-anonymous/%ctools_js/login'] = array(
    'title' => 'Login',
    'page callback' => 'story_collaboration_anonymous_login',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'checkdesk_core.pages.inc',
  );
  $items['checkdesk/reports'] = array(
    'title' => 'Reports',
    'page callback' => 'drupal_goto',
    'page arguments' => array('search'),
    'access callback' => TRUE,
  );
  $items['checkdesk/draft_stories'] = array(
    'title' => 'Draft stories',
    'page callback' => 'drupal_goto',
    'page arguments' => array('search'),
    'access callback' => '_checkdesk_is_journalist',
  );
  $items['checkdesk/draft_updates'] = array(
    'title' => 'Draft updates',
    'page callback' => 'drupal_goto',
    'page arguments' => array('search'),
    'access callback' => '_checkdesk_is_journalist',
  );
  return $items;
}

function _checkdesk_is_journalist() {
  global $user;
  if ($user->uid == 1 || in_array('journalist', $user->roles)) {
    return TRUE;
  }
  return FALSE;
}
/**
 * Menu callback function for `checkdesk_take_tour`
 */
function _checkdesk_core_take_tour() {
  global $user;
  $roles = array_values($user->roles);
  $tour = '';
  if (in_array('journalist', $roles)) {
    $tour = 'journalist';
  }
  else if (in_array('citizen journalist', $roles)) {
    $tour = 'citizen';
  }
  drupal_goto('<front>', array('query' => array('tour' => $tour)));
}

/**
 * Menu access callback function for `checkdesk_take_tour`
 */
function _checkdesk_core_can_take_tour() {
  global $user;
  $roles = array_values($user->roles);
  return ($user->uid == 1) || in_array('journalist', $roles) || in_array('citizen journalist', $roles);
}

/**
 * Implements hook_menu_alter().
 */
function checkdesk_core_menu_alter(&$items) {
  // add delete tab to all nodes
  $items['node/%node/delete']['context'] = MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE;
  // make nodequeue tab localizable
  $items['node/%node/nodequeue']['title callback'] = 'checkdesk_core_nodequeue_tab_title';
  //deny access to node page
  $items['node']['access callback'] = FALSE;
}

/**
 * Title callback for menu item `node/%node/nodequeue`.
 */
function checkdesk_core_nodequeue_tab_title() {
  return t(variable_get('nodequeue_tab_name', 'Nodequeue'));
}

/**
 * Menu function for `modal/%ctools_js`.
 */
function checkdesk_core_modal_callback($js = FALSE) {
  $alias = preg_replace('/([a-z]{2}\/)?modal\/[^\/]+\//', '', request_path());
  $path = drupal_lookup_path('source', $alias);
  $node = menu_get_object('node', 1, $path);
  if (empty($node)) {
    return MENU_NOT_FOUND;
  }
  $output = drupal_render(node_view($node));
  $title = $node->title;
  if ($js) {
    ctools_include('ajax');
    ctools_include('modal');
    // custom settings array for bookmarlet modal
    $modal_style = array(
      'modal-popup-bookmarklet' => array(
        'modalSize' => array(
          'type' => 'fixed',
          'width' => 700,
          'height' => 350,
          'addWidth' => 0,
          'addHeight' => 0
        ),
        'modalOptions' => array(
          'opacity' => .5,
          'background-color' => '#000',
        ),
        'animation' => 'show',
        'animationSpeed' => 40,
        'modalTheme' => 'CToolsModalDialog',
        'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'checkdesk_core'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
      ),
    );

    drupal_add_js($modal_style, 'setting');
    ctools_modal_render($title, $output);

  }
  else {
    drupal_set_title($title);
    return $output;
  }
}

/**
 * Access function for
 */
function _checkdesk_core_report_can_suggest($report) {
  global $user;
  return user_access('add report to story');
}

/**
 * Menu function for `report-view-modal/%ctools_js`.
 */
function _checkdesk_modal_report_view($js = FALSE) {
  ctools_include('modal');
  $nid = arg(2);
  $output = '';
  if (is_numeric($nid)) {
    $node = node_load($nid);
    if (is_object($node)) {
      $title = $node->title;
      $element = node_view($node);
      $element['comments'] = comment_node_page_additions($node);
      $output = drupal_render($element);

      $javascript = drupal_add_js(NULL, NULL);
      $settings = '';
      if(isset($javascript['settings'])) {
        $settings = '<script type="text/javascript">jQuery.extend(Drupal.settings, ' .
          drupal_json_encode(call_user_func_array('array_merge_recursive', $javascript['settings']['data'])) .
          ');</script>';
      }
      //Add the settings to the form
      $output .= $settings;
    }
  }

  if ($js) {
    ctools_modal_render($title, $output);
  }
  else {
    drupal_set_title($title);
    print $output . ' no ctools';
  }
}

/**
 * Implements hook_ajax_render_alter().
 * Add a `facebook_refresh` command to make sure FB embeds are shown correctly.
 * @see http://thereisamoduleforthat.com/content/loading-facebook-embeds-ajax
 */
function checkdesk_core_ajax_render_alter(&$commands) {
  foreach ($commands as $command) {
    if ($command['command'] == 'modal_display') {
      $commands[] = array(
        'command' => 'refreshFacebook',
      );
    }
  }
}

/**
 * Form function for `_checkdesk_core_settings`.
 */
function _checkdesk_core_settings($form, $form_state) {
  $form['checkdesk_site_owner'] = array(
    '#title' => t('Site owner'),
    '#type' => 'textfield',
    '#default_value' => variable_get('checkdesk_site_owner', ''),
  );
  $form['checkdesk_site_owner_url'] = array(
    '#title' => t('Site owner URL'),
    '#type' => 'textfield',
    '#default_value' => variable_get('checkdesk_site_owner_url', ''),
  );
  $form['checkdesk_factchecking_statement'] = array(
    '#title' => t('A "verified" status means'),
    '#type' => 'textarea',
    '#default_value' => variable_get('checkdesk_factchecking_statement', ''),
  );

  return system_settings_form($form);
}

/**
 * Form function for `_checkdesk_activity_formatter_mapping`.
 */
function _checkdesk_activity_formatter_mapping($form, $form_state) {

  return system_settings_form($form);
}

/**
 * Load function for reports.
 */
function checkdesk_report_load($nid) {
  $report = node_load($nid);
  if ($report && $report->type == 'media') {
    return $report;
  }
  return FALSE;
}

/**
 * Title callback for `_checkdesk_core_report_suggest`.
 */
function _checkdesk_core_report_suggest_title($report) {
  return user_access('add report to story') ?
    t('Add Report "!title" to Story', array(
      '!title' => views_trim_text(array('max_length' => 30, 'ellipsis' => TRUE), $report->title))
    ) :
    t('Suggest Report "!title" to Story', array(
      '!title' => views_trim_text(array('max_length' => 30, 'ellipsis' => TRUE), $report->title))
    );
}

/**
 * Form function for `_checkdesk_core_report_suggest`.
 * Allow user to choose from all stories not already associated with this report.
 */
function _checkdesk_core_report_suggest($form, $form_state, $report = NULL) {
  if (empty($report)) {
    $report = $form_state['report'];
  }
  $stories = db_query("
    SELECT nid, concat(substring(title, 1, 48), '...') as title
    FROM {node}
    WHERE type='discussion'
    ORDER BY created DESC
    LIMIT 10
    ")->fetchAllKeyed();
  $form['story'] = array(
    '#type' => 'select',
    '#options' => $stories,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['#report'] = $report;
  return $form;
}

/**
 * Submit function for `_checkdesk_core_report_suggest`.
 */
function _checkdesk_core_report_suggest_submit($form, &$form_state) {
  // Add the story to the report.
  $report = $form['#report'];
  if (module_exists('checkdesk_duplicates')) {
    // Clone existing report ticket #3660
    $report = _checkdesk_duplicate_share_report($report, $form_state['values']['story']);
  }
  else {
    $report->field_stories[LANGUAGE_NONE][]['target_id'] = $form_state['values']['story'];
    node_save($report);
  }
  $story = node_load($form_state['values']['story']);
  $form_state['values']['story_title'] = $story->title;
  $form_state['values']['report_id'] = $report->nid;
  // Redirect to story.
  if (user_access('add report to story')) {
    $form_state['redirect'] = array('node/add/post', array('query' => array('report' => $report->nid, 'story' => $form_state['values']['story'])));
  }
}

/**
 * Modal function for `_checkdesk_core_report_suggest`.
 */
function _checkdesk_core_report_suggest_modal($report, $js) {
  if (!$js) {
    drupal_goto('node/' . $report->nid . '/checkdesk/suggest');
    return;
  }

  ctools_include('modal');
  ctools_include('ajax');

  $form_state = array(
    'ajax' => TRUE,
    'title' => _checkdesk_core_report_suggest_title($report),
    'report' => $report,
  );

  $commands = ctools_modal_form_wrapper('_checkdesk_core_report_suggest', $form_state);

  if (!empty($form_state['executed'])) {
    // Add the responder javascript, required by ctools
    ctools_add_js('ajax-responder');

    // Array with ajax response.
    $commands = array();
    // Create ajax command array, set the message and dismiss the modal window.
    $message = t('<b>' . views_trim_text(array('max_length' => 30, 'ellipsis' => TRUE), $report->title) . '</b> added to <b>' . $form_state['values']['story_title'] . '</b>');
    drupal_set_message(t($message));
    // $commands[] = ajax_command_prepend('#messages-container', theme('status_messages'));
    $commands[] = ctools_modal_command_dismiss();

    // Redirect to story.
    if (user_access('add report to story')) {
      $commands[] = ctools_ajax_command_redirect('node/add/post', 0, array('query' => array('report' => $form_state['values']['report_id'], 'story' => $form_state['values']['story'])));
    }
  }

  print ajax_render($commands);
  exit;
}

/**
 * Implements hook_flag_link_type_info().
 */
function checkdesk_core_flag_link_type_info() {
  return array(
    'checkdesk_modal' => array(
      'title' => t('Open confirmation in modal'),
      'description' => t('The user will be shown a modal window to confirm the flag.'),
      'options' => array(
        'confirm_modal_style' => 'modal-popup-small',
        'flag_confirmation' => '',
        'unflag_confirmation' => '',
      ),
      'uses standard js' => FALSE,
      'uses standard css' => FALSE,
    ),
  );
}

/*
 * Implements hook_flag_link().
 */
function checkdesk_core_flag_link($flag, $action, $content_id) {
  return array(
    'href' => 'node/flag/confirm/' . "$action/$flag->name/$content_id" . '/nojs',
    'query' => drupal_get_destination(),
    'attributes' => array('class' => array('ctools-use-modal')),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for `flag_form`.
 */
function checkdesk_core_form_flag_form_alter(&$form, &$form_state, $form_id) {
  $flag = $form['#flag'];
  $form['display']['link_options_checkdesk_modal'] = array(
    '#type' => 'fieldset',
    '#title' => t('Options for the "Confirmation form" link type'),
    // Any "link type" provider module must put its settings fields inside
    // a fieldset whose HTML ID is link-options-LINKTYPE, where LINKTYPE is
    // the machine-name of the link type. This is necessary for the
    // radiobutton's JavaScript dependency feature to work.
    '#id' => 'link-options-checkdesk_modal',
    '#weight' => 22,
  );

  $form['display']['link_options_checkdesk_modal']['confirm_modal_style'] = array(
    '#type' => 'radios',
    '#title' => t('Confirmation modal window sytle'),
    '#default_value' => isset($flag->confirm_modal_style) ? $flag->confirm_modal_style : 'modal-popup-small',
    '#options' => array(
      'modal-popup-small' => t('Small popup'),
      'modal-popup-medium' => t('Medium popup'),
      'modal-popup-large' => t('Large popup'),
    ),
  );
  $form['display']['link_options_checkdesk_modal']['flag_confirmation'] = array(
    '#type' => 'textfield',
    '#title' => t('Flag confirmation message'),
    '#default_value' => isset($flag->flag_confirmation) ? $flag->flag_confirmation : '',
    '#description' => t('Message displayed if the user has clicked the "flag this" link and confirmation is required. Usually presented in the form of a question such as, "Are you sure you want to flag this content?"'),
    '#access' => empty($flag->locked['flag_confirmation']),
  );

  $form['display']['link_options_checkdesk_modal']['unflag_confirmation'] = array(
    '#type' => 'textfield',
    '#title' => t('Unflag confirmation message'),
    '#default_value' => isset($flag->unflag_confirmation) ? $flag->unflag_confirmation : '',
    '#description' => t('Message displayed if the user has clicked the "unflag this" link and confirmation is required. Usually presented in the form of a question such as, "Are you sure you want to unflag this content?"'),
    '#access' => empty($flag->locked['unflag_confirmation']),
  );

}

function checkdesk_core_preprocess_flag(&$variables) {
  if ($variables['flag']->link_type == 'checkdesk_modal' && $variables['link_href']) {
    ctools_include('modal');
    ctools_include('ajax');
    ctools_modal_add_js();

    $flag_css_name = 'flag-' . str_replace('_', '-', $variables['flag']->name);
    if (empty($variables['flag_classes'])) {
      $variables['flag_classes'] = '';
    }
    $variables['flag_classes'] .= ' ctools-modal-' . $variables['flag']->confirm_modal_style;
    $variables['flag_classes'] .= ' '. $flag_css_name;

    $path = str_replace("/checkdesk/drupal/", "", $variables['link']['href']);
    $variables['modal_link'] = ctools_modal_text_button($variables['link_text'], $path, $variables['link_title'], $variables['flag_classes']);
  }
}


/**
 * Modal function for `flag_confirm`.
 */
function _checkdesk_core_flags_confirm_modal($action, $flag, $nid, $js) {

  if (!$js) {
    return drupal_get_form('flag_confirm', $action, $flag, $nid);
  }

  module_load_include('inc', 'flag', 'includes/flag.pages');

  ctools_include('modal');
  ctools_include('ajax');
  $title_ac = '';
  if (isset($flag->action)) {
    $action_confirmation = $flag->action . '_confirmation';
    $title_ac = isset($flag->$action_confirmation) ? $flag->$action_confirmation: '';
  }

  // Pass to form generated by the Flag module
  $form_state = array(
    'title' => $title_ac,
    'ajax' => TRUE,
    'build_info' => array(
      'args' => array(
        0 => $action,
        1 => $flag,
        3 => $nid,
      ),
    ),
  );

  $commands = ctools_modal_form_wrapper('flag_confirm', $form_state);

  if (!empty($form_state['executed'])) {
    // Add the responder javascript, required by ctools
    ctools_add_js('ajax-responder');

    // Array with ajax response
    $commands = array();

    // Refresh messages
    $commands[] = ajax_command_html('#messages-container', theme('status_messages'));
    $new_link = trim(flag_create_link($flag->name, $nid));

    // Update link (we need to wrap the link in order to get the correct behavior)
    $commands[] = ajax_command_invoke('.node-' . $nid . ' .flag-' . $flag->name, 'replaceWith', array($new_link));
    $commands[] = checkdesk_core_ajax_command_attach_behaviors('.node-' . $nid . ' .flag-as');

    // Check if this report is flagged and highlight icon or not
    $flags = flag_get_flags('node');
    $class = 'unflagged';
    foreach ($flags as $flag) {
      if ($flag->is_flagged($nid)) {
        $class = 'flagged';
      }
    }
    $commands[] = ajax_command_invoke('.node-' . $nid . ' .flag-as > a', 'removeClass', array('flagged unflagged'));
    $commands[] = ajax_command_invoke('.node-' . $nid . ' .flag-as > a', 'addClass', array($class));

    // Dismiss modal
    $commands[] = ctools_modal_command_dismiss();
  }

  print ajax_render($commands);

  exit();
}

/**
 * Ajax callback for invoking messages
 */
function _checkdesk_core_invoke_messages($action, $type) {

  if ($type != 'ajax') {
    // This is js only.
    return 'Oh well';
  }

  $commands = array();
  $commands[] = ajax_command_prepend('#messages-container', theme('status_messages'));
  $page = array('#type' => 'ajax', '#commands' => $commands);
  ajax_deliver($page);
}

/**
 * Form function for `_checkdesk_core_report_publish`.
 */
function _checkdesk_core_report_publish($form, $form_state, $report) {
  $stories = db_query("
    SELECT nid, title
    FROM {node}
    WHERE type='discussion'
    ")->fetchAllKeyed();
  $form['story'] = array(
    '#type' => 'select',
    '#title' => t('Story'),
    '#options' => $stories,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );
  $form['#report'] = $report;
  return $form;
}

/**
 * Submit function for `_checkdesk_core_report_publish`.
 */
function _checkdesk_core_report_publish_submit($form, &$form_state) {
  // Add the story to the report.
  // TODO Don't add the story to the report if it's already there.
  $report = $form['#report'];
  $report->field_stories[LANGUAGE_NONE][]['target_id'] = $form_state['values']['story'];
  node_save($report);

  // Redirect to story.
  $form_state['redirect'] = array('node/add/post', array('query' => array('report' => $report->nid, 'story' => $form_state['values']['story'])));
}

/**
 * Retrieve action links on given node.
 */
function _checkdesk_core_node_links($node, $account = NULL) {
  global $language, $base_root, $base_path;
  if (!$account) {
    global $user;
    $account = $user;
  }
  $links = array();
  if ($node->type == 'post') {
    $parent_story_id = $node->field_desk[LANGUAGE_NONE][0]['target_id'];
    $update_anchor = 'update-' . $node->nid;
    $url = url('node/'.$parent_story_id, array('absolute' => TRUE, 'alias' => TRUE, 'fragment' => $update_anchor, 'language' => $language));
    // Replace anchor # with %23 to force anchor on share link
    $url = str_replace('#' . $update_anchor, '%23' . $update_anchor, $url);
  }
  else {
    $url = url('node/' . $node->nid, array('absolute' => TRUE, 'alias' => TRUE, 'language' => $language));
  }

  // Try to gracefully redirect the user back to where they were. In some cases
  // this is not a simple task. Ajax based UI is especially difficult.
  $destination = $_GET['q'];

  // When launched from a modal on the reports page, attempt to go back to reports
  // and relaunch the modal.
  if (arg(0) == 'report-view-modal') {
    $destination = 'reports#report-' . arg(2);
  }
  // If the current page smells like AJAX, redirect somewhere safe.
  if (strstr($destination, 'ajax')) {
    $destination = 'reports';
  }
  if (arg(0) == 'reactor') {
    $destination = $_GET['destination'];
  }

  // Links for reports only.
  if ($node->type == 'media') {
    if (_checkdesk_core_report_can_suggest($node)) {
      $links['checkdesk-suggest'] = array(
        'title' => user_access('add report to story') ? t('Add to Story') : t('Suggest to Story'),
        'href' => 'node/' . $node->nid . '/checkdesk/modal/suggest/nojs',
        'query' => array(
          'destination' => $destination,
        ),
      );
    }

    // View original content
    if (isset($node->embed) && isset($node->embed->original_url)) {
      $links['checkdesk-view-original'] = array(
        'title' => t('View original'),
        'href' => $node->embed->original_url,
      );
    }

    // Check if this report is flagged
    $flags = flag_get_flags('node');
    $flagged = FALSE;
    foreach ($flags as $flag) {
      if ($flag->is_flagged($node->nid)) {
        $flagged = TRUE;
      }
    }
    $links['checkdesk-flag'] = array(
      'title' => '',
      'href' => '#',
      'attributes' => array('class' => 'dropdown-toggle ' . ($flagged ? 'flagged' : 'unflagged'), 'data-toggle' => 'dropdown'),
      'html' => TRUE,
      'cd_group' => 'checkdesk-flag',
    );

    $links['checkdesk-ellipsis'] = array(
      'title' => '',
      'href' => '#',
      'attributes' => array('class' => 'dropdown-toggle', 'data-toggle' => 'dropdown'),
      'html' => TRUE,
      'cd_group' => 'checkdesk-ellipsis',
    );
  }

  // Reports or stories can be shared, edited or deleted
  if (in_array($node->type, array('discussion', 'media', 'post'))) {
    if (node_access('update', $node) && $node->type != 'post') {
      $links['checkdesk-edit'] = array(
        'title' => t('Edit'),
        'href' => 'node/' . $node->nid . '/edit',
        'query' => array(
          'destination' => $destination,
        ),
      );
    }
    if (node_access('delete', $node) && $node->type != 'post') {
      // After deleting the report, redirect to current page or previous page, if the current page is the report to be removed
      $destination = current_path();
      if (($destination == 'node/' . $node->nid) || (arg(0) == 'report-view-modal' && arg(2) == $node->nid)) {
        if (isset($_SERVER['HTTP_REFERER'])) {
          $purl = parse_url($_SERVER['HTTP_REFERER']);
          if (@$purl['scheme'] . '://' . @$purl['host'] == $base_root) {
            $langcode = '';
            $alias = preg_replace('/^' . preg_quote($base_path, '/') . '/', '', $purl['path']);
            if (variable_get('locale_language_negotiation_url_part', LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX) == LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX) {
              $alias_list = explode('/', $alias, 2);
              if (count($alias_list) == 2) {
                list($langcode, $alias) = $alias_list;
              }
              if (!in_array($langcode, array_keys(language_list()))) {
                $alias = $langcode . '/' . $alias;
              }
            }
            $destination = drupal_lookup_path('source', urldecode($alias), $langcode);
            if (empty($destination)) $destination = $alias;
          }
          else {
            $destination = '<front>';
          }
        }
        else {
          $destination = '<front>';
        }
      }
      $links['checkdesk-delete'] = array(
        'title' => t('Delete'),
        'href' => 'node/' . $node->nid . '/delete',
        'query' => array(
          'destination' => $destination,
        ),
      );
    }

    // set direction of the dropdown
    $layout = checkdesk_core_direction_settings();
    // Set direction for Updates
    if ($node->type == 'post') {
      $links['dropdown-direction'] = $layout['alpha'];
    } else {
      $links['dropdown-direction'] = $layout['omega'];
    }
    $embed_data = array();
    if ($node->type == 'media' || $node->type == 'discussion') {
      $embed_title = 'Embed this ';
      $embed_title .= ($node->type == 'media') ? 'report' : 'story';
      $embed_data = array('nid' => $node->nid, 'title' => $embed_title);
    }
    $share_links = checkdesk_core_share_links($url, $node->title, $node->type, $embed_data);
    foreach ($share_links as $id => $link) {
      $links[$id] = $link;
    }
  }
  return $links;
}

/**
 * Returns an array containing share links for a node
 */
function checkdesk_core_share_links($url, $title, $type, $embed = array()) {
  $links = array();
  // parent share link with title
  $links['checkdesk-share'] = array(
    'title' => ($type == 'media') ? '' : '<span class="label">' . t('Share') . '</span>',
    'href' => '#',
    'attributes' => array('title' => $title, 'class' => 'dropdown-toggle', 'data-toggle' => 'dropdown'),
    'html' => TRUE,
    'cd_group' => 'checkdesk-share',
  );
  $links['checkdesk-share-facebook'] = array(
    'title' => t('Share on Facebook'),
    'href' => $url,
    'attributes' => array('title' => $title, 'class' => array('facebook')),
    'link_type' => 'link',
    'cd_group' => 'checkdesk-share',
  );
  $links['checkdesk-share-twitter'] = array(
    'title' => t('Share on Twitter'),
    'href' => $url,
    'attributes' => array('title' => $title, 'class' => array('twitter')),
    'link_type' => 'link',
    'cd_group' => 'checkdesk-share',
  );
  $links['checkdesk-share-google'] = array(
    'title' => t('Share on Google+'),
    'href' => $url,
    'attributes' => array('title' => $title, 'class' => array('google')),
    'link_type' => 'link',
    'cd_group' => 'checkdesk-share',
  );
  // show embed if nid has a value
  if (isset($embed['nid'])) {
    if (!isset($embed['title'])) {
      $embed['title'] = 'Embed this story';
    }
    $links['checkdesk-share-embed'] = array(
      'html' => TRUE,
      'title' => t($embed['title']) . '<br><textarea class="embed-code" onclick="this.select();" readonly>' . check_plain(checkdesk_oembed_embed_code($embed['nid'])) . '</textarea>',
      'href' => $url,
      'attributes' => array('title' => $title, 'class' => array('embed'), 'onclick' => 'return false;'),
      'link_type' => 'link',
      'cd_group' => 'checkdesk-share',
    );
  }

  return $links;
}

/**
 * Implements hook_flag_access().
 */
function checkdesk_core_flag_access($flag, $entity_id, $action, $account) {
  // Prevent "flag as graphic" from appearing if report already flagged as graphic by journalist.
  if ($flag->name == 'graphic') {
    $flag_journalist = flag_get_flag('graphic_journalist');
    if ($flag_journalist->is_flagged($entity_id)) {
      return FALSE;
    }
  }
  global $user;
  //do not allow unflag not allowed text to appear to citizen journalist.
  if (in_array('citizen journalist', $user->roles) && $flag->name == 'factcheck_journalist') {
    $flag_factcheck = flag_get_flag('factcheck_journalist');
    if ($flag_factcheck->is_flagged($entity_id)) {
      return FALSE;
    }
  }
}

/**
 * Implements hook_node_view().
 */
function checkdesk_core_node_view($node, $view_mode, $langcode) {
  // Do nothing if view mode is search index
  // as we only need to index title & body
  // check search index display settings
  if ($view_mode == 'search_index') {
    if ($node->type == 'post') {
      if (isset($node->body[LANGUAGE_NONE][0]['value'])) {
        $node->content['body'] = preg_replace('/\[[^:]+:([0-9]+)\]/u', NULL, $node->body[LANGUAGE_NONE][0]['value']);
      }
    }
    return;
  }
  if ($view_mode == 'checkdesk_search') {
    if (!empty($_GET['keys']) && isset($node->body[LANGUAGE_NONE][0]['value'])) {
      $node->content['body'] = search_excerpt($_GET['keys'], $node->body[LANGUAGE_NONE][0]['value']);
    }
    if ($node->type == 'discussion') {
      $updates = db_query('
          SELECT COUNT(entity_id) FROM {field_data_field_desk} WHERE field_desk_target_id = :nid
      ', array(':nid' => $node->nid))->fetchField();
      $node->content['story_updates_count'] = $updates ? format_plural($updates, '1 update', '@count updates') : NULL;
      // collaborators count
      $collaborators = db_query('
          SELECT COUNT(DISTINCT ha.uid)
          FROM {heartbeat_activity} ha
          WHERE nid_target = :nid AND message_id != :message_id
      ', array(':nid' => $node->nid, ':message_id' => 'checkdesk_follow_story'))->fetchField();
      $node->content['story_collaborators_count'] = $collaborators ? format_plural($collaborators, '1 collaborator', '@count collaborators') : NULL;
    }
  }

  if ($view_mode == 'checkdesk_collaborate' || $view_mode == 'checkdesk_search') {
    if ($node->type == 'post') {
      if (isset($node->body[LANGUAGE_NONE][0]['value'])) {
        $node->content['body'] = preg_replace('/\[[^:]+:([0-9]+)\]/u', NULL, $node->body[LANGUAGE_NONE][0]['value']);
        //collect reports
        $reports = $matches = array();
        preg_match_all('/\[[^:]+:([0-9]+)\]/u', $node->body[LANGUAGE_NONE][0]['value'], $matches);
        if (count($matches[1])) {
          foreach ($matches[1] as $key => $nid) {
            $entity = node_load($nid);
            if (is_object($entity)) {
              $reports[] = $entity;
            }
          }
        }
        if (count($reports)) {
          $node->content['update_reports'] = array(
            '#theme' => 'checkdesk_core_update_reports',
            '#reports' => $reports,
          );
          $node->content['update_reports_count'] = format_plural(count($reports), '1 report', '@count reports');
        }
      }
    }
    if ($node->type == 'media') {
      $node->content['comments'] = comment_node_page_additions($node);
      $heartbeat_row = isset($node->heartbeat_row) ? $node->heartbeat_row : '';
      if ($heartbeat_row) {
        $heartbeat_row = $node->heartbeat_row;
        // Load activity status with verification footnote
        if ($heartbeat_row->heartbeat_activity_message_id == 'status_report') {
          $heartbeat_activity = heartbeat_activity_load($heartbeat_row->uaid);
          $node->content['report_activity_status'] = array(
            '#theme' => 'checkdesk_core_report_activity_status',
            '#heartbeat_activity' => $heartbeat_activity,
          );
        }
        // Load verification footnote
        if ($heartbeat_row->heartbeat_activity_message_id == 'checkdesk_comment_on_report') {
          $heartbeat_activity = heartbeat_activity_load($heartbeat_row->uaid);
          $footnote = comment_load($heartbeat_activity->cid);
          $node->content['report_verification_footnote'] = isset($footnote->comment_body[LANGUAGE_NONE][0]['value']) ? $footnote->comment_body[LANGUAGE_NONE][0]['value'] : '';
        }
      }
      $node->content['field_link'] = _meedan_render_oembed_activity_type($node, $heartbeat_row);
    }
  }

  // Get node links.
  $links = _checkdesk_core_node_links($node);
  if (!empty($links)) {
    $node->content['links']['checkdesk'] = array(
      '#theme' => 'links',
      '#links' => $links,
      '#attributes' => array('class' => array('links', 'inline')),
    );
  }

  // Add decorations to story nodes.
  if ($node->type == 'discussion') {
    $node->content['story_blogger'] = array(
      '#theme' => 'checkdesk_core_story_blogger',
      '#story' => $node,
    );
    $node->content['story_status'] = array(
      '#theme' => 'checkdesk_core_story_status',
      '#story' => $node,
    );
    $node->content['story_drafts'] = array(
      '#theme' => 'checkdesk_core_story_drafts',
      '#story' => $node,
    );

    // Facebook tags
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:title',
        'content' => strip_tags($node->title),
      ),
    );
    drupal_add_html_head($element, 'meta_og_title');
    $description = strip_tags(preg_replace('/\n|\r/', ' ', token_replace('[node:summary]', array('node' => $node), array('clear' => TRUE))));
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:description',
        'content' => (empty($description) ? '-' : $description),
      ),
    );
    drupal_add_html_head($element, 'meta_og_description');
    $element = array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => 'og:image',
        'content' => (empty($node->field_lead_image) ? '' : file_create_url($node->field_lead_image[LANGUAGE_NONE][0]['uri'])),
      ),
    );
    drupal_add_html_head($element, 'meta_og_image');
  }
  // Add decorations to report nodes.
  if ($node->type == 'media') {
    $node->content['report_source'] = array(
      '#theme' => 'checkdesk_core_report_source',
      '#report' => $node,
    );
  }
}

/*
 * Implements hook_contextual_links_view_alter().
 */
function checkdesk_core_contextual_links_view_alter(&$element, $items) {
  if (!isset($element['#element']['#node']->nid)) return;
  $links = _checkdesk_core_node_links($element['#element']['#node']);
  if (!empty($links)) {
    $element['#links'] += $links;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for `post_node_form`.
 */
function checkdesk_core_form_post_node_form_alter(&$form, &$form_state) {
  global $user;

  // Adjust compose update form
  $form['title']['#title'] = t('Update headline');
  $form['body'][LANGUAGE_NONE][0]['#title'] = t('Text');
  $form['body'][LANGUAGE_NONE][0]['#attributes']['placeholder'] = t('Write text and drag reports here to compose the update');

  // Are we showing the post form on the desk page?
  if (($node = menu_get_object()) && $node->type == 'discussion') {
    // Hard-code desk reference to current desk.
    $form['field_desk'][LANGUAGE_NONE]['#default_value'] = $node->nid;
    $form['field_desk']['#access'] = false;
  }

  // Make the body field a drop target for reports.
  $form['body']['#prefix'] = '<div class="droppable">';
  $form['body']['#suffix'] = '</div>';

  // Set language
  global $language;
  $form['language'] = array(
    '#type' => 'value',
    '#value' => $language->language,
  );

  // Set default parameters if any.
  if (isset($_GET['story'])) {
    // Hard-code desk reference to given desk.
    $form['field_desk'][LANGUAGE_NONE]['#default_value'] = $_GET['story'];
    $form['field_desk']['#access'] = false;
  }
  if (isset($_GET['report'])) {
    // Add given report to body.
    $node = node_load($_GET['report']);
    $form['body'][LANGUAGE_NONE][0]['#default_value'] = checkdesk_core_droppable_reference($node);
    $form['body'][LANGUAGE_NONE][0]['#format'] = 'liveblog';
  }
  $form['#validate'][] = '_checkdesk_core_post_node_form_validate';
  $form['actions']['submit']['#submit'][] = $form['actions']['draft']['#submit'][] = '_checkdesk_core_post_node_form_submit';

  if ($form['field_desk']['#access']) {
    $options = array('_none' => t('- Select a value -')) + _checkdesk_get_stories_by_activity();
    $form['field_desk'][LANGUAGE_NONE]['#options'] = $options;
    $form['field_desk'][LANGUAGE_NONE]['#attributes']['onchange'] = "_checkdesk_filter_reports(jQuery(this).val());";
    // Handle HTML entities
    foreach ($form['field_desk'][LANGUAGE_NONE]['#options'] as $key => $value) {
      $form['field_desk'][LANGUAGE_NONE]['#options'][$key] = htmlspecialchars_decode($value);
    }
  }

  if (!in_array('administrator', array_values($user->roles))) {
    $form['additional_settings']['#access'] = FALSE;
  }

  // Change title.
  drupal_set_title(t('Compose Update'));
}

/**
 * Submit function for `post_node_form`.
 */
function _checkdesk_core_post_node_form_submit($form, &$form_state) {
  // Add wording for saving draft.
  if ($form_state['triggering_element']['#value'] == $form['actions']['draft']['#value']) {
    drupal_set_message(t('@type %title saved as draft.', array('@type' => t('Update'), '%title' => $form_state['values']['title'])));
  }
  $redirect_nid = $form_state['values']['field_desk'][LANGUAGE_NONE][0]['target_id'];
  $form_state['redirect'] = array('node/' . $redirect_nid, array('fragment' => 'update-'. $form_state['nid']));
}

/**
 * Validation function for `post_node_form`.
 */
function _checkdesk_core_post_node_form_validate($form, &$form_state) {
  // Prevent user from saving a new draft if another one exists already.
  if ($form_state['triggering_element']['#value'] == $form['actions']['draft']['#value']) {
    $desk_nid = $form_state['values']['field_desk'][LANGUAGE_NONE][0]['target_id'];
    global $user;
    $draft_nid = db_query("
  SELECT n.nid
  FROM {node} n INNER JOIN {field_data_field_desk} d ON n.nid = d.entity_id
  WHERE n.type = 'post'
  AND n.status = 0
  AND d.field_desk_target_id = :desk_nid
  AND n.uid = :uid
    ", array(':desk_nid' => $desk_nid, ':uid' => $user->uid))->fetchCol();
    if ($draft_nid) {
      form_set_error('field_desk',
        t('This story already has a draft that you created. You cannot save more than one draft for each story. You can <a href="@url">edit that draft now</a>.',
          array('@url' => url('node/' . $desk_nid))
        )
      );
    }
  }

}

/**
 * Implements hook_form_FORM_ID_alter() for `discussion_node_form`.
 *
 * Ajax-enable the discussion form as requested.
 */
function checkdesk_core_form_discussion_node_form_alter(&$form, &$form_state) {

  //Adjust create story form
  $form['title']['#title'] = t('Story title');
  // $form['title']['#attributes']['placeholder'] = t('Story title');

  $form['body'][LANGUAGE_NONE][0]['#attributes']['placeholder'] = t('Add a brief description of the story (optional)');
  $form['field_tags'][LANGUAGE_NONE]['#attributes']['placeholder'] = t('Add tags');

  $form['body'][LANGUAGE_NONE][0]['#title'] = t('Text');
  $form['body'][LANGUAGE_NONE][0]['#description'] =
    t('A story contains one or more liveblog updates. The story will remain unpublished until the first update is created.');
  // Make the body field a drop target for reports.
  $form['body']['#prefix'] = '<div class="droppable">';
  $form['body']['#suffix'] = '</div>';
  // add custom class for image uploader plus hide description with class nodescription
  $form['field_lead_image']['#prefix'] = '<div class="custom_file_upload nodescription">';
  $form['field_lead_image']['#suffix'] = '</div">';
  $form['field_lead_image'][LANGUAGE_NONE][0]['#title'] = t('Add feature image');
  $form['field_lead_image']['#description'] = '';
  $form['actions']['submit']['#submit'][] = '_redirect_story';
  // language field
  $form['language']['#weight'] = 99;
  unset($form['language']['#options'][LANGUAGE_NONE]);
  if (!$form['nid']['#value']) {
    global $language;
    $form['actions']['submit']['#value'] = t('Create story');
    $form['actions']['submit']['#suffix'] =
      '<div class="description">'.
      t('<span>Note:</span> Your story won\'t be published to the liveblog homepage until you add an update to your story.') .
      '</div>';
    //Set default language value
    $form['language']['#default_value'] = $language->language;
  }
  if (count($form_state['build_info']['args']) <= 1 || $form_state['build_info']['args'][1] != 'ajax') {
    return;
  }

  $form['#prefix'] = '<div id="discussion-form-wrapper">';
  $form['#suffix'] = '</div>';

  // Helper class caught by Drupal.behaviors.checkdeskKeepTBDropdownsOpen
  // after the form is rebuilt by AJAX we need the hacks to stay active.
  $form['#attributes']['class'][] = 'cd-keep-tb-dropdown-open';

  $file_size = $form['field_lead_image'][LANGUAGE_NONE][0]['#upload_validators']['file_validate_size'][0];
  $formats = $form['field_lead_image'][LANGUAGE_NONE][0]['#upload_validators']['file_validate_extensions'][0];
  $file_upload_description = t('Image must be less than !size.', array('!size' => format_size($file_size))) .
                             ' ' .
                             t('Allowed file types: !extensions.', array('!extensions' => $formats));
  $form['field_lead_image'][LANGUAGE_NONE][0]['#description'] = $file_upload_description;

  $form['actions']['submit']['#ajax'] = array(
    'callback' => 'checkdesk_core_discussion_ajax_node_form_submit_callback',
    'wrapper' => 'discussion-form-wrapper',
    'method' => 'replace',
    'effect' => 'fade',
    'selector' => '#edit-submit-story',
  );
  $form['actions']['submit']['#submit'][] = 'checkdesk_core_discussion_node_form_submit_callback';
  $form['actions']['submit']['#attributes']['id'] = 'edit-submit-story';

  $form['actions']['cancel'] = array(
    '#type' => 'button',
    '#value' => t('Cancel'),
    '#attributes' => array(
      'onclick' => "document.getElementById('discussion-form-menu-link').click(); return false;"
    ),
    '#weight' => 15,
  );

  $form['body'][$form['#node']->language][0]['#after_build'][] = 'checkdesk_core_discussion_node_form_after_build';

  // Make the upload field customizable
  drupal_add_js(libraries_get_path('fileinput') . '/jquery.fileinput.js');
  drupal_add_js(drupal_get_path('module', 'checkdesk_core') . '/js/fileinput.js');
  $fileinput = array(
    'change' => t('Change'),
    'button' => t('Browse'),
    'field'  => t('Add optional feature image'),
  );
  drupal_add_js(array('fileInput' => $fileinput), 'setting');
  drupal_add_css(libraries_get_path('fileinput') . '/fileinput.css');
}

/**
 * Redirect story to collaboration page.
 */
function _redirect_story($form, &$form_state) {
  $values = $form_state['values'];
  if (!$form['nid']['#value']) {
    $_SESSION['report_tooltip'] = TRUE;
  }
  $form_state['redirect'] = 'node/' . $values['nid'] . '/collaboration';
}

/**
 * Append extra information
 */
function checkdesk_core_discussion_node_form_after_build($element) {
  $element['#id'] .= '-noconflict';

  if (isset($element['format']) && isset($element['format']['format'])) {
    $element['format']['format']['#id'] .= '-noconflict';
  }

  return $element;
}

/**
 * Submit handler to be invoked AFTER node_form_submit().
 *
 * Removes redirect added by node_form_submit() to ensure AJAX commands
 * are returned correctly.
 */
function checkdesk_core_discussion_node_form_submit_callback($form, &$form_state) {
  if (!form_get_errors()) {
    unset($form_state['redirect']);

    // Reset the form form next usage. This is critical else drupal_get_form()
    // in checkdesk_core_discussion_ajax_node_form_submit_callback() can
    // double submit the form!
    //
    // See: http://drupal.org/node/1350700
    $form_state['input'] = array();
    $form_state['rebuild'] = TRUE;
  }
}

/**
 * Delivers the updated discussion node form after the #ajax enabled node form is
 * submitted.
 */
function checkdesk_core_discussion_ajax_node_form_submit_callback($form, &$form_state) {
  global $user;

  // Return the actual form if it contains errors.
  if (form_get_errors()) {
    return $form;
  }

  $commands = array();

  // Redirect to compose update page is user is not on it yet
  if (isset($_SERVER["HTTP_REFERER"]) && $_SERVER["HTTP_REFERER"] !== url('node/add/post', array('absolute' => TRUE))) {
    $commands[] = ctools_ajax_command_redirect('node/add/post');
  }

  // Update form if user is on compose update page
  else {
    $node = $form_state['node'];

    $title_link = l('<strong>' . check_plain($node->title) . '</strong>', 'node/' . $node->nid, array('html' => TRUE));
    $success_message = t("!title created successfully.", array('!title' => $title_link));

    // Yuck. Need to wipe $_POST to trick drupal_get_form() into creating a
    // brand new form. If we don't do this drupal_get_form() will latch onto the
    // old build_id. There appears to be no way around this in D7.
    $_POST = array();
    $new_node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'discussion', 'language' => LANGUAGE_NONE);
    $fresh_form = drupal_get_form('discussion_node_form', $new_node, 'ajax');

    $fresh_form['create_another_story'] = array(
      '#type'   => 'markup',
      '#markup' => '<h2>' . t('Create another story') . '</h2>',
      '#weight' => -500,
    );

    $commands[] = ajax_command_replace('#discussion-form-wrapper', drupal_render($fresh_form));
    $commands[] = ajax_command_prepend('#discussion-form-wrapper', '<div class="messages success">' . $success_message . '</div>');
    $commands[] = ajax_command_append('#edit-field-desk-und', form_select_options(array('#options' => array($node->nid => $node->title))));
  }

  ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));

  // Some rouge actor is throwing extra ajax commands after these ones causing
  // invalid JSON.
  drupal_exit();
}

/**
 * Implements hook_form_FORM_ID_alter() for `comment_node_discussion_form`.
 */
function checkdesk_core_form_comment_node_discussion_form_alter(&$form, &$form_state) {
  // Hide comment attachment field on comment form.
  $form['field_attachment']['#access'] = false;
}

/**
 * Implements hook_views_pre_render().
 */
function checkdesk_core_views_pre_render(&$view) {
  if ($view->name == 'desk_reports') {
    // Setup drag & drop.
    drupal_add_js(libraries_get_path('insertatcaret') . '/jquery.insertatcaret.js');

    $data = array();
    foreach ($view->result as $datum) {
      $node = (object) array(
        'nid'   => $datum->nid,
        'title' => $datum->node_title,
        'type'  => 'media',
      );

      $datum->droppable_ref = checkdesk_core_droppable_reference($node);

      $data['report-' . $datum->nid] = $datum;
    }

    // Send view results to client.
    drupal_add_js(array('checkdesk' => array('reports' => $data)), 'setting');
  }
  else if ($view->name == 'liveblog') {
    foreach ($view->result as $id => $story) {
      $updates = views_get_view('updates_for_stories');
      $updates->set_arguments(array($story->nid));
      $updates->get_total_rows = TRUE;
      $output = $updates->preview('block_1');
      $total_rows = $updates->total_rows;
      $updates->destroy();
      if ($total_rows) {
        $view->result[$id]->updates = $output;
      }
    }
  }
  elseif ($view->name == 'story_collaboration') {
    foreach ($view->result as $k => $v) {
      // Localize some variables
      $variables = heartbeat_decode_message_variables($v->heartbeat_activity_variables);
      foreach ($variables as $key => $value) {
        if (in_array($key, array('!flag_type', '!fact_checking_status', '!status'))) {
          $variables[$key] = t($value);
        }   
      }
      $view->result[$k]->heartbeat_activity_variables = heartbeat_encode_message_variables($variables);
    }
  }
  elseif ($view->name == 'updates_for_stories') {
    if (in_array($view->current_display, array('block', 'page_1')) && isset($_REQUEST['autorefreshRequest'])) {
      // Update total rows so autorefresh can set correct update numbers 'update #'
      $nid = $_REQUEST['original_view_data']['view_args'];
      if ($nid) {
        $updates_count = db_query(' SELECT COUNT(*)
                  FROM {node} n
                  INNER JOIN {field_data_field_desk} fd ON n.nid = fd.entity_id
                  WHERE n.type = :type AND n.status = :status AND field_desk_target_id = :nid
                  ', array(':type' => 'post', ':status' => 1, ':nid' => $nid)
        )->fetchField();
        $view->total_rows = $updates_count;
      }
    }
  }
  elseif ($view->name == 'checkdesk_search') {
    if ($view->current_display == 'attachment_1') {
      if (!empty($view->exposed_raw_input['keys'])) {
        //Fix result count due to "group by" that generated by search module.
        $exists_type = array();
        foreach ($view->result as $k => &$row) {
          if (isset($exists_type[$row->node_type_1])) {
            $view->result[$exists_type[$row->node_type_1]]->node_type += 1;
            unset($view->result[$k]);
          }
          else {
            $row->node_type = 1;
            $exists_type[$row->node_type_1] = $k;
          }
        }
      }
      $types = array(
        'media' => array('s' => 'Report', 'p' => 'Reports'),
        'post' => array('s' => 'Update', 'p' => 'Updates'),
        'discussion' => array('s' => 'Story', 'p' => 'Stories'),
      );
      foreach ($view->result as $k => &$row) {
        $row->node_type_1 = ($row->node_type > 1) ? t($types[$row->node_type_1]['p']) : t($types[$row->node_type_1]['s']);
      }
    }
  }
}

/**
 * (Ab)use pathauto to create the drag and drop media reference.
 *
 * @param $node
 *  A node object, needs at least 'nid' and 'title' attributes.
 */
function checkdesk_core_droppable_reference($node) {
  module_load_include('inc', 'pathauto');
  $pathauto_pattern = '[node:title]';

  // Replace any tokens in the pattern. Uses callback option to clean replacements. No sanitization.
  $alias = token_replace($pathauto_pattern, array('node' => $node), array(
    'sanitize' => FALSE,
    'clear' => TRUE,
    'callback' => 'pathauto_clean_token_values',
    'language' => (object) array('language' => LANGUAGE_NONE),
    'pathauto' => TRUE,
  ));
  $alias = pathauto_clean_alias($alias);

  return '[' . $alias . ':' . $node->nid . ']';
}

/**
 * Implements hook_entity_property_info().
 */
function checkdesk_core_entity_property_info() {
  $info = array();
  $properties = &$info['node']['bundles']['post']['properties'];

  $properties['reports'] = array(
    'label' => t('Reports'),
    'type' => 'list<node>',
    'description' => t("List of reports in this post."),
    'getter callback' => 'checkdesk_core_entity_property_get_reports',
  );
  return $info;
}

/**
 * Getter function for `reports` property.
 */
function checkdesk_core_entity_property_get_reports($node, array $options, $name, $entity_type) {
  $reports = array();
  if (!isset($node->body[LANGUAGE_NONE][0])) return $reports;
  $text = $node->body[LANGUAGE_NONE][0]['value'];
  $matches = array();
  preg_match_all('/\[[^:]+:([0-9]+)\]/u', $text, $matches);
  if (count($matches[1])) {
    $output = array();
    foreach ($matches[1] as $key => $nid) {
      if (is_numeric($nid)) {
        $node = node_load($nid);
        if (is_object($node)) {
          $reports[] = $node;
        }
      }
    }
  }
  return $reports;
}

/**
 * Implements hook_form_FORM_ID_alter() for `views_exposed_form`.
 */
function checkdesk_core_form_views_exposed_form_alter(&$form, &$form_state) {
  if ($form['#id'] == 'views-exposed-form-desk-reports-block') {
    $title_options = array('contains' => t('Show reports with this keyword'), 'not'=> t('Exclude report with this keyword'));
    $source_options = array('contains' => t('Show reports from this source'), 'not'=> t('Exclude report from this source'));
    $form['title_op']['#options'] = $title_options;
    $form['source_op']['#options'] = $source_options;
    $form['source_op']['#process'] = $form['title_op']['#process'] = array('form_process_radios');
    $form['source_op']['#attributes'] = $form['title_op']['#attributes'] = array('class' => array('bef-select-as-radios'));
    $form['source_op']['#theme'] = $form['title_op']['#theme'] = 'select_as_radios';
    $form['field_stories_target_id']['#options'] = array_reverse($form['field_stories_target_id']['#options'], TRUE);
    //Display filter info.
    if (!empty($_REQUEST['title'])) {
      $form['title']['#description'] = str_replace(array('{key:contains}', '{key:not}'), array('Showing reports with', 'Excluding reports with'), $form['title']['#description']);
    }
    else {
      $form['title']['#description'] = NULL;
    }
    $form['title']['#attributes']['placeholder'] = t('Keyword');
    if (isset($_REQUEST['source'])) {
      $form['source']['#description'] = str_replace(array('{key:contains}', '{key:not}'), array('Showing reports from', 'Excluding reports from'), $form['source']['#description']);
    }
    else {
      $form['source']['#description'] = NULL;
    }
    $form['source']['#attributes']['placeholder'] = 'YouTube'; // don't translate this as the sources database won't understand the translation.
    //Fix reset button
    $form['#action'] = url($_GET['q']);
    if (checkdesk_core__get_desk_reports_args() !== 'all' || (isset($_GET['q']) && $_GET['q'] == 'node/add/discussion')) {
      $form['field_stories_target_id']['#access'] = FALSE;
      $form['#info']['filter-field_stories_target_id'] = FALSE;
    }
  }

  if ($form['#id'] == 'views-exposed-form-checkdesk-search-page') {
    // Add custom filed for type
    $form['type'] = array(
      '#type' => 'select',
      '#title' => '',
      '#options' => array(
        'All' => t('Everything'),
        'report' => t('Reports'),
        'story' => t('Stories'),
        'update' => t('Updates'),
      ),
      '#theme' => 'select_as_links',
    );
    // this value determines the position of the new element.
    $insert_index = 2;
    $element_to_insert = array();
    $element_to_insert['filter-type'] = array(
      'value' => 'type',
    );
    $form_info_top = array_slice($form['#info'], 0, $insert_index);
    $form_info_bottom = array_slice($form['#info'], $insert_index);
    $new_form_info = $form_info_top + $element_to_insert + $form_info_bottom;
    $form['#info'] = $new_form_info;
    // Add required js for fastLiveFilter plugin
    drupal_add_js(drupal_get_path('module', 'checkdesk_core') . '/js/jquery-fastLiveFilter/jquery.fastLiveFilter.js');
    drupal_add_js(drupal_get_path('module', 'checkdesk_core') . '/js/checkdesk_search.js');
    $form['field_tags_tid']['#fastlivefilte_placeholder'] = t('Search for tag');
    //Hide/show media reports based on type filter
    if (!isset($_GET['type']) || (isset($_GET['type']) && $_GET['type'] != 'report')) {
      $form['#info']['filter-field_rating_tid']['label'] = NULL;
      $form['field_rating_tid']['#type'] = 'hidden';
      unset($form['field_rating_tid']['#theme']);
    }
    // Media filters
    if (isset($_GET['type']) && $_GET['type'] == 'report') {
      // Change -Any- status label
      $form['field_rating_tid']['#options']['All'] = t('Any status');
      $form['media_flags'] = array(
        '#type' => 'select',
        '#title' => t('Flags'),
        '#options' => array(
          'All' => t('Any flag'),
          'flagged_gc' => t('Graphic content'),
          'flagged_spam' => t('Spam'),
        ),
        //'#multiple' => TRUE,
        '#theme' => 'select_as_links',
      );
    }
    // Hide tag filter for updates
    if (isset($_GET['type']) && $_GET['type'] == 'update') {
      $form['#info']['filter-field_tags_tid']['label'] = NULL;
      $form['field_tags_tid']['#type'] = 'hidden';
      unset($form['field_tags_tid']['#theme']);
    }
    // Hide update choice if user filter by tag.
    if (isset($_GET['field_tags_tid']) && is_numeric($_GET['field_tags_tid'])) {
      unset($form['type']['#options']['update']);
    }

    $form['keys']['#attributes']['placeholder'] = t('Search');

    // Add author filter for admin or journalist
    global $user;
    if ($user->uid) {
      $users = array();
      if (in_array('administrator', $user->roles) || in_array('journalist', $user->roles)) {
        $users = db_query('
              SELECT name FROM {users} WHERE status = :status AND uid != :uid ORDER BY name
    ', array(':status' => 1, ':uid' => $user->uid))->fetchAllKeyed(0, 0);
      }
      $users = array('All' => t('- Any -'), $user->name => t('- Mine -')) + $users;
      $form['author'] = array(
        '#type' => 'select',
        '#title' => t('Authors'),
        '#options' => $users,
        '#theme' => 'select_as_links',
        '#bef_enable_fastlivefilter' => 1,
        '#fastlivefilte_placeholder' => t('Search for author'),
      );
    }
      // Hide sort and submit button
    $form['sort_bef_combine']['#type'] = 'hidden';
    $form['submit']['#attributes']['class'][] = 'js-hide';
  }
}

/**
 * Implements hook_theme().
 */
function checkdesk_core_theme() {
  $themes = array();
  $base = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'checkdesk_core') . '/theme',
  );

  $themes['checkdesk_core_story_blogger'] = array(
    'template' => 'story_blogger',
    'variables' => array(
      'story' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_story_status'] = array(
    'template' => 'story_status',
    'variables' => array(
      'story' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_story_drafts'] = array(
    'template' => 'story_drafts',
    'variables' => array(
      'story' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_report_source'] = array(
    'template' => 'report_source',
    'variables' => array(
      'report' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_user_info'] = array(
    'template' => 'user_info',
    'variables' => array(
      'user' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_update_reports'] = array(
    'template' => 'update_reports',
    'variables' => array(
      'reports' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_report_activity'] = array(
      'template' => 'report_activity',
      'variables' => array(
        'node' => NULL,
        'content' => NULL,
        'view_mode' => NULL,
      ),
    ) + $base;

  $themes['checkdesk_core_report_activity_status'] = array(
    'template' => 'report_activity_status',
    'variables' => array(
      'heartbeat_activity' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_report_activity_count'] = array(
    'template' => 'report_activity_count',
    'variables' => array(
      'count' => NULL,
      'nid' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_report_activity_stream'] = array(
    'template' => 'report_activity_stream',
    'variables' => array(
      'activity' => NULL,
      'nid' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_render_links'] = array(
    'variables' => array(
      'options' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_render_search_header'] = array(
      'template' => 'checkdesk_search_header',
      'variables' => array(
      'links' => NULL,
    ),
  ) + $base;

  $themes['checkdesk_core_main_navigation'] = array(
      'template' => 'checkdesk_main_navigation',
      'variables' => array(
      'first_group' => NULL,
      'second_group' => NULL,
      'third_group' => NULL,
    ),
  ) + $base;

  return $themes;
}

/**
 * API function to find whether user is online or offline.
 */
function checkdesk_core_user_online($account = NULL) {
  if (!$account) {
    global $user;
    $account = $user;
  }
  $interval = REQUEST_TIME - variable_get('user_block_seconds_online', 900);
  $count = db_query("SELECT COUNT(DISTINCT s.uid) FROM {sessions} s WHERE s.timestamp >= :timestamp AND s.uid = :uid", array(':timestamp' => $interval, ':uid' => $account->uid))->fetchField();
  return $count > 0;
}

/**
 * API function to find whether a node is flagged for fact-checking.
 */
function checkdesk_core_fact_checking($node) {
  $flag_name = 'factcheck';
  $flag = flag_get_flag($flag_name);
  if (!$flag) {
    watchdog('checkdesk', 'Flag "@flag" not found for fact-checking.', array('@flag' => $flag_name), WATCHDOG_ERROR);
    return FALSE;
  }
  return $flag->is_flagged($node->nid);
}

/**
 * API function to return number of drafted updates of a story.
 */
function checkdesk_core_story_updates_count($node, $drafted_only = FALSE) {
  $status = $drafted_only ? 0 : 1;
  $count = db_query("SELECT COUNT(*) FROM {node} n INNER JOIN {field_data_field_desk} f ON f.entity_id = n.nid WHERE n.type = 'post' AND n.status = :status AND f.bundle = 'post' AND field_desk_target_id = :target_nid", array(':status' => $status, ':target_nid' => $node->nid))->fetchField();
  return intval($count);
}

/**
 * Implements hook_block_info().
 */
function checkdesk_core_block_info() {
  $blocks = array();

  $blocks['post'] = array(
    'info' => 'Report form block',
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['checkdesk_user_info'] = array(
    'info'   => t('Checkdesk user information'),
    'cache'  => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function checkdesk_core_block_view($delta = '') {
  switch ($delta) {
    case 'post':
      return checkdesk_core_report_form_block();
    case 'checkdesk_user_info':
      return checkdesk_core_user_info_block();
  }
}

/**
 * Generate report form.
 */
function checkdesk_core_report_form_block() {
  if (!user_access('create post content')) {
    return array('subject' => NULL, 'content' => NULL);
  }

  // Include page handler for node_add()
  module_load_include('inc', 'node', 'node.pages');
  $title = drupal_get_title();

  // If we're on a story page and there's already a draft, show it.
  $desk_nid = 0;
  if (($node = menu_get_object()) && $node->type == 'discussion') {
    $desk_nid = $node->nid;
  }
  global $user;
  $draft_nid = db_query("
SELECT n.nid
FROM {node} n INNER JOIN {field_data_field_desk} d ON n.nid = d.entity_id
WHERE n.type = 'post'
AND n.status = 0
AND d.field_desk_target_id = :desk_nid
AND n.uid = :uid
  ", array(':desk_nid' => $desk_nid, ':uid' => $user->uid))->fetchCol();
  if ($draft_nid) {
    $draft = node_load($draft_nid);
    $content = node_page_edit($draft);
    $subject = t('Edit draft update');
  }
  else {
    $content = node_add('post');
    $subject = t('Compose new update');
  }

  drupal_set_title($title);
  return array('subject' => $subject, 'content' => $content);
}

/**
 * Generates a block with user information.
 */
function checkdesk_core_user_info_block() {
  $content = '';
  if (arg(0) == 'user' && is_numeric(arg(1))) {
    $profile = user_load(arg(1));
    $content = theme('checkdesk_core_user_info', array('user' => $profile));
  }
  return array('subject' => '<none>', 'content' => $content);
}

/**
 * Implements hook_heartbeat_theme_alter()
 */
function checkdesk_core_heartbeat_theme_alter(&$messages, HeartbeatStream $heartbeatStream) {
  global $base_path, $base_root, $language;
  // Localize some variables
  foreach ($messages as $key => $message) {
    foreach ($message->variables as $variable => $value) {
      // Translate strings
      if (in_array($variable, array('!flag_type', '!fact_checking_status', '!status'))) {
        $messages[$key]->variables[$variable] = t($value);
      }
      // Localize URLs
      else if (in_array($variable, array('!url', '!user_url', '!story_url', '!report_url', '!update_url', '!flag_author_url'))) {
        $url = parse_url($value);
        if ($url) {
          $langcode = '';
          $alias = preg_replace('/^' . preg_quote($base_path, '/') . '/', '', $url['path']);
          if (variable_get('locale_language_negotiation_url_part', LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX) == LOCALE_LANGUAGE_NEGOTIATION_URL_PREFIX) {
            $alias_list = explode('/', $alias, 2);
            if (count($alias_list) == 2) {
              list($langcode, $alias) = $alias_list;
            }
            if (!in_array($langcode, array_keys(language_list()))) {
              $alias = $langcode . '/' . $alias;
            }
          }
          $path = drupal_lookup_path('source', urldecode($alias), $langcode);
          if (empty($path)) $path = $alias;
          $messages[$key]->variables[$variable] = url($path, array('language' => $language, 'absolute' => TRUE, 'alias' => TRUE));
        }
      }
    }
    $messages[$key]->message = t($message->template->message, $message->variables);
  }

  // Additional processing is not necessary for notifications
  $view = views_get_current_view();
  if (isset($view) && $view->name == 'my_notifications') return;

  foreach ($messages as $key => $message) {
    if ($message->nid > 0 && in_array($message->message_id, array('status_report', 'new_comment_report', 'new_report', 'publish_report'))) {
      $node = node_load($message->nid);
      if ($node->type == 'media') {
        $messages[$key]->message = theme('checkdesk_heartbeat_content',  array(
          'message' => $message,
          'node' => $node,
          ));
      }
    }
  }
}

define('RATING_IN_PROGRESS', 'In Progress');
define('RATING_FALSE', 'False');
define('RATING_VERIFIED', 'Verified');

/**
 * Implements hook_form_FORM_ID_alter() for `comment_node_media_form`.
 */
function checkdesk_core_form_comment_node_media_form_alter(&$form, $form_state, $form_id) {
  $term = isset($form['#node']->field_rating[LANGUAGE_NONE][0]['taxonomy_term']) ?
    $form['#node']->field_rating[LANGUAGE_NONE][0]['taxonomy_term'] :
    taxonomy_term_load($form['#node']->field_rating[LANGUAGE_NONE][0]['tid']);
  if (!in_array($term->name, array(RATING_IN_PROGRESS, RATING_FALSE, RATING_VERIFIED))) {
    $form['#access'] = FALSE;
  }
  else {
    // Adjust node comments form
    $nid = $form['#node']->nid;
    $form['author']['homepage'] = NULL;
    $form['author']['mail'] = NULL;
    $form['actions']['submit']['#attributes']['class'] = array('btn');
    $form['comment_body'][LANGUAGE_NONE][0]['#attributes']['rows'] = 1;
    $form['comment_body']['und'][0]['#attributes']['class'] = array('expanding');
    $form['actions']['submit']['#value'] = t('Add footnote');
    $form['actions']['submit']['#ajax'] = array(
      'callback' => '_checkdesk_comment_form_submit',
      'wrapper' => 'node-' . $nid,
      'method' => 'replace',
      'effect' => 'fade',
    );
    $form_state['ctools comment alter'] = FALSE;

    $form['comment_body'][LANGUAGE_NONE][0]['#attributes']['placeholder'] = t('Add footnote');

    $form['field_rating'][LANGUAGE_NONE]['#default_value'] = $term->name;

    $form['field_rating'][LANGUAGE_NONE]['#prefix'] = '<div class="report-activity-edit-status"><span class="current-status ' . preg_replace('/\s+/', '-', trim(strtolower($term->name))) . '">' . t($term->name) . '</span>';
    $form['field_rating'][LANGUAGE_NONE]['#suffix'] = '</div>';
    $form['field_rating'][LANGUAGE_NONE]['#title'] = t('Edit Status');
    $form['field_rating'][LANGUAGE_NONE]['#description'] = t('Pick the appropriate verification status');

    // Options
    $options = array();
    foreach ($form['field_rating'][LANGUAGE_NONE]['#options'] as $tid => $name) {
      if ($tid !== '_none') {
        $term = taxonomy_term_load($tid);
        $options[$term->name] = t($term->name);
      }
    }
    $form['field_rating'][LANGUAGE_NONE]['#options'] = array_reverse($options);
    $form['#validate'] = array('_checkdesk_core_comment_form_validate');
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function checkdesk_core_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    // Move mymodule_form_alter() to the end of the list. module_implements()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['checkdesk_core'];
    unset($implementations['checkdesk_core']);
    $implementations['checkdesk_core'] = $group;
  }
}

function _redirect_footnote_delete($form, &$form_state) {
  if (isset($form_state['redirect'])) {
    $form_state['redirect'] = $_SESSION['comment_referer'];
    unset($_SESSION['comment_referer']);
  }
}

/**
 * Implements hook_form_alter().
 */
function checkdesk_core_form_alter(&$form, $form_state, $form_id) {
  //Redirect user to right place after delete footnote
  if ($form_id == 'comment_confirm_delete' && $form['#comment']->node_type == 'comment_node_media') {
    if(!isset($_SESSION['comment_referer'])) {
      //use session to catch referer as destination did not work well with AJAX requests
      $_SESSION['comment_referer'] = $_SERVER['HTTP_REFERER'];
    }
    $form['#submit'][] = '_redirect_footnote_delete';
  }
  // Add a class to forms which should display inline errors
  $ife_form_ids = checkdesk_core_ife_form_ids();
  foreach ($ife_form_ids as $fid => $row) {
    if($form_id == $fid) {
      $form['#attributes']['class'][] = 'ife';
    }
  }
  if ($form_id == 'system_site_information_settings' || $form_id == '_checkdesk_core_settings') {
    //alter submit to purge all varnish caches
    $form['#submit'][] = 'checkdesk_core_site_information_submit';
  }

  if (in_array($form_id, array('user_login', 'user_login_block', 'user_register_form'))) {
    $items = array();
    if (twitter_api_keys()) {
      $items[] = twitter_signin_button();
    }
    $fb_block = module_invoke('fboauth', 'block_view', 'login');
    if (isset($fb_block['content'])) {
      $items[] = $fb_block['content'];
    }
    if (count($items)) {
      $form['social_media_signin'] = array(
        '#type' => 'item',
        '#markup' => theme('item_list', array('items' => $items)),
        '#weight' => '-99',
        '#prefix' => '<div class="social-signin-wrapper">',
        '#suffix' => '</div><div class="or"><span>' . t('or') . '</span></div>',
      );
    }
    unset($form['twitter_signin']);
  }
  if ($form_id == 'user_login' || $form_id == 'user_login_block') {
    $form['#prefix'] = '<div class="user-login-wrapper">';
    $form['#suffix'] = '</div>';
    $form['pass']['#title'] = $form['pass']['#title'] . l(t('(forgot?)'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'))));
    $items = array();
    if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL)) {
      $items[] = l(t('Create new account'), 'user/register', array('attributes' => array('title' => t('Create a new user account.'))));
    }
    $form['links'] = array('#markup' => theme('item_list', array('items' => $items)));
    $form['actions']['submit']['#value'] = t('Sign in');
    unset($form['name']['#description']);
    unset($form['pass']['#description']);
    $form['pass']['#title'] = t('Password');
    // Add forgot link and a wrapper around forgot pass and remember me
    $forgot_pass_link = l(t('Forgot your password?'), 'user/password');
    $form['pass']['#suffix'] = '<div class="user-links"><div class="user-forgot-pass-link">' . $forgot_pass_link . '</div>';
    $form['remember_me']['#suffix'] = '</div>';
    // add a wrapper around new account link
    unset($form['links']);
    $link['attributes']['class'][] = 'register';
    $link['attributes']['title'] = t('Sign Up');
    // Set destination with story collaboration page if login using modal
    if (isset($form_state['ajax'])) {
      $link['query']['destination'] = 'node/' . $form_state['story'] . '/collaboration';
    }
    else {
      $link['query'] = drupal_get_destination();
    }
    $new_account_link = l(t('Sign Up'), 'user/register', $link);
    $form['actions']['submit']['#suffix'] = '<div class="user-new-account-link"><span>' . t('Don\'t have an account? ') . '</span>
    ' . $new_account_link . '</div>';

  }

  if ($form_id == '_checkdesk_core_report_suggest') {
    $form['story']['#prefix'] = '<div class="modal-content-wrapper">';
    $form['story']['#suffix'] = '</div>';
    $form['submit']['#prefix'] = '<div class="modal-footer"><div class="form-actions form-wrapper">
                <a id="close" class="btn" data-dismiss="modal" aria-hidden="true"
                onClick="jQuery(\'#close\').trigger(\'click\');" >' . t('Close') . '</a>';
    $form['submit']['#suffix'] = '</div></div>';
    $form['submit']['#value'] = t('Continue');
    $form['submit']['#attributes']['class'] = array('btn', 'btn-primary');
  }

  if ($form_id == 'flag_confirm') {
    $form['actions']['#prefix'] = '<div class="modal-footer">';
    $form['actions']['#suffix'] = '</div>';

    $form['actions']['submit']['#attributes']['class'] = array('btn', 'btn-primary');
    $form['actions']['cancel']['#attributes']['class'] = array('btn');
    $form['actions']['cancel']['#attributes']['id'] = array('close');
    $form['actions']['cancel']['#weight'] = -1;
  }

  if ($form_id == 'node_delete_confirm') {
    if (isset($form['#node'])) {
      if ($form['#node']->type == 'discussion') {
        $form['description']['#markup'] = t('All related updates will be deleted. Are you sure you want to proceed?');
      }
    }
  }

  if ($form_id == 'user_register_form') {
    $form['#prefix'] = '<div class="user-register-wrapper">';
    $form['#suffix'] = '</div>';
    global $user;
    //Hide administer role so journalist can not give his account a higher role.
    if (!in_array('administrator', $user->roles) && in_array('journalist', $user->roles)) {
      $form['account']['roles']['#options'] = array_diff($form['account']['roles']['#options'], array('administrator'));
    }
    // Hook on submit to remove misleading message.
    // when registeration required admin approval.
    if (variable_get('user_register', USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL) == USER_REGISTER_VISITORS_ADMINISTRATIVE_APPROVAL) {
      $form['#submit'][] = 'checkdesk_core_user_register_form_submit';
    }
    unset($form['account']['name']['#description']);
    unset($form['account']['pass']['#description']);
    $form['account']['mail']['#title'] = t('E-mail address <span>(never shared)</span>');
    $form['account']['mail']['#description'] = t('Check your e-mail to confirm your account');
  }
  if ($form_id == 'user_pass') {
    $form['name']['#attributes']['placeholder'] = t('Username or e-mail address');
  }

  // theme file field
  if ($form_id == 'discussion_node_form') {
    if (isset($form['#node']->language)) {
      $node_language = $form['#node']->language;
      if (isset($form['field_lead_image'][$node_language])) {
        foreach ($form['field_lead_image'][$node_language] as $item => $field_lead_image) {

          if (!is_numeric($item)) {
            continue;
          }
          if (isset($form['field_lead_image'][$node_language][$item])) {
            // Alter the file field element after it has been built.
            $form['field_lead_image'][$node_language][$item]['#after_build'][] = 'checkdesk_core_rename_remove_button';
          }
        }
      }
    }
  }
}

function checkdesk_core_rename_remove_button($element, &$form_state) {
  $element['upload_button']['#value'] = t('Upload');
  $element['remove_button']['#value'] = t('Remove');
  // $element['upload']['#prefix'] = '<label class="cabinet">';
  // $element['upload']['#suffix'] = '</label>';
  return $element;
}

function checkdesk_core_user_register_form_submit(&$form, &$form_state) {
  $message = t('Thank you for applying for an account. Your account is currently pending approval by the site administrator.<br />In the meantime, a welcome message with further instructions has been sent to your e-mail address.');
  $position = array_search($message, $_SESSION['messages']['status']);
  if ($position !== FALSE) {
    unset($_SESSION['messages']['status'][$position]);
  }
  $_SESSION['messages']['status'] = array_values($_SESSION['messages']['status']);

  drupal_set_message(t('Thank you for applying for an account. Your account is currently pending approval by the site administrator.'));
}

/**
 * Implements hook_user_insert().
 */
function checkdesk_core_user_insert(&$edit, $account, $category) {
  module_load_include('lib.php', 'twitter');
  //Add new citizen journalist role to all registered users if they don't have another role
  if ((!isset($edit['roles']) || empty($edit['roles']) || array_keys($edit['roles']) === array(DRUPAL_AUTHENTICATED_RID)) && !isset($account->role)) {
    $user_roles = array_flip(user_roles(TRUE));
    $account->roles = array($user_roles['citizen journalist'] => $user_roles['citizen journalist']) + $edit['roles'];
  }

  // Profile image for Twitter
  if (isset($_SESSION['twitter']) && isset($_SESSION['twitter']['values'])) {
    $key = variable_get('twitter_consumer_key', '');
    $secret = variable_get('twitter_consumer_secret', '');
    $response = $_SESSION['twitter']['values'];

    $twitter = new Twitter($key, $secret, $response['oauth_token'], $response['oauth_token_secret']);
    try {
      $twitter_account = $twitter->users_show($response['screen_name']);
    } catch (TwitterException $e) {
      form_set_error('screen_name', t('Request failed: @message.', array('@message' => $e->getMessage())));
      return;
    }
    $twitter_account->set_auth($response);
    _twitter_signin_get_picture($account, $twitter_account);
  }
}

/**
 * Import twitter profile picture
 **/
function _twitter_signin_get_picture($account, $twitter_account) {
  if ($account->uid) {
    $picture_directory =  file_default_scheme() . '://' . variable_get('user_picture_path', 'pictures');
    if(file_prepare_directory($picture_directory, FILE_CREATE_DIRECTORY)) {
      $source_url = $twitter_account->profile_image_url;
      $picture_path = file_stream_wrapper_uri_normalize($picture_directory . '/twitter-picture-' . $account->uid . '-' . REQUEST_TIME . substr($source_url, -4));
      $picture_file = file_save_data(file_get_contents($source_url), $picture_path, FILE_EXISTS_REPLACE);

      // Check to make sure the picture isn't too large for the site settings.
      $max_dimensions = variable_get('user_picture_dimensions', '85x85');
      file_validate_image_resolution($picture_file, $max_dimensions);
      // Update the user record.
      $picture_file->uid = $account->uid;
      $picture_file = file_save($picture_file);
      file_usage_add($picture_file, 'user', 'user', $account->uid);
      db_update('users')
        ->fields(array(
          'picture' => $picture_file->fid,
        ))
        ->condition('uid', $account->uid)
        ->execute();
    }
  }
}

/**
 * Implements hook_views_query_alter
 * @param type $view
 * @param type $query
 */
function checkdesk_core_views_query_alter(&$view, &$query) {
  // On desk reports, show suggested reports first
  if ($view->name == 'desk_reports') {
    if (isset($_GET['q']) &&  $_GET['q'] == 'node/add/discussion') {
      // show reports that are unassigned to any story
      $join = new views_join();
      $join->construct('field_data_field_stories', 'node', 'nid', 'entity_id', array(), 'LEFT');
      $query->add_relationship('f', $join, 'field_data_field_stories');
      $query->add_where(1,'f.field_stories_target_id', 1, 'IS NULL');
    }
  }

  // Do not display on liveblog stories without updates
  if ($view->name === 'liveblog') {
    $join = new views_join();
    $join->construct('field_data_field_desk', 'node', 'nid', 'field_desk_target_id', array(), 'INNER');
    $query->add_relationship('f', $join, 'field_data_field_desk');
    $query->add_field('node', 'nid', 'nid', array('function' => 'groupby'));
    $query->add_groupby('node.nid');
  }

  if ($view->name == 'checkdesk_search') {
    global $user;
    // Update type condition with right values
    if (isset($_GET['type']) && $_GET['type'] != 'All') {
      foreach($query->where[1]['conditions'] as $k => $v) {
        if (is_string($v['field']) && $v['field'] == 'node.type') {
          $selected_type = array();
          if ($_GET['type'] == 'report') {
            $selected_type = array('media');
          }
          elseif ($_GET['type'] == 'update') {
            $selected_type = array('post');
          }
          elseif ($_GET['type'] == 'story') {
            $selected_type = array('discussion');
          }
          $query->where[1]['conditions'][$k]['value'] = $selected_type;
          break;
        }
      }
    }
    // Add where condition based on flag type for reports.
    if (isset($_GET['type']) && $_GET['type'] == 'report' && isset($_GET['media_flags'])) {
      switch($_GET['media_flags']) {
        case 'flagged_spam':
          $query->add_where(1,'flagging_node.uid', 1, 'IS NOT NULL');
          break;
        case 'flagged_gc':
          $query->add_where(1,'flagging_node_1.uid', 1, 'IS NOT NULL');
        break;
      }
    }
    // Remove status condition if user selected type not reports
    if (isset($_GET['type']) && $_GET['type'] != 'report' && isset($_GET['field_rating_tid']) && is_numeric($_GET['field_rating_tid'])) {
      $conditions = $query->where[1]['conditions'];
      foreach($conditions as $k => $v) {
        if (is_string($v['field']) && $v['field'] == 'field_data_field_rating.field_rating_tid') {
          unset($query->table_queue['field_data_field_rating']);
          unset($query->where[1]['conditions'][$k]);
          break;
        }
      }
    }
    // Add author condition
    if (isset($_GET['author']) && $_GET['author'] != 'All') {
      $query->add_where(1,'users_node.name', $_GET['author'], 'LIKE');
    }
    if (isset($query->having[1]['conditions'][0]['value'][':search_index_keys'])) {
      // Set value equal to 1 to apply OR searching
      // Ticket #3550
      $query->having[1]['conditions'][0]['value'][':search_index_keys'] = 1;
    }
    // Fix helper text in case of search by keyword
    if ($view->current_display == 'attachment_1') {
      if (empty($view->exposed_raw_input['keys'])) {
        $query->having = $query->groupby = array();
      }
      elseif (isset($query->having[1]['conditions'][0]['value'][':search_index_keys1'])) {
        // Set value equal to 1 to apply OR searching
        // Ticket #3550
        $query->having[1]['conditions'][0]['value'][':search_index_keys1'] = 1;
      }
    }
  }
}

/**
 * Implements hook_views_api().
 */
function checkdesk_core_views_api() {
  return array(
    'api' => '3.0',
    'path' => drupal_get_path('module', 'checkdesk_core'),
  );
}

/**
 * Implements hook_views_default_views_alter().
 */
function checkdesk_core_views_default_views_alter(&$data) {
  if (isset($data['admin_views_user'])) {
    $data['admin_views_user']->display['default']->display_options['fields']['views_bulk_operations']['vbo']['operations']['action::user_block_user_action'] = array(
      'selected' => 1,
      'postpone_processing' => 0,
      'skip_confirmation' => 1,
      'override_label' => 1,
      'label' => 'Block user',
    ); /* WAS: '' */
  }

  if (isset($data['admin_views_node'])) {
    $data['admin_views_node']->display['default']->display_options['fields']['views_bulk_operations']['vbo']['operations']['action::checkdesk_core_node_set_language'] = array(
      'selected' => 1,
      'postpone_processing' => 0,
      'skip_confirmation' => 1,
      'override_label' => 0,
      'label' => '',
    ); /* WAS: '' */
    $data['admin_views_node']->display['default']->display_options['fields']['language'] = array(
      'id' => 'language',
      'table' => 'node',
      'field' => 'language',
    );
  }

}

/**
 * Implements hook_email_registration_name().
 */
function checkdesk_core_email_registration_name($edit, $account) {
  // Strip off everything after the @ sign.
  $new_name = preg_replace('/@.*$/', '', $edit['mail']);
  // Clean up the username.
  $new_name = email_registration_cleanup_username($new_name);
  return $new_name;
}

/**
 * Implements hook_wysiwyg_plugin().
 */
function checkdesk_core_wysiwyg_plugin($editor, $version) {
  switch ($editor) {
    case 'ckeditor':
      if ($version >= 4) {
        return array(
          'confighelper' => array(
            'vendor url' => 'http://ckeditor.com/addon/confighelper',
            'path' => drupal_get_path('module', 'checkdesk_core') . '/ckeditor/plugins/confighelper',
            'filename' => 'plugin.js',
            'extensions' => array(
              'confighelper' => t('Config helper'),
            ),
            'load' => TRUE,
          ),
          //
          'mediaoembed' => array(
            'path' => drupal_get_path('module', 'checkdesk_core') . '/ckeditor/plugins/mediaoembed',
            'filename' => 'plugin.js',
            'extensions' => array(
              'mediaoembed' => t('Media Oembed'),
            ),
            'load' => TRUE,
            'buttons' => array(
              'mediaoembed' => t('Media Oembed'),
            ),
          ),

        );
      }
      break;
  }
}

/**
 * Implements hook_wysiwyg_editor_settings_alter().
 *
 * Have the editor use the current language. There are open bugs for WYSIWYG
 * module to do this automatically..
 */
function checkdesk_core_wysiwyg_editor_settings_alter(&$settings, $context) {
  global $language, $base_path;

  $settings['language']       = $language->language;
  $settings['directionality'] = $language->direction == LANGUAGE_RTL ? 'rtl' : 'ltr';

  if ($language->direction == LANGUAGE_RTL && isset($settings['contentsCss'])) {
    foreach ($settings['contentsCss'] as $key => $path) {
      $filepath = substr(preg_replace('/^' . preg_quote($base_path, '/') . '/', '', $path), 0, -4);
      $filepath_rtl = $filepath . '-rtl.css';

      if (file_exists($filepath_rtl)) {
        $settings['contentsCss'][$key] = $base_path . $filepath_rtl;
      }
    }
  }

  // Hide crazy link settings
  $settings['linkShowAdvancedTab'] = FALSE;
  $settings['linkShowTargetTab'] = FALSE;


  if ($context['profile']->editor == 'ckeditor') {
    $settings['forcePasteAsPlainText'] = TRUE;
    $settings['disableNativeSpellChecker'] = FALSE;
    $settings['fillEmptyBlocks'] = FALSE;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for `user_cancel_confirm_form`.
 */
function checkdesk_core_form_user_cancel_confirm_form_alter(&$form, $form_state) {
  $form['#action'] .= '?destination=administer-users';
}

/**
 * Ensures that the IFE module settings are properly installed in the database.
 */
function checkdesk_core_ensure_ife_settings() {

  $form_ids = checkdesk_core_ife_form_ids();

  $defaults = array(
    'field_types' => NULL,
    'status'      => '1',
    'display'     => '-1'
  );

  db_query("TRUNCATE TABLE {ife}");

  foreach ($form_ids as $form_id => $row) {
    $row = array_merge($defaults, $row);

    $row['form_id'] = $form_id;

    db_insert('ife')
      ->fields($row)
      ->execute();
  }
}

/**
 * Forms that will use inline form errors
 */

function checkdesk_core_ife_form_ids() {
  $form_ids = array(
    'article_node_form'     => array(),
    'discussion_node_form'  => array(),
    'forum_node_form'       => array(),
    'media_node_form'       => array(),
    'node_export_node_form' => array(),
    'page_node_form'        => array(),
    'post_node_form'        => array(),
    'flag_confirm'          => array(),

    'comment_form'          => array(),

    'contact_mail_page'     => array(),
    'contact_mail_user'     => array(),

    'user_login'            => array(),
    'user_login_block'      => array(),
    'user_pass'             => array(),
    'user_register_form'    => array(),
    'user_profile_form'     => array(),
  );

  return $form_ids;
}

/**
 * Implements hook_query_TAG_alter() for features_menu_links.
 */
function checkdesk_core_query_features_menu_link_alter($query) {
  $query->fields('menu_links', array('uuid', 'language', 'customized'));
}

/**
 * Implements hook_form_FORM_ID_alter() for `flag_confirm`.
 */
function checkdesk_core_form_flag_confirm_alter(&$form, $form_state, $form_id) {
  $form['field_reason'][LANGUAGE_NONE][0]['value']['#attributes']['placeholder'] = t('Reason');
}

/**
 * Implements hook_form_FORM_ID_alter() for `twitter_oauth_callback_form`.
 */
function checkdesk_core_form_twitter_oauth_callback_form_alter(&$form, $form_state) {
  if (isset($_SESSION['twitter_oauth']['signin'])) {
    //add function to show msg if user still blocked.
    $form['#submit'][] = '_checkdesk_twitter_signin_user_status';
  }
}

function _checkdesk_twitter_signin_user_status(&$form, &$form_state) {
 $account = $form_state['twitter_oauth']['account'];
 if (!$account->status) {
   drupal_set_message(t('The username %name has not been activated or is blocked.', array('%name' => $account->name)), 'error');
 }
}

/**
 * Implements hook_action_info().
 */
function checkdesk_core_action_info() {
  return array(
    'checkdesk_core_node_set_language' => array(
      'type' => 'node',
      'label' => t('Set language'),
      'configurable' => TRUE,
      'behavior' => array('changes_property'),
    ),
  );
}

/**
 * Form function for action `checkdesk_core_node_set_language`.
 */
function checkdesk_core_node_set_language_form($context) {
  $languages = array();
  foreach (language_list() as $langcode => $language) {
    $languages[$langcode] = $language->name;
  }
  $form['language'] = array(
    '#title' => t('Language'),
    '#type' => 'select',
    '#options' => $languages,
    '#default_value' => @$context['language'],
  );
  return $form;
}

/**
 * Submit function for action `checkdesk_core_node_set_language`.
 */
function checkdesk_core_node_set_language_submit($form, $form_state) {
  return array('language' => $form_state['values']['language']);
}

/**
 * Action function for action `checkdesk_core_node_set_language`.
 */
function checkdesk_core_node_set_language($node, $context) {
  $node->language = $context['language'];
  watchdog('action', 'Set node language to %language.', array('%language' => $context['language']));
}

/**
 * API function to get a Facebook locale string given a Drupal language code.
 */
function checkdesk_core_get_facebook_locale($lang_code = '') {
  $languages_map = array(
    'af' => 'af_ZA',
    'ar' => 'ar_AR',
    'ay' => 'ay_BO',
    'az' => 'az_AZ',
    'be' => 'be_BY',
    'bg' => 'bg_BG',
    'bn' => 'bn_IN',
    'bs' => 'bs_BA',
    'ca' => 'ca_ES',
    'cs' => 'cs_CZ',
    'cy' => 'cy_GB',
    'da' => 'da_DK',
    'de' => 'de_DE',
    'el' => 'el_GR',
    'en' => 'en_US',
    'eo' => 'eo_EO',
    'es' => 'es_ES',
    'et' => 'et_EE',
    'eu' => 'eu_ES',
    'fa' => 'fa_IR',
    'fi' => 'fi_FI',
    'fo' => 'fo_FO',
    'fr' => 'fr_FR',
    'ga' => 'ga_IE',
    'gl' => 'gl_ES',
    'gn' => 'gn_PY',
    'gu' => 'gu_IN',
    'he' => 'he_IL',
    'hi' => 'hi_IN',
    'hr' => 'hr_HR',
    'hu' => 'hu_HU',
    'hy' => 'hy_AM',
    'id' => 'id_ID',
    'is' => 'is_IS',
    'it' => 'it_IT',
    'ja' => 'ja_JP',
    'jv' => 'jv_ID',
    'ka' => 'ka_GE',
    'kk' => 'kk_KZ',
    'km' => 'km_KH',
    'kn' => 'kn_IN',
    'ko' => 'ko_KR',
    'ku' => 'ku_TR',
    'la' => 'la_VA',
    'lt' => 'lt_LT',
    'lv' => 'lv_LV',
    'mg' => 'mg_MG',
    'mk' => 'mk_MK',
    'ml' => 'ml_IN',
    'mn' => 'mn_MN',
    'mr' => 'mr_IN',
    'ms' => 'ms_MY',
    'mt' => 'mt_MT',
    'nb' => 'nb_NO',
    'ne' => 'ne_NP',
    'nl' => 'nl_BE',
    'nn' => 'nn_NO',
    'pa' => 'pa_IN',
    'pl' => 'pl_PL',
    'ps' => 'ps_AF',
    'qu' => 'qu_PE',
    'rm' => 'rm_CH',
    'ro' => 'ro_RO',
    'ru' => 'ru_RU',
    'sa' => 'sa_IN',
    'se' => 'se_NO',
    'sk' => 'sk_SK',
    'sl' => 'sl_SI',
    'so' => 'so_SO',
    'sq' => 'sq_AL',
    'sr' => 'sr_RS',
    'sv' => 'sv_SE',
    'sw' => 'sw_KE',
    'ta' => 'ta_IN',
    'te' => 'te_IN',
    'tg' => 'tg_TJ',
    'th' => 'th_TH',
    'tl' => 'tl_ST',
    'tr' => 'tr_TR',
    'tt' => 'tt_RU',
    'uk' => 'uk_UA',
    'ur' => 'ur_PK',
    'uz' => 'uz_UZ',
    'vi' => 'vi_VN',
    'xh' => 'xh_ZA',
    'yi' => 'yi_DE',
    'zh-hans' => 'zh_CN',
    'zh-hant' => 'zh_TW',
    'zu' => 'zu_ZA',
  );

  //Page language
  if (empty($lang_code)) {
    global $language;
    $lang_code = $language->language;
  }

  if (isset($languages_map[$lang_code])) {
    return $languages_map[$lang_code];
  }
  //Not found, return default code
  else{
    return 'en_US';
  }
}

/**
 * Implements hook_filter_info().
 */
function checkdesk_core_filter_info() {
  $filters['filter_checkdesk_markup'] = array(
    'title' => t('Checkdesk markup filter'),
    'description' => t('Replace bad characters, that can mess up Arabic text.'),
    'prepare callback' => '_checkdesk_core_filter_prepare',
    'process callback' => '_checkdesk_core_filter_process',
    'tips callback' => '_checkdesk_core_filter_tips',
    'cache' => FALSE,
  );
  return $filters;
}

/**
 * Checkdesk filter prepare callback.
 */
function _checkdesk_core_filter_prepare($text, $filter) {
  return $text;
}

/**
 * Time filter process callback.
 *
 * Now, in the "process" step, we'll search for problematic characters
 * and replace them by safe ones.
 */
function _checkdesk_core_filter_process($text, $filter) {
  $replacements = array(
    // On Google Chrome, on Windows, '&nbsp;' is replaced by '!' when using font 'Amiri'
    '/&nbsp;/' => ' ',
  );
  $text = preg_replace(array_keys($replacements), array_values($replacements), $text);
  return $text;
}

/**
 * Filter tips callback for Checkdesk filter.
 *
 */
function _checkdesk_core_filter_tips($filter, $format, $long = FALSE) {
}

/**
 * Implements hook_node_insert().
 */
function checkdesk_core_node_insert($node) {
  checkdesk_varnish_pages_to_purge('node', $node, 'insert');
  if ($node->type === 'post') {
    // Update story when a new update is created in this story
    if (isset($node->field_desk[LANGUAGE_NONE][0]['target_id'])) {
      db_update('node')
        ->fields(array(
          'changed' => $node->changed,
        ))
        ->condition('nid', $node->field_desk[LANGUAGE_NONE][0]['target_id'])
        ->execute();
    }
    //link report to created update
    if (isset($node->body)) {
      $story_nid = $node->field_desk[LANGUAGE_NONE][0]['target_id'];
      checkdesk_log_reports_updates('insert', $node->body[LANGUAGE_NONE][0]['value'], $node->nid, $story_nid);
    }
  }
  elseif ($node->type == 'discussion') {
    $path = array(
      'source' => 'node/' . $node->nid . '/collaboration',
      'alias' => 'story/' . $node->nid . '/collaboration',
    );
    path_save($path);
    // Link reports to created story
    if (isset($node->body[LANGUAGE_NONE][0]['value'])) {
      $matches = $reports = array();
      preg_match_all('/\[[^:]+:([0-9]+)\]/u', $node->body[LANGUAGE_NONE][0]['value'], $matches);
      if (count($matches[1])) {
        foreach ($matches[1] as $key => $nid) {
          if (is_numeric($nid) && is_object(node_load($nid))) {
            if (!in_array($nid, $reports)) {
              $reports[] = $nid;
              //Link report to story
              $report = node_load($nid);
              if (!isset($report->field_stories[LANGUAGE_NONE][0]['target_id']) ||
                $report->field_stories[LANGUAGE_NONE][0]['target_id'] != $node->nid
              ) {
                $report->field_stories[LANGUAGE_NONE][0]['target_id'] = $node->nid;
                node_save($report);
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Implements hook_node_update().
 */
function checkdesk_core_node_update($node) {
  checkdesk_varnish_pages_to_purge('node', $node, 'update');
  if ($node->type === 'post' && isset($node->body)) {
    $story_nid = $node->field_desk[LANGUAGE_NONE][0]['target_id'];
    //link report to update
    checkdesk_log_reports_updates('update', $node->body[LANGUAGE_NONE][0]['value'], $node->nid, $story_nid);
  }
}

/**
 * Implements hook_node_delete().
 */
function checkdesk_core_node_delete($node) {
  checkdesk_varnish_pages_to_purge('node', $node, 'delete');
  if ($node->type === 'post') {
    db_delete('checkdesk_reports_updates')
      ->condition('update_nid', $node->nid)
      ->execute();
  }
  elseif ($node->type == 'media') {
    db_delete('checkdesk_reports_updates')
      ->condition('report_nid', $node->nid)
      ->execute();
  }
}

/**
 * Implements hook_preprocess_htmlmail().
 */
function checkdesk_core_preprocess_htmlmail(&$variables) {
  $directions = array('ltr', 'rtl');
  $variables['direction'] = (isset($variables['language']) ? $directions[$variables['language']->direction] : 'ltr');
}

/**
 * Implements hook_variable_info().
 */
function checkdesk_core_variable_info($options) {
  $variable['checkdesk_site_owner'] = array(
    'type' => 'string',
    'title' => t('Checkdesk site owner', array(), $options),
    'description' => t('Checkdesk site owner'),
    'default' => '',
    'localize' => TRUE,
  );
  return $variable;
}

/**
 * Function to generate custom format interval
 * issue #1930
 */
function checkdesk_core_custom_format_interval($timestamp) {
  $interval = time() - $timestamp;
  $y = 31536000;
  $m = 2592000;
  $d = 86400;
  //interval over 1 year
  if ($interval > $y) {
    return format_date($timestamp, 'custom', t('j M Y'));
  }
  //interval between 3 months and year
  if ($interval > (3*$m) && $interval <= $y ) {
    return format_date($timestamp, 'custom', t('M j'));
  }
  //less than 5 sec (as soos as item is posted)
  if ($interval < 5) {
    return t('now');
  }
  //interval beteen one day and 3 months.
  if ($interval >= $d && $interval <= (3*$m)) {
    $count = floor($interval / $d);
    return t('@countd', array('@count' => $count));
  }
  //interval less than one day
  $units = array(
    'h' => 3600,
    'm' => 60,
    's' => 1,
  );
  $output = '';
  foreach ($units as $key => $value) {
    if ($interval >= $value) {
      $count = floor($interval / $value);
      $output = t("@count$key", array('@count' => $count));
      break;
    }
  }
  return $output;
}

/**
 * Generate a title to a node based on its body.
 * Used by auto_nodetitle to set titles of updates.
 */
function _checkdesk_core_auto_title($node) {
  $replacements = array('/\[[^]]+\]/' => '', '/&nbsp;/' => ' '); // &nbsp; would be decoded as a non-UTF-8 char
  $body = html_entity_decode(strip_tags(preg_replace(array_keys($replacements), array_values($replacements), @$node->body[LANGUAGE_NONE][0]['value'])));
  if (empty($body)) {
    return t('Update');
  }
  $title = (mb_strlen($body) > 25) ? mb_substr($body, 0, 22) . '...' : $body;
  return $title;
}

/**
 * Ajax command to call Drupal.attachBehaviors passing $selector as context
 */
function checkdesk_core_ajax_command_attach_behaviors($selector = NULL) {
  $command = array(
    'command' => 'attachBehaviors',
    'selector' => $selector,
  );
 return $command;
}

/**
 * Implements hook_flag_javascript_info_alter().
 */
function checkdesk_core_flag_javascript_info_alter(&$info) {
  if ($info['flagName'] != 'follow_story') {
    $nid = $info['contentId'];
    $node = node_load($nid);
    $element = node_view($node);
    $element['comments'] = comment_node_page_additions($node);
    $output = drupal_render($element);

    $js = drupal_add_js(NULL, NULL);
    $settings = '';
    if (isset($js['settings'])) {
      $settings = '<script type="text/javascript">jQuery.extend(Drupal.settings, ' .
        drupal_json_encode(call_user_func_array('array_merge_recursive', $js['settings']['data'])) .
        ');</script>';
    }
    // Add the settings to the form
    $output .= $settings;

    $commands = array();
    $commands[] = ajax_command_invoke('.default-view-node-' . $nid, 'replaceWith', array($output));
    $commands[] = checkdesk_core_ajax_command_attach_behaviors('.node-' . $nid);

    $info['commands'] = $commands;
  }
}

/**
 * Implements hook_preprocess() for user_alert theme.
 */
function checkdesk_core_preprocess_user_alert(&$vars) {
  $vars['body'] = $vars['node']->body[LANGUAGE_NONE][0]['value'];
  $vars['is_closeable'] = TRUE;
}

/**
 * Helper function to check whether a report was published on an update before
 */
function checkdesk_core_report_published_on_update($nid) {
  if (is_numeric($nid)) {
    $count = db_query(
      'SELECT COUNT(*) FROM {checkdesk_reports_updates} WHERE report_nid = :nid', array(':nid' => $nid)
    )->fetchField();
    return $count ? $count : FALSE;
  }
  return FALSE;
}

/**
 * Implements hook_clientside_validation_form_alter().
 */
function checkdesk_core_clientside_validation_form_alter(&$form, &$form_state, &$js_rules) {
  if ($form['#form_id'] == 'user_register_form') {

    // Passwords must match
    $value = array(
      'element_name' => $form['account']['pass']['pass1']['#name'],
      'name' => $form['account']['pass']['pass1']['#title'],
    );
    _clientside_validation_set_equal($form['account']['pass']['pass2']['#name'], $form['account']['pass']['pass2']['#title'], $value, $js_rules, t('mismatch'));

    // Password min length
    $min = variable_get('logintoboggan_minimum_password_length', 0);
    if ($min) {
      _clientside_validation_set_minmaxlength($form['account']['pass']['pass1']['#name'], $form['account']['pass']['pass1']['#title'], $min, 1, $js_rules, t('too short'));
      _clientside_validation_set_minmaxlength($form['account']['pass']['pass2']['#name'], $form['account']['pass']['pass2']['#title'], $min, 1, $js_rules, t('too short'));
    }

    // E-mail must be valid
    _clientside_validation_set_email($form['account']['mail']['#name'], $form['account']['mail']['#title'], $js_rules, t('invalid'));

    // Captcha
    //_clientside_validation_set_captcha('recaptcha_response_field', t('Captcha'), $form['captcha']['#captcha_validate'], $js_rules, t('wrong'));
    //_clientside_validation_set_required('recaptcha_response_field', t('Captcha'), TRUE, $js_rules, t('required'));

    // Customize error messages to shorter strings
    foreach (array('name', 'mail', 'pass[pass1]', 'pass[pass2]') as $field) {
      $js_rules[$field]['messages']['required'] = t('required');
    }

    // Username must be unique
    _checkdesk_validation_set_unique_field('users', $form['account']['name']['#name'], $form['account']['name']['#title'], $js_rules, t('unavailable'));

    // E-mail must be unique
    _checkdesk_validation_set_unique_field('users', $form['account']['mail']['#name'], $form['account']['mail']['#title'], $js_rules, t('unavailable'));

  }
}

/**
 * Set validation rule for unique fields.
 */
function _checkdesk_validation_set_unique_field($table, $name, $title, &$js_rules, $message = '') {
  $title = _clientside_validation_set_title($title);
  $js_rules[$name]['unique'] = $table;
  $variables = array(
    'message' => empty($message) ? 'The value in !title is already taken.' : $message,
    'placeholders' => empty($message) ? array('!title' => $title) : array(),
    'error_type' => 'unique',
    'element_name' => $name
  );
  $js_rules[$name]['messages']['unique'] = theme('clientside_error', $variables);
}

/**
 * Menu callback function for checkdesk_validation/unique_field.
 */
function _checkdesk_validation_ajax_unique_field() {
  $value = filter_xss($_POST['value']);
  $table = filter_xss($_POST['table']);
  $field = filter_xss($_POST['field']);
  $exists = db_select($table)
            ->fields($table, array($field))
            ->condition($field, $value)
            ->execute()
            ->rowCount();
  return drupal_json_output(array('result' => !(bool)$exists));
}

function _checkdesk_core_comment_form_validate($form, &$form_state) {

  // Get tid from name
  if (isset($form_state['values']['field_rating'])) {
    $tids = array_keys(taxonomy_get_term_by_name($form_state['values']['field_rating'][LANGUAGE_NONE][0]['tid']));
    $form_state['values']['field_rating'][LANGUAGE_NONE][0]['tid'] = $tids[0];
  }

}

/**
 * Submit comment via ajax.
 */
function _checkdesk_comment_form_submit($form, &$form_state) {
  global $user;

  drupal_get_messages();

  $nid = $form['#node']->nid;
  $node = node_load($nid);

  $commands = array();
  // Change report status
  if (in_array('journalist', $user->roles) || in_array('administrator', $user->roles)) {
    $node->field_rating[LANGUAGE_NONE][0]['tid'] = $form_state['values']['field_rating'][LANGUAGE_NONE][0]['tid'];
    node_save($node);
    // Update report status on report display
    $report_status = _checkdesk_report_status($node);
    $commands[] = ajax_command_replace('.media-status-report-' . $node->nid, $report_status['status']);
  }
  //$node_view = node_view($node);
  // $node_view['comments'] = comment_node_page_additions($node);
  //$output = drupal_render($node_view);
  //TODO use theme function instead of writing HTML
  $output = _checkdesk_render_footnotes($node);
  $commands[] = ajax_command_invoke(NULL, 'footnoteCallback', array($nid, $output));

  return array('#type' => 'ajax', '#commands' => $commands);
}

/**
 * Implements hook_search_preprocess().
 */
function checkdesk_core_search_preprocess($text) {
  // Reject overly long 2 byte sequences, as well as characters above U+10000
  $text = preg_replace('/[\x00-\x08\x10\x0B\x0C\x0E-\x19\x7F]'.
    '|[\x00-\x7F][\x80-\xBF]+'.
    '|([\xC0\xC1]|[\xF0-\xFF])[\x80-\xBF]*'.
    '|[\xC2-\xDF]((?![\x80-\xBF])|[\x80-\xBF]{2,})'.
    '|[\xE0-\xEF](([\x80-\xBF](?![\x80-\xBF]))|(?![\x80-\xBF]{2})|[\x80-\xBF]{3,})/S',
    '', $text);

  // Reject overly long 3 byte sequences and UTF-16 surrogates
  $text = preg_replace('/\xE0[\x80-\x9F][\x80-\xBF]'.
    '|\xED[\xA0-\xBF][\x80-\xBF]/S', '', $text);

  return $text;
}

/**
 * Implements hook_system_info_alter().
 */
function checkdesk_core_system_info_alter(&$info, $file, $type) {
  //prevent overlay module from being enabled Issue #2039.
  if ($file->name == 'overlay' && $type == 'module') {
    //add dependencies to non exist module.
    $info['dependencies'] = array('checkdesk_not_exist');
  }
}

/**
 * Utility function to set $alpha and $omega for layouts
 */
function checkdesk_core_direction_settings() {
  // set $alpha and $omega for language directions
  global $language;
  $layout = array();
  if ($language->direction == LANGUAGE_RTL) {
    $layout['alpha'] = 'right';
    $layout['omega'] = 'left';
  } else {
    $layout['alpha'] = 'left';
    $layout['omega'] = 'right';
  }

  return $layout;
}

/*
 * Implements hook_core_pathauto_alias_alter().
 */
function checkdesk_core_pathauto_alias_alter(&$alias, array &$context) {
  // Force all aliases to be saved as language neutral.
  $context['language'] = LANGUAGE_NONE;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function checkdesk_core_form_media_node_form_alter(&$form, &$form_state) {
  // Adjust edit node form
  $form['field_link'][LANGUAGE_NONE][0]['#title'] = t('URL');
  $form['field_tags'][LANGUAGE_NONE]['#attributes']['placeholder'] = t('Add tags');

  if (isset($form['nid']['#value'])) {
    $node = $form['#node'];
    drupal_set_title(t('Edit @type <em>@title</em>', array('@type' => t('Report'), '@title' => $node->title)), PASS_THROUGH);
  }
  //set default story if exist.
  elseif (isset($_GET['ref_nid'])) {
    $form['field_stories'][LANGUAGE_NONE]['#default_value'] = array($_GET['ref_nid']);
  }

  $options = array('_none' => t('- None -')) + _checkdesk_get_stories_by_activity();
  $form['field_stories'][LANGUAGE_NONE]['#options'] = $options;
  // Handle HTML entities
  foreach ($form['field_stories'][LANGUAGE_NONE]['#options'] as &$option) {
    $option = decode_entities($option);
  }
  // Redirect user to collaboration page.
  $form['actions']['submit']['#submit'][] = '_redirect_report';
}

/**
 * Redirect user to collaboration page.
 */
function _redirect_report($form, &$form_state) {
  $values = $form_state['values'];
  if (!empty($values['field_stories'][LANGUAGE_NONE][0]['target_id'])) {
    $form_state['redirect'] = 'node/' . $values['field_stories'][LANGUAGE_NONE][0]['target_id'] . '/collaboration';
  }
}

/**
 * Implements hook_comment_delete().
 */
function checkdesk_core_comment_delete($comment) {
  // Delete messages from deleted comments.
  $query = db_select('heartbeat_activity', 'ha');
  $query->addField('ha', 'uaid');
  $query->condition('cid', $comment->cid);
  $query->condition('nid', $comment->nid);
  foreach ($query->execute() as $row_object) {
    $uaids[] = $row_object->uaid;
  }
  if (!empty($uaids)) {
    heartbeat_activity_delete($uaids);
  }
}

/**
 * Implements hook_flag_flag().
 */
function checkdesk_core_flag_flag($flag, $entity_id, $account, $flagging) {
  if ($flag->name == 'graphic_journalist') {
    $node = node_load($entity_id);
    checkdesk_varnish_pages_to_purge($flag->entity_type, $node, 'update');
  }
}

/**
 * Implements hook_flag_unflag().
 */
function checkdesk_core_flag_unflag($flag, $entity_id, $account, $flagging) {
  if ($flag->name == 'graphic_journalist') {
    $node = node_load($entity_id);
    checkdesk_varnish_pages_to_purge($flag->entity_type, $node, 'update');
  }
}

/**
 * Implements hook_cron().
 */
/** Disable it for now
function checkdesk_core_cron() {
  //Remove active story (older than 2 weeks)
  $time = strtotime("-2 week");
  db_query('
     UPDATE {field_data_field_active_story}
     SET field_active_story_value = :inactive_story
     WHERE entity_id IN (SELECT nid FROM {node} WHERE type = :type AND changed < :time)
  ', array(
      ':inactive_story' => 0,
      ':type' => 'discussion',
      ':time' => $time,
    ));
}
 */
/**
 * Implements hook_cron_queue_info().
 */
function checkdesk_core_cron_queue_info() {
  $queues['checkdesk_varnish'] = array(
    'worker callback' => '_checkdesk_purge_varnish',
    'skip on cron' => TRUE,
  );
  return $queues;
}

/**
 * Implements hook_cron_queue_info_alter().
 */
function checkdesk_core_cron_queue_info_alter(&$queues) {
  $queues['rules_scheduler_tasks']['skip on cron'] = TRUE;
}

/**
 * Implements hook_cron().
 */
function _checkdesk_purge_varnish($paths) {
  if (module_exists('varnish')) {
    //any action reflect on frontpage
    if (count($paths)) {
      $languages = language_list();
      $hostnames = variable_get('hostnames', array());
      //define purge_all variable as no need to generate  URLs if purge all exist.
      $purge_all = FALSE;
      if (in_array('varnish_purge_all_pages', $paths)) {
        $purge_all = TRUE;
      }
      foreach ($hostnames as $hostname) {
        $urls = array();
        if (!$purge_all) {
          foreach ($paths as $path) {
            foreach($languages as $key => $value) {
              $urls[] = url($path, array(
                'language' => $languages[$key],
              ));
            }
          }
          //add front page
          $urls[] = url('<front>', array());
        }
        else {
          $urls = array(base_path());
        }
        //log urls and host name
        $message = t('Purge was executed on !host for the next URLs: !urls', array('!host' => $hostname, '!urls' => theme('item_list', array('items' => $urls))));
        //watchdog('checkdesk-varnish', $message, array(), WATCHDOG_DEBUG);
        checkdesk_varnish_expire_cache($urls, $hostname);
        //adding sleep for 2 seconds
        sleep(2);
      }
    }
  }
}

/**
 * Clone varnish_expire_cache().
 */
function checkdesk_varnish_expire_cache($paths, $host) {
  $purge = implode('$|^', $paths);
  $purge = '^'. $purge .'$';
  varnish_purge($host, $purge);
}

/**
 *
 */
function checkdesk_log_reports_updates($op, $text, $update_nid, $story_nid) {
  //link report to created update
  if ($op == 'update') {
    db_delete('checkdesk_reports_updates')
      ->condition('update_nid', $update_nid)
      ->execute();
  }
  $matches = $reports = array();
  preg_match_all('/\[[^:]+:([0-9]+)\]/u', $text, $matches);
  if (count($matches[1])) {
    foreach ($matches[1] as $key => $nid) {
      if (is_numeric($nid) && is_object(node_load($nid))) {
        if(!in_array($nid, $reports)) {
          $reports[] = $nid;
          db_insert('checkdesk_reports_updates')->fields(array('report_nid' => $nid, 'update_nid'  => $update_nid))->execute();
          //Link report to story
          $report = node_load($nid);
          if (!isset($report->field_stories[LANGUAGE_NONE][0]['target_id']) || 
            $report->field_stories[LANGUAGE_NONE][0]['target_id'] != $story_nid) {
              $report->field_stories[LANGUAGE_NONE][0]['target_id'] = $story_nid;
              node_save($report);
            }
        }
      }
    }
  }
}

/**
 *
 */
function checkdesk_core_site_information_submit(&$form, &$form_state) {
  $paths = array();
  //add static keyword to identify purged all caches
  $paths[] = 'varnish_purge_all_pages';
  $queue = DrupalQueue::get('checkdesk_varnish');
  $queue->createItem($paths);
}

/**
 *
 */
function checkdesk_varnish_pages_to_purge($type, $object, $op) {
  if (!module_exists('varnish')) {
    return;
  }
  $paths = array();
  if ($type == 'node') {
    //check insert
    //only published content that will need to purge from varnish cache
    //no need to check media content as it does not include on any update yet.
    if ($op == 'insert' && $object->status != 0) {
      switch($object->type) {
      case 'discussion':
        $paths[] = 'node/'. $object->nid;
        break;
      case 'post':
        //get story nid
        $paths[] = 'node/'. $object->field_desk[LANGUAGE_NONE][0]['target_id'];
        break;
      }
    }
    //case update or delete
    if ($op == 'update' || $op == 'delete') {
      switch($object->type) {
      case 'discussion':
        $paths[] = 'node/'. $object->nid;
        break;
      case 'post':
        //get story nid
        $paths[] = 'node/'. $object->field_desk[LANGUAGE_NONE][0]['target_id'];
        break;
      case 'media':
        //get all stories that hold updates contain this report
        $query = db_select('checkdesk_reports_updates', 'ru');
        $query->join('field_data_field_desk', 'fd', 'ru.update_nid = fd.entity_id');
        $query->condition('ru.report_nid', $object->nid);
        $query->addExpression("CONCAT('node/', fd.field_desk_target_id)", 'story_url');
        $paths = $query->execute()->fetchCol();
        $paths[] = 'node/'. $object->nid;
        break;
      }
    }
  }
  if (count($paths)) {
    //store pages on Queue to purge them on cron task.
    $queue = DrupalQueue::get('checkdesk_varnish');
    $queue->createItem($paths);
  }
}

/**
 * Render heartbeat activity on story collaboration page.
 *
 * @param onject $row
 *  heartbeat activity object
 *
 * @return HTML for target node (update/report)
 */
function checkdesk_story_collaborate_render_object($row) {
  $node = node_load($row->heartbeat_activity_nid);
  $node->heartbeat_row = $row;
  if ($row->heartbeat_activity_message_id == 'checkdesk_follow_story') {
    $node_view = node_view($node);
  }
  else {
    $node_view = node_view($node, 'checkdesk_collaborate');
  }
  $output = render($node_view);
  return $output;
}

/**
 * Add updates/collaboration tab to story node.
 *
 * @param int $nid
 *  story nid
 */
function _checkdesk_story_tabs($nid) {
  $items = array();
  $items[] = array(
    'data' => l(t('Updates'), 'node/'. $nid),
    'class' => array('story-tab-updates'),
  );
  $items[] = array(
    'data' => l(t('Collaboration'), 'node/'. $nid .'/collaboration'),
    'class' => array('story-tab-collaboration'),
  );
  return theme('item_list', array('items' => $items, 'title' => '', 'attributes' => array('class' => 'story-tabs')));
}

/**
 * Return story nid to filler incomming rports view.
 */
function checkdesk_core__get_desk_reports_args() {
  $story_nid = 'all';
  // Show incoming reports on story page or update form.
  if (is_numeric(arg(1))) {
    $nid = arg(1);
    $node = node_load($nid);
    if ($node->type == 'discussion') {
      $story_nid = $nid;
    }
    else if ($node->type == 'post' && isset($node->field_desk[LANGUAGE_NONE][0]['target_id'])) {
      $story_nid = $node->field_desk[LANGUAGE_NONE][0]['target_id'];
    }
  }
  elseif (isset($_GET['story']) && is_numeric($_GET['story'])) {
    $story_nid = $_GET['story'];
  }
  return $story_nid;
}

/**
 * Function to delete follow story activity (unfollow action)
 *
 * @param int $target_nid
 *  story nid
 * @param int $uid
 *  user uid
 */
function _checkdesk_delete_follow_story_activity($target_nid, $uid = 0) {
  if (!$uid) {
    global $user;
    $uid = $user->uid;
  }
  $uaids = db_query('
  SELECT uaid
  FROM {heartbeat_activity}
  WHERE message_id = :message_id AND nid_target = :target_nid AND uid = :uid
  ', array(':message_id' => 'checkdesk_follow_story', ':target_nid' => $target_nid, ':uid' => $uid))->fetchCol();

  if (count($uaids)) {
    heartbeat_activity_delete($uaids);
  }
}

/**
 * implements of hook_rules_action_info().
 */
function checkdesk_core_rules_action_info() {
  $actions = array(
    'checkdesk_core_actions_set_followers' => array(
      'label' => t('Set current user as follower'),
      'group' => t('Node'),
      'parameter' => array(
        'node' => array(
          'type' => 'node',
          'label' => t('Node to follow.'),
        ),
      ),
    ),
  );
  return $actions;
}

/**
 * Set Action for checkdesk_core_actions_set_followers.
 */
function checkdesk_core_actions_set_followers($node) {
  global $user;
  // Check if current user already follow this node.
  $flag = flag_get_flag('follow_story');
  if ($flag && !$flag->is_flagged($node->nid, $user->uid)) {
    $flag->skip_heartbeat_log = TRUE;
    $flag->flag('flag', $node->nid, $user);
    //watchdog('User follow story', t('@user follow this story @title', array('@user' => $user->name, '@title' => $node->title)));
  }
}

function _set_user_avatar_bg($account, $classes = array()) {

  if (isset($account->picture->uri)) {
    $avatar_uri = $account->picture->uri;
  }
  else {
    $avatar_uri = variable_get('user_picture_default', '') ? variable_get('user_picture_default', '') : '';
  }

  $avatar = '';
  if ($avatar_uri) {
    $derivative_uri = image_style_path('activity_avatar', $avatar_uri);
    $success = file_exists($derivative_uri) || image_style_create_derivative('activity_avatar', $avatar_uri, $derivative_uri);

    $new_image_url = file_create_url($derivative_uri);
    $avatar = l('', 'user/' . $account->uid, array('html' => TRUE,
      'attributes' => array(
        'class' => is_array($classes) ? $classes : array(),
        'title' => $account->name,
        'style' => 'background-image: url("' . $new_image_url . '")'
      )));
  }
  return $avatar;
}

/**
 * Render footnote HTML for footnote ajax submit
 * @param object $node
 * @return HTML
 */
function _checkdesk_render_footnotes($node) {
  $node_view = node_view($node);
  $view = views_get_view('activity_report');
  $view->set_arguments(array($node->nid));
  $view->get_total_rows = TRUE;
  $view_output = $view->preview('block');
  $total_rows = $view->total_rows;
  $view->destroy();
  if ($total_rows) {
    $media_activity_report_count = $total_rows;
    $media_activity_report = $view_output;
  }
  $html = '<div id="report-activity-node-' . $node->nid . '" class="item-nested-content-wrapper open">';
  $html .= '<div class="activity-item-controls item-controls">';
  $html .= '    <div class="meta">';
  $html .= $media_activity_report_count . ' '. t('verification footnotes');
  $html .= '</div>';
  $html .= '<div class="actions" role="toolbar">';
  $html .= render($node_view['links']);
  $html .= '</div>';
  $html .= '</div>';
  $html .= ' <div class="activity nested item-nested-content open" style="display: block;">';
  $html .= $media_activity_report;
  $html .= '  </div>';
  $html .= '  </div>';
  return $html;
}

/**
 * @param array $options
 *   An associative array with the following keys
 *   theme : bool(default TRUE) set TRUE to return active stories as HTML list F
 *           FALSE to return associative array nid => title
 *   extra_nids : array with nids to be added to active stories.
 *   time : the base item for active stories
 *
 * @return string/array
 */
function _checkdesk_active_story($options = array()) {
  $time =  isset($options['time']) ? $options['time'] : strtotime("-". variable_get('checkdesk_active_story_time', '3 day'));
  if (!isset($options['extra_nids'])) {
    $options['extra_nids'] = array(-1);
  }
  if (!isset($options['theme'])) {
    $options['theme'] = TRUE;
  }
  $result = db_query('
    (
      SELECT nid, title
      FROM {node} n
      /*LEFT JOIN {field_data_field_active_story} acs ON acs.entity_id = n.nid*/
      WHERE n.type = :type AND ((n.changed > :time /*AND acs.field_active_story_value != :inactive*/) OR n.nid IN (:extra_nids))
    )
      UNION
    (
      SELECT DISTINCT nid_target, n.title
      FROM {heartbeat_activity} ha
      INNER JOIN {node} n on ha.nid_target = n.nid AND n.type = :type
      /*LEFT JOIN {field_data_field_active_story} acs ON acs.entity_id = n.nid*/
      WHERE message_id IN (:message_id ) AND timestamp > :time /*AND acs.field_active_story_value IS NULL*/
    )
      ORDER BY nid DESC
    ',
    array(
      ':type' => 'discussion',
      ':time' => $time,
      ':inactive' => 0,
      ':message_id' => array('checkdesk_report_suggested_to_story', 'checkdesk_report_published_in_update'),
      ':extra_nids' => $options['extra_nids']
    )
  )->fetchAllKeyed(0);
  if ($options['theme']) {
    $items = array();
    foreach ($result as $k => $v) {
      $items[] = l($v, 'node/'. $k);
    }
    return theme('item_list', array('items' => $items, 'title' => '', 'attributes' => array('class' => 'checkdesk-active-story')));
  }
  return $result;
}

/**
 * @return array
 *  List of stories sorted by activity.
 */
function _checkdesk_get_stories_by_activity() {
  global $language;
  $result = db_query('
    SELECT n.nid, n.title
    FROM heartbeat_activity ha
    INNER JOIN node n ON n.nid = ha.nid_target AND n.type = :type AND n.language = :language
    ORDER BY ha.timestamp DESC 
    ', array(':type' => 'discussion', ':language' => $language->language))->fetchAllKeyed(0);
  return $result;
}

/**
 * Delete update activity when user change story for existing one
 */
function _checkdesk_delete_heartbeat_activity ($node) {
  if ($node->type == 'post') {
    $story_nid = $node->field_desk[LANGUAGE_NONE][0]['target_id'];
  }
  else {
    $story_nid = $node->field_stories[LANGUAGE_NONE][0]['target_id'];
  }
  $uaids = db_query('
            SELECT uaid FROM {heartbeat_activity} WHERE nid = :nid AND nid_target = :nid_target
          ', array(':nid' => $node->nid, ':nid_target' => $story_nid))->fetchCol();
  if (!empty($uaids)) {
    heartbeat_activity_delete($uaids);
  }
}

/**
 *
 */
function _checkdesk_story_links($nid) {
  global $user;
  $output = '';
  if ($user->uid) {
    $items = array();

    $items[] = array(
      'data' => l(t('Add a report'), 'node/add/media', array('query' => array('ref_nid' => $nid, drupal_get_destination()))),
      'class' => array('submit-report'),
    );

    if (user_access('create post content')) {
      $items[] = array(
        'data' => l(t('Compose update'), 'node/add/post', array('query' => array('story' => $nid))),
        'class' => array('compose-update'),
      );
    }
    $output .= theme('item_list', array('items' => $items, 'title' => '', 'attributes' => array('class' => 'story-collaborate-links')));
  }

  // Add tooltip for add a report.
  if (isset($_SESSION['report_tooltip'])) {
    $tour = array(
      'title' => 'Submit Report',
      'content' => 'Quickly add newsworthy links from social media. Then you can fact-check and publish them.',
    );
    $tooltip = '<span class="popover tour-tour fade right in collaboration-report-tooltip">';
    $tooltip .= '  <div class="popover-arrow"></div>';
    $tooltip .= '  <div class="popover-close" data-role="end" onclick="jQuery(this).parent().hide();"><span>[X]</span></div>';
    $tooltip .= '  <h3><span class="popover-title">' . t($tour['title']) . '</span></h3>';
    $tooltip .= '  <div class="popover-content">' . t($tour['content']) . '</div>';
    $tooltip .= '</span>';
    $output .= $tooltip;
    unset($_SESSION['report_tooltip']);
  }

  return $output;
}

/**
 * List story collaborators
 *  @param story_nid
 *
 */
function _checkdesk_story_get_collaborators($nid, $options = array()) {
  if (!isset($options['extra_users'])) {
    $options['extra_users'] = TRUE;
  }
  if (!isset($options['show_avatars'])) {
    $options['show_avatars'] = TRUE;
  }
  $output = '';
  //ToDO check node type
  $users = db_query('
    SELECT ha.uid, u.name, f.fid, f.uri
    FROM {heartbeat_activity} ha
    INNER JOIN {users} u ON ha.uid = u.uid
    LEFT JOIN {file_managed} f ON u.picture = f.fid
    WHERE nid_target = :nid AND message_id != :message_id
    GROUP BY ha.uid
    ORDER BY COUNT(ha.uid) DESC
    ', array(':nid' => $nid, ':message_id' => 'checkdesk_follow_story'))->fetchAll();
  $total_users = count($users);
  if ($total_users) {
    $extra_users = 0;
    $title = format_plural($total_users, '1 collaborator', '@count collaborators');
    if ($options['extra_users']) {
      $num_to_show = variable_get('collaborators_display_count', 3);
      $extra_users = $total_users > $num_to_show ? $total_users - $num_to_show : 0;
    }
    $uitems = $pitems = array();
    if ($extra_users) {
      $users = array_slice($users, 0, $num_to_show);
    }
    foreach ($users as $user) {
      // split user name into first name and last
      $fullname = explode(' ', $user->name);
      $fname = array_shift($fullname);
      $uitems[] = l($fname, 'user/'. $user->uid);
      if ($options['show_avatars']) {
        $avatar = _set_user_avatar_bg(user_load($user->uid));
        if ($avatar) {
          $pitems[] = $avatar;
        }
      }
    }


    $output .= '<div class="story-collaborators-wrapper"><div class="story-collaborators"><span class="sc-users"><h3>' . $title . '</h3>' . implode(', ', $uitems);
    if ($extra_users) {
      $output .= ' <span class="sc-extra-users">+ '. $extra_users .'</span>';
    }
    $output .= '</span>'; // closing sc-users
    if ($options['show_avatars']) {
      $output .= '<span class="sc-avatars">';
      foreach ($pitems as $pitem) {
        $output .= $pitem;
      }
      $output .= '</span>';
    }
    $output .= '</div></div>';
  }

  return $output;
}

/**
 * Get status of a report
 */
function _checkdesk_report_status($report) {
  global $language;
  $report_status = array();
  $icon_class = '';
  $term = isset($report->field_rating[LANGUAGE_NONE][0]['taxonomy_term']) ?
      $report->field_rating[LANGUAGE_NONE][0]['taxonomy_term'] :
      taxonomy_term_load($report->field_rating[LANGUAGE_NONE][0]['tid']);
  $status_name = $term->name;

  $status_class = empty($status_name) ? '' : strtolower(str_replace(' ', '-', $status_name));;
  if ($status_name == 'Verified') {
    $icon_class = 'icon-check-circle';
  }
  elseif ($status_name == 'In Progress') {
    $icon_class = 'icon-random';
  }
  elseif ($status_name == 'Undetermined') {
    $icon_class = 'icon-question-circle';
  }
  elseif ($status_name == 'False') {
    $icon_class = 'icon-times-circle';
  }
  $icon = empty($icon_class) ? '' : '<span class="'. $icon_class .'"></span> ';
  $report_status['status'] = $icon . '<span class="status-name ' . $status_class . '">' . t($status_name) . '</span>';
  if($status_name != 'In Progress') {
    $partner = i18n_variable_get('checkdesk_site_owner', $language->language) ?
      i18n_variable_get('checkdesk_site_owner', $language->language) : i18n_variable_get('checkdesk_site_owner', 'en');
    $status_by = t('by <span class="checkdesk-status-partner">@partner</span>',
      array('@partner' => $partner));
  }
  // display status with an icon and "x by partner"
  if(isset($status_name) && isset($icon) && isset($status_by)) {
    $report_status['status'] = $icon . '<span class="status-name ' . $status_class . '">' . t($status_name) . '</span>&nbsp;<span class="status-by">' . $status_by . '</span>';
  } else { // display status with an icon only
    $report_status['status'] = $icon . '<span class="status-name ' . $status_class . '">' . t($status_name) . '</span>';
  }
  $report_status['status'] = '<span class="media-status-report-'. $report->nid .'">' . $report_status['status'] .'</span>';
  return $report_status;
}

/**
 * Add header for search page
 * i.e - sort filter + basic filters for each content type.
 */
function _checkdesk_search_header() {
  global $user;
  $links = array();
  $path = '';
  $selected = 'DESC';
  if (isset($_GET['sort_bef_combine'])) {
    $selected = ($_GET['sort_bef_combine'] == 'created ASC') ? 'ASC' : 'DESC';
  }

  $links[] = l(t('Newest'), bef_replace_query_string_arg('sort_bef_combine', 'created DESC', FALSE, FALSE, $path),
    array('attributes' => array('class' => ($selected == 'DESC') ? 'selected' : '')));
  $links[] = l(t('Oldest'), bef_replace_query_string_arg('sort_bef_combine', 'created ASC', FALSE, FALSE, $path),
    array('attributes' => array('class' => ($selected == 'ASC') ? 'selected' : '')));

  if (isset($_GET['type'])) {
    switch ($_GET['type']) {
      case 'report':
        // Add filters for media only
        $selected = 'All';
        if (isset($_GET['field_rating_tid'])) {
          if($_GET['field_rating_tid'] == 1) {
            $selected = 'verified';
          }
          elseif ($_GET['field_rating_tid'] == 2) {
            $selected = 'in-progress';
          }
        }
        $links[] = l(t('Verified'), bef_replace_query_string_arg('field_rating_tid', 1, FALSE, FALSE, $path),
          array('attributes' => array('class' => ($selected == 'verified') ? 'selected' : '')));
        $links[] = l(t('In Progress'), bef_replace_query_string_arg('field_rating_tid', 2, FALSE, FALSE, $path),
          array('attributes' => array('class' => ($selected == 'in-progress') ? 'selected' : '')));

        $selected = 'All';
        if (isset($_GET['media_flags']) && $_GET['media_flags'] == 'flagged_spam') {
          $selected = 'spam';
        }
        $links[] = l(t('Spam'), bef_replace_query_string_arg('media_flags', 'flagged_spam', FALSE, FALSE, $path),
          array('attributes' => array('class' => ($selected == 'spam') ? 'selected' : '')));

        break;
      case 'story':
      case 'update':
      $selected = 'All';
        if (isset($_GET['status'])) {
          $selected = ($_GET['status'] == 0) ? 'drafts' : 'published';
        }
        if ($user->uid &&  (in_array('administrator', $user->roles) || in_array('journalist', $user->roles))) {
          $links[] = l(t('Drafts'), bef_replace_query_string_arg('status', 0, FALSE, FALSE, $path),
            array('attributes' => array('class' => ($selected == 'drafts') ? 'selected' : '')));
        }
        $links[] = l(t('Published'), bef_replace_query_string_arg('status', 1, FALSE, FALSE, $path),
          array('attributes' => array('class' => ($selected == 'published') ? 'selected' : '')));
      break;
    }
  }
  return theme('checkdesk_core_render_search_header', array('links' => $links));
}

/**
 * Implements of hook_url_outbound_alter().
 */
function checkdesk_core_url_outbound_alter(&$path, &$options, $original_path) {
  //This is a taxonomy page
  if (preg_match('|^taxonomy/term/([0-9]*)|', $original_path, $matches)) {
    if (is_numeric($matches[1])) {
      $tags = taxonomy_vocabulary_machine_name_load('tags');
      $term = taxonomy_term_load($matches[1]);
      if ($tags->vid == $term->vid) {
        $path = 'search';
        $options['query']['field_tags_tid'] = $matches[1];
      }
    }
  }
  elseif ($original_path == 'checkdesk/reports') {
    $path = 'search';
    $options['query']['type'] = 'report';
  }
  elseif ($original_path == 'checkdesk/draft_stories') {
    $path = 'search';
    $options['query'] = array('type' => 'story', 'status' => 0);
  }
  elseif ($original_path == 'checkdesk/draft_updates') {
    $path = 'search';
    $options['query'] = array('type' => 'update', 'status' => 0);
  }
}

/**
 * @return string
 */
function _checkdesk_main_navigation() {
  $items = array();
  $a_class = 'main-navigation-link'; //global class for a
  $li_class = 'main-navigation-item'; //global class for item
  //Build first group links
  //homepage, add a report, write a story and search
  $items[] = array(
    'data' => l(t('Homepage'), '<front>', array(
      'attributes' => array('class' => array($a_class, 'homepage-link'))
    )),
    'class' => array($li_class, 'homepage'),
  );
  $ref_nid = 0;
  if (arg(0) == 'node' && is_numeric(arg(1)) /*&& $node->type == 'discussion'*/) {
    $ref_nid = arg(1);
  }

  if (user_access('create media content')) {
    $items[] = array(
      'data' => l(t('Submit report'), 'node/add/media', array(
        'attributes' => array('class' => array($a_class, 'create-report-link')),
        'query' => array('ref_nid' => $ref_nid),
      )),
      'class' => array($li_class, 'create-report'),
    );
  }

  if (user_access('create discussion content')) {
    $items[] = array(
      'data' => l(t('Create story'), 'node/add/discussion', array(
        'attributes' => array('class' => array($a_class, 'create-story-link')),
        'query' => array('ref_nid' => arg(1)),
      )),
      'class' => array($li_class, 'create-story'),
    );
  }
  $items[] = array(
    'data' => l(t('Search'), 'search', array(
      'attributes' => array('class' => array($a_class, 'checkdesk-search-link')),
    )),
    'class' => array($li_class, 'checkdesk-search'),
  );

  $first_group = theme('item_list', array(
    'items' => $items,
    'title' => '',
    'type' => 'ul',
    'attributes' => array('class' => 'first-group')
  ));
  // Second group
  // reports, stories and updates
  $items = array();
  $items[] = array(
    'data' => l(t('Reports'), 'search', array(
      'attributes' => array('class' => array($a_class, 'reports-link')),
      'query' => array('type' => 'media'),
    )),
    'class' => array($li_class, 'reports'),
  );
  $items[] = array(
    'data' => l(t('Stories'), 'search', array(
      'attributes' => array('class' => array($a_class, 'stories-link')),
      'query' => array('type' => 'discussion'),
    )),
    'class' => array($li_class, 'stories'),
  );
  $items[] = array(
    'data' => l(t('Updates'), 'search', array(
      'attributes' => array('class' => array($a_class, 'updates-link')),
      'query' => array('type' => 'post'),
    )),
    'class' => array($li_class, 'updates'),
  );

  $second_group = theme('item_list', array(
    'items' => $items,
    'title' => '',
    'type' => 'ul',
    'attributes' => array('class' => 'second-group')
  ));

  // Third group
  // manage users and about checkdesk
  $items = array();
  if (user_access('administer users')) {
    $items[] = array(
      'data' => l(t('Administer users'), 'admin/people', array(
        'attributes' => array('class' => array($a_class, 'administer-users-link')),
      )),
      'class' => array($li_class, 'administer-users'),
    );
  }
  $items[] = array(
    'data' => l(t('About Checkdesk'), 'content/about-checkdesk', array(
      'attributes' => array('class' => array($a_class, 'about-checkdesk-link')),
    )),
    'class' => array($li_class, 'about-checkdesk'),
  );

  $third_group = theme('item_list', array(
    'items' => $items,
    'title' => '',
    'type' => 'ul',
    'attributes' => array('class' => 'third-group')
  ));

  return theme('checkdesk_core_main_navigation', array(
    'first_group' => $first_group,
    'second_group' => $second_group,
    'third_group' => $third_group,
  ));
}
