<?php

/**
 * @file
 * Input filter that enhances oEmbed enabled URL:s with extra content
 */

/**
 * Implements hook_init().
 */
function oembed_init() {
  drupal_add_css(drupal_get_path('module', 'oembed') . '/oembed.base.css');
  drupal_add_css(drupal_get_path('module', 'oembed') . '/oembed.theme.css');
}

/**
 * Implements hook_help().
 */
function oembed_help($path, $arg) {
  switch ($path) {
    case 'admin/help#oembed':
      return '<p>' . t('Adds an input filter for replacing oEmbed enabled URLs with embedded content') . '</p>';
  }
}

/**
 * Implements hook_filter_info().
 */
function oembed_filter_info() {
  $filters['oembed'] = array(
    'title' => t('oEmbed filter'),
    'description' => t('Embeds content for oEmbed-enabled web addresses and turns the rest, and e-mail addresses, into clickable links.'),
    'prepare callback' => 'oembed_filter_oembed_prepare',
    'process callback' => 'oembed_filter_oembed_process',
    'settings callback' => 'oembed_filter_oembed_settings',
    'tips callback' => 'oembed_filter_oembed_tips',
    'default settings' => array(
      'options' => '',
      'autoembed' => TRUE,
    ),
  );
  $filters['oembed_legacy'] = array(
    'title' => t('oEmbed legacy filter'),
    'description' => t('Embeds content for oEmbed-enabled web addresses and turns the rest, and e-mail addresses, into clickable links.'),
    'process callback' => 'oembed_filter_oembed_legacy_process',
    'settings callback' => 'oembed_filter_oembed_legacy_settings',
    'default settings' => array(
      'maxwidth' => '',
      'maxheight' => '',
    ),
  );
  return $filters;
}

/**
 * Implements hook_filter_FILTER_settings().
 */
function oembed_filter_oembed_legacy_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
  module_load_include('inc', 'oembed', 'oembed_legacy');
  return _oembed_filter_settings($form, $form_state, $filter, $format, $defaults);
}

/**
 * Implements hook_filter_FILTER_process().
 */
function oembed_filter_oembed_legacy_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  module_load_include('inc', 'oembed', 'oembed_legacy');
  return _oembed_filter_apply($text, $filter, $format, $langcode, $cache, $cache_id);
}

/**
 * Implements hook_filter_FILTER_settings().
 */
function oembed_filter_oembed_settings($form, &$form_state, $filter, $format, $defaults, $filters) {
  $filter->settings += $defaults;

  $settings = array();
  $settings['options'] = array(
    '#type' => 'textfield',
    '#title' => t('Default oEmbed request options'),
    '#default_value' => $filter->settings['options'],
    '#description' => t('A series of attribute value pairs for the default request options. For example, <em>maxwidth="500"</em>.'),
  );
  $settings['autoembed'] = array(
    '#type' => 'checkbox',
    '#title' => t('Automatically embed URLs'),
    '#default_value' => $filter->settings['autoembed'],
    '#description' => t('When possible, embed the media content from a URL directly in the input.'),
  );
  return $settings;
}

/**
 * Implements hook_filter_FILTER_process().
 */
function oembed_filter_oembed_prepare($text, $filter, $format, $langcode, $cache, $cache_id) {
  if ($filter->settings['autoembed']) {
    $pattern = '|^\s*(https?://[^\s"]+)\s*$|im';
    $text = preg_replace_callback($pattern, 'oembed_preg_auto_replace', $text);
  }
  return $text;
}

/**
 * Implements hook_filter_FILTER_process().
 */
function oembed_filter_oembed_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  global $_oembed_default_attributes;

  $_oembed_default_attributes = !empty($filter->settings['options']) ? oembed_parse_attr($filter->settings['options']) : array();

  // Undo auto paragraph around media tags.
  $text = preg_replace('/<p>\s*+(\[embed\b.*?\].+?\[\/embed\])\s*+<\/p>/s', '$1', $text);

  $pattern = '/(.?)\[embed\b(.*?)\](.+?)\[\/embed\](.?)/s';
  $text = preg_replace_callback($pattern, 'oembed_preg_tag_replace', $text);

  unset($_oembed_default_attributes);

  return $text;
}

/**
 * Implements hook_filter_FILTER_tips().
 */
function oembed_filter_oembed_tips($filter, $format, $long) {
  if ($long) {
    return t('Embed content by wrapping a supported URL in [embed] &hellip; [/embed]. Set options such as width and height with attributes [embed width="123" height="456"] &hellip; [/embed]. Unsupported options will be ignored.');
  }
  else {
    return t('Embed content by wrapping a supported URL in [embed] &hellip; [/embed].');
  }
}

/**
 * PREG replace callback finds [embed] shortcodes, URLs and request options.
 */
function oembed_preg_tag_replace($match) {
  global $_oembed_default_attributes;

  // allow [[oembed]] syntax for escaping a tag
  if ($match[1] == '[' && $match[4] == ']') {
    return substr($match[0], 1, -1);
  }

  $url = $match[3];

  $options = !empty($match[2]) ? oembed_parse_attr($match[2]) : array();
  $options += $_oembed_default_attributes;

  return $match[1] . oembed_resolve_link($options, $url) . $match[4];
}

/**
 * PREG replace callback finds URLs
 */
function oembed_preg_auto_replace($match) {
  return '[embed]'. $match[1] ."[/embed]\n";
}

/**
 * PREG replace callback finds [embed] shortcodes, URLs and request options.
 */
function oembed_resolve_link($options, $url) {

  $return = '';
  $url = decode_entities($url);

  $matches = array();
  $element = array();
  if ($provider = oembedcore_get_provider($url, $matches)) {
    $element = oembedcore_render_cache('oembed_bare', $url, $options);

    // In filters, theme must have no impact on oembed output, so the cache key
    // is recalculated to exclude theme. This is normally done in
    // drupal_render_cache_set(), but it's OK here because the array is rendered
    // immediately.
    $cid_parts = drupal_render_cid_parts($element['#cache']['granularity']);
    unset($cid_parts[0]);

    $element['#cache']['cid'] = implode(':', array_merge($element['#cache']['keys'], $cid_parts));
    $return = drupal_render($element);
  }
  if (empty($return)) {
    $return = $url;
  }

  return $return;
}

/**
 * Retrieve all attributes from the shortcodes tag.
 *
 * @see shortcode_parse_atts in WordPress 3.1.3.
 * @param string $text
 * @return array List of attributes and their value.
 */
function oembed_parse_attr($text) {
  $attributes = array();
  $pattern = '/(\w+)\s*=\s*"([^"]*)"(?:\s|$)|(\w+)\s*=\s*\'([^\']*)\'(?:\s|$)|(\w+)\s*=\s*([^\s\'"]+)(?:\s|$)|"([^"]*)"(?:\s|$)|(\S+)(?:\s|$)/';
  $text = preg_replace("/[\x{00a0}\x{200b}]+/u", " ", $text);
  if (preg_match_all($pattern, $text, $matches, PREG_SET_ORDER)) {
    foreach ($matches as $match) {
      if (!empty($match[1])) {
        $attributes[strtolower($match[1])] = stripcslashes($match[2]);
      }
      elseif (!empty($match[3])) {
        $attributes[strtolower($match[3])] = stripcslashes($match[4]);
      }
      elseif (!empty($match[5])) {
        $attributes[strtolower($match[5])] = stripcslashes($match[6]);
      }
      elseif (isset($match[7]) and strlen($match[7])) {
        $attributes[] = stripcslashes($match[7]);
      }
      elseif (isset($match[8])) {
        $attributes[] = stripcslashes($match[8]);
      }
    }
  } else {
    $attributes = ltrim($text);
  }
  return $attributes;
}
