<?php

/**
 * Implements hook_migrate_api().
 */
function checkdesk_multitenancy_migration_migrate_api() {

  $migrations = array();
  $groups = array('migrations' => array());

  // Set $conf['databases_to_be_migrated'] on settings.php  
  foreach(variable_get('databases_to_be_migrated', array()) as $name) {

    $groups[$name] = array(
      'title' => t('Migration from single-tenant !name Checkdesk to multi-tenancy', array('!name' => $name)),
      'name' => $name,
    );

    $common_arguments = array(
      'source_connection' => $name,
      'source_version' => 7,
      'group_name' => $name,
    );

    $migrations['Picture_' . $name] = $common_arguments + array(
      'description' => t('Migration of user picture'),
      'default_uid' => 1,
      'source_dir' => "/mnt/$name/pictures",
      'destination_dir' => 'public://',
      'class_name' => 'DrupalPicture7Migration',
      'machine_name' => 'Picture_' . $name,
    );

    $migrations['User_' . $name] = $common_arguments + array(
      'description' => t('Migration of users from !site', array('!site' => $name)),
      'class_name' => 'CheckdeskUserMigration',
      'picture_migration' => 'Picture_' . $name,
    );

    $migrations['Term_' . $name] = $common_arguments + array(
      'description' => t('Migration of terms from !site', array('!site' => $name)),
      'class_name' => 'DrupalTerm7Migration',
      'source_vocabulary' => 'tags',
      'destination_vocabulary' => 'tags',
      'machine_name' => 'Term_' . $name,
      'soft_dependencies' => array('User_' . $name),
    );

    $migrations['Files_' . $name] = $common_arguments + array(
      'description' => t('Migration of files from !site', array('!site' => $name)),
      'machine_name' => 'Files_' . $name,
      'source_dir' => "/mnt/$name",
      'destination_dir' => 'public://',
      'class_name' => 'DrupalFile7Migration',
    );

    $migrations['Story_' . $name] = $common_arguments + array(
      'user_migration' => 'User_' . $name,
      'class_name' => 'CheckdeskStoryMigration',
      'description' => t('Migration of stories from !site', array('!site' => $name)),
      'source_type' => 'discussion',
      'destination_type' => 'discussion',
      'dependencies' => array('Term_' . $name),
    );

    $migrations['Update_' . $name] = $common_arguments + array(
      'user_migration' => 'User_' . $name,
      'class_name' => 'CheckdeskUpdateMigration',
      'description' => t('Migration of updates from !site', array('!site' => $name)),
      'source_type' => 'post',
      'destination_type' => 'post',
      'dependencies' => array('Story_' . $name),
    );
  }

  $api = array(
    'api' => 2,
    'groups' => $groups,
    'migrations' => $migrations,
  );

  return $api;
}
