<?php

define('MEEDAN_LIVEFYRE_SCRIPT', 'http://zor.livefyre.com/wjs/v3.0/javascripts/livefyre.js');

/**
 * Implements hook_node_view().
 */
function meedan_livefyre_node_view($node, $view_mode, $langcode) {
  if (!variable_get('meedan_livefyre_disable', FALSE) && in_array($node->type, array_filter(variable_get('meedan_livefyre_types', array())))) {
    $collectionMeta = array(
      'articleId' => $node->nid,
      'url' => url('node/' . $node->nid, array('absolute' => TRUE)),
    );
    $streamConfig = array(
      'collectionMeta' => $collectionMeta,
      'signed' => false,
      'articleId' => $collectionMeta['articleId'],
      'siteId' => variable_get('meedan_livefyre_siteid', ''),
      'el' => 'livefyre-' . $node->nid,
    );
    $node->content['livefyre'] = array(
      '#markup' => '<div id="livefyre-' . $node->nid . '"></div>',
      '#attached' => array(
        'js' => array(
          array('data' => MEEDAN_LIVEFYRE_SCRIPT, 'type' => 'external'),
          array('data' => array('livefyre' => array($node->nid => array(
            'nid' => $node->nid,
            'streamConfig' => $streamConfig,
          ))), 'type' => 'setting'),
          array('data' => drupal_get_path('module', 'meedan_livefyre') . '/meedan_livefyre.js', 'type' => 'file'),
        ),
      ),
    );
  }
}

/**
 * Implements hook_menu().
 */
function meedan_livefyre_menu() {
  $items = array();

  $items['admin/config/content/livefyre'] = array(
    'title' => 'Livefyre',
    'description' => 'Administer Livefyre settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('meedan_livefyre_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Form function for `admin/config/content/livefyre`.
 */
function meedan_livefyre_admin_settings() {
  $form['meedan_livefyre_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Disable'),
    '#default_value' => variable_get('meedan_livefyre_disable', FALSE),
    '#description' => t('Disable Livefyre integration.'),
  );
  $form['meedan_livefyre_siteid'] = array(
    '#type' => 'textfield',
    '#title' => t('Livefyre Site ID'),
    '#default_value' => variable_get('meedan_livefyre_siteid', ''),
  );
  $options = array();
  foreach (node_type_get_types() as $type) {
    $options[$type->type] = t($type->name);
  }
  $form['meedan_livefyre_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types'),
    '#options' => $options,
    '#default_value' => variable_get('meedan_livefyre_types', array()),
    '#description' => t('Activate Livefyre comments for the selected content types.'),
  );

  return system_settings_form($form);
}

