<?php

/**
 * Implementation of hook_menu().
 */
function checkdesk_api_menu() {
  return array(
    'checkdesk-api/docs/%' => array(
      'title' => 'Checkdesk API Explorer: JSON Docs',
      'page callback' => 'checkdesk_api_docs_json',
      'page arguments' => array(2),
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
    ),
    'checkdesk-api/ui' => array(
      'title' => 'Checkdesk API Explorer',
      'page callback' => 'checkdesk_api_ui',
      'access arguments' => array('administer site configuration'),
      'type' => MENU_CALLBACK,
    ),
  );
}

function checkdesk_api_ui() {
  print theme('swagger-ui', array('base' => '/' . drupal_get_path('module', 'checkdesk_api')));
  return NULL;
};

function checkdesk_api_docs_json($doc = 'api') {
  $docs = array('api', 'reports', 'stories');
  $contents = '';
  if (in_array($doc, $docs)) {
    $contents = file_get_contents(drupal_get_path('module', 'checkdesk_api') . '/json/' . $doc . '.json');
  }
  drupal_add_http_header('Content-Type', 'application/json');
  print $contents;
  return NULL;
}

/**
 * Implementation of hook_theme().
 */
function checkdesk_api_theme($existing, $type, $theme, $path) {
  return array(
    'swagger-ui' => array(
      'template' => 'swagger-ui',
      'variables' => array(
        'base' => NULL,
      ),
    ),
 );
}
