<?php

/**
 * @file
 * Module file for tracelytics_late module
 */

/**
 * Implements hook_boot().
 */
function tracelytics_late_boot() {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_boot', 'exit', array());
  }
}

/**
 * Implements hook_init().
 */
function tracelytics_late_init() {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_init', 'exit', array());
  }
}

/**
 * Implements hook_form_alter().
 *
 * @param array $form
 * @param array $form_state
 * @param string $form_id
 */
function tracelytics_late_form_alter(&$form, &$form_state, $form_id) {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_form_alter', 'exit', array());
  }
}

/**
 * Implements hook_views_pre_build().
 *
 * @param object $view
 */
function tracelytics_late_views_pre_build(&$view) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_views', FALSE)) {
    tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'pre_build'));
    tracelytics_oboe_log('drupal_views', 'profile_entry', array('ProfileName' => 'build'));
  }
}

/**
 * Implements hook_views_post_build().
 *
 * @param object $view
 */
function tracelytics_late_views_post_build(&$view) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_views', FALSE)) {
    tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'post_build'));
  }
}

/**
 * Implements hook_views_pre_execute().
 *
 * @param object $view
 */
function tracelytics_late_views_pre_execute(&$view) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_views', FALSE)) {
    tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'pre_execute'));
    tracelytics_oboe_log('drupal_views', 'profile_entry', array('ProfileName' => 'execute'));
  }
}

/**
 * Implements hook_views_post_execute().
 *
 * @param object $view
 */
function tracelytics_late_views_post_execute(&$view) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_views', FALSE)) {
    tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'post_execute'));
  }
}

/**
 * Implements hook_views_pre_render().
 *
 * @param object $view
 */
function tracelytics_late_views_pre_render(&$view) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_views', FALSE)) {
    tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'pre_render'));
    tracelytics_oboe_log('drupal_views', 'profile_entry', array('ProfileName' => 'render'));
  }
}

/**
 * Implements hook_views_post_render().
 *
 * @param object $view
 * @param string $output
 * @param object $cache
 */
function tracelytics_late_views_post_render(&$view, &$output, &$cache) {
  if (variable_get('tracelytics_layers', FALSE)) {
    if (variable_get('tracelytics_profile_views', FALSE)) {
      tracelytics_oboe_log('drupal_views', 'profile_exit', array('ProfileName' => 'post_render'));
    }
    tracelytics_oboe_log('drupal_views', 'exit', array());
  }
}

/**
 * Implements hook_panels_pre_render().
 *
 * @param object $display
 * @param object $renderer
 */
function tracelytics_late_panels_pre_render($display, $renderer) {
  if (variable_get('tracelytics_layers', FALSE) && variable_get('tracelytics_profile_panels', FALSE)) {
    tracelytics_oboe_log('drupal_panels', 'profile_exit', array('ProfileName' => 'pre_render'));
  }
}

/**
 * Implements hook_panels_post_render().
 *
 * @param object $display
 * @param object $renderer
 */
function tracelytics_late_panels_post_render($display, $renderer) {
  if (variable_get('tracelytics_layers', FALSE)) {
    if (variable_get('tracelytics_profile_panels', FALSE)) {
      tracelytics_oboe_log('drupal_panels', 'profile_exit', array('ProfileName' => 'post_render'));
    }
    tracelytics_oboe_log('drupal_panels', 'exit', array('Panel-Renderer' => $display->renderer, 'Panel-Layout' => $display->layout));
  }
}

/**
 * Implements hook_node_load().
 *
 * @param object $nodes
 * @param array $types
 */
function tracelytics_late_node_load($nodes, $types) {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_node_load', 'exit', array());
  }
}

/**
 * Implements hook_watchdog().
 *
 * @param array $log_entry
 */
function tracelytics_late_watchdog($log_entry) {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_watchdog', 'exit', array());
  }
}

/**
 * Implements hook_exit().
 */
function tracelytics_late_exit() {
  if (variable_get('tracelytics_layers', FALSE)) {
    tracelytics_oboe_log('drupal_hook_exit', 'exit', array());
  }
}
