<?php

function checkdesk_media_form_alter(&$form, &$form_state, $form_id) {
}

function checkdesk_media_form_media_node_form_alter(&$form, &$form_state) {
  if (!empty($form['nid']['#value'])) {
    // Hide desk reference if we're updating the report, not creating it.
    $form['field_desk']['#access'] = false;
  }
}

function checkdesk_media_node_insert($node) {
  if ($node->type == 'media') {
    // Link new report to new comment on discussion.
    $nids = field_get_items('node', $node, 'field_desk', $node->language);
    if (!empty($nids[0]['target_id'])) {
      global $language;
      global $user;
      $comment = new StdClass;
      $comment->nid = $nids[0]['target_id'];
      $comment->pid = 0;
      $comment->cid = 0;
      $comment->uid = $user->uid;
      $comment->mail = $user->mail;
      $comment->status = COMMENT_PUBLISHED;
      $comment->is_anonymous = 0;
      $comment->subject = t('Report added');
      $comment->language = LANGUAGE_NONE;
      $comment->field_media[LANGUAGE_NONE][0]['target_id'] = $node->nid;
      comment_save(comment_submit($comment));
    }
  }
}

