<?php

/**
 * Implements of hook_node_insert();
 */
function meedan_sources_node_insert($node) {
  if ($node->type == 'media') {
    //Import embed data info on statisctics table.
    $embed = oembedcore_oembed_data($node->field_link[LANGUAGE_NONE][0]['url']);
    if (empty($embed)) {
      $embed = meedan_oembed_data($node->field_link[LANGUAGE_NONE][0]['url']);
    }
    _meedan_sources_insert($embed, $node->nid);
  }
}

/**
 * Implements of hook_node_delete();
 */
function meedan_sources_node_delete($node) {
  if ($node->type == 'media') {
    db_delete('meedan_sources_media')
      ->condition('nid', $node->nid)
      ->execute();
  }
}

/**
 * Insert embed data info in sources table.
 */
function _meedan_sources_insert($embed, $nid = NULL) {
  $source_child = new stdClass();
  $source_parent = new stdClass();
  if (!$nid) {
    $nid = db_result(db_query("SELECT nid FROM {content_type_report} WHERE field_media_embed_url = '%s'", $embed->original_url));
  }

  $source_parent->source = $embed->provider_name;
  $source_parent->source_url = $embed->provider_url;
  $source_parent->parent = NULL;
  $query = db_select('meedan_sources', 'ms');
  $query->condition('ms.source', $source_parent->source);
  $query->fields('ms', array('ms_id'));
  $parent_id = $query->execute()->fetchfield();
  if (!$parent_id) {
    drupal_write_record('meedan_sources', $source_parent);
    $parent_id = $source_parent->ms_id;
  }
  if (isset($embed->author_name)) {
    $source_child->source = $embed->author_name;
    $source_child->source_url = $embed->author_url;
    $source_child->parent = $parent_id;
    $query = db_select('meedan_sources', 'ms');
    $query->condition('ms.source', $source_child->source);
    $query->condition('ms.parent', $source_child->parent);
    $query->fields('ms', array('ms_id'));
    $child_id = $query->execute()->fetchfield();
    if (!$child_id) {
      drupal_write_record('meedan_sources', $source_child);
      $child_id = $source_child->ms_id;
    }
  }
  if ($nid) { 
    //Check if there is a related node because oembed doesn't handle the deleted node.
    $ms_id = isset($child_id) ? $child_id : $parent_id;
    db_insert('meedan_sources_media')
      ->fields(array('nid' => $nid, 'ms_id'  => $ms_id,))
      ->execute();
  }
}

/**
 * Implements hook_views_api().
 */
function meedan_sources_views_api() {
  return array(
    'api' => 2.0,
  );
}

