<?php

/**
 * @file
 * Main file for the Save Draft module, which adds a 'Save as draft' button to content types.
 */

/**
 * Save draft functionality is disabled.
 */
define('SAVE_DRAFT_DISABLED', 0);

/**
 * Save draft functionality is enabled.
 */
define('SAVE_DRAFT_ENABLED', 1);

/**
 * Implements hook_permission().
 */
function save_draft_permission() {
  return array(
    'save draft' => array(
      'title' => t('Save content as draft'),
      'description' => t('Allows people with permission to view and edit their own unpublished content to change the published state of their content when saving it.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * For users with permission to choose the published state of the node being
 * edited, improves the content editing workflow by removing the Published
 * checkbox and replacing the Save button with two buttons: the original for
 * saving the node as published, and a new one for saving the node as
 * unpublished.
 */
function save_draft_form_node_form_alter(&$form, &$form_state) {
  if (variable_get('save_draft_enabled_' . $form['#node']->type, SAVE_DRAFT_ENABLED) && save_draft_access($form, $form_state)) {
    // Remove the status checkbox from the options fieldset, and adjust the
    // fieldset accordingly.
    if (isset($form['options']['status'])) {
      $form['options']['status']['#access'] = FALSE;
      $form['options']['#title'] = t('Promotion settings');
      $form['options']['#attributes']['class'] = array('node-promotion-options');
      $form['options']['#attached'] = array(
        'js' => array(
          'vertical-tabs' => drupal_get_path('module', 'save_draft') . '/save_draft.js',
        ),
      );
    }

    // Add a validation handler to set $form_state['values']['status'] based on
    // which button is clicked.
    if (empty($form['#validate'])) {
      $form['#validate'] = array();
    }
    array_unshift($form['#validate'], 'save_draft_validate');

    // The form already has a $form['actions']['submit'] button, which we'll
    // use for saving the node as published. Here, add a second button for
    // saving the node as unpublished.
    $form['actions']['draft'] = array(
      '#type' => 'submit',
      '#class' => 'form-submit',
      '#submit' => $form['actions']['submit']['#submit'],
      // Between the default Save and Preview buttons.
      '#weight' => 9,
    );

    // Button labels when adding a new node.
    if (!isset($form_state['node']->nid)) {
      $form['actions']['submit']['#value'] = t('Publish');
      $form['actions']['draft']['#value'] = t('Save as draft');
    }
    // Button labels when editing an existing draft.
    elseif (!$form_state['node']->status) {
      $form['actions']['submit']['#value'] = t('Publish');
      $form['actions']['draft']['#value'] = t('Save');
      // Move the draft button before the submit button, so that the
      // "Save" action is always first when editing existing content.
      $form['actions']['draft']['#weight'] = 0;
    }
    // Button labels when editing an already published node.
    else {
      $form['actions']['submit']['#value'] = t('Save');
      $form['actions']['draft']['#value'] = t('Unpublish');
    }
  }
}

/**
 * Handles save draft form validation
 */
function save_draft_validate($form, &$form_state) {
  // Set the node to be published or unpublished depending on which button was
  // clicked.
  if ($form_state['triggering_element']['#value'] == $form['actions']['draft']['#value']) {
    $form_state['values']['status'] = 0;
  }
  elseif ($form_state['triggering_element']['#value'] == $form['actions']['submit']['#value']) {
    $form_state['values']['status'] = 1;
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the node type form.
 */
function save_draft_form_node_type_form_alter(&$form, &$form_state) {
  $enabled = variable_get('save_draft_enabled_' . $form['#node_type']->type, SAVE_DRAFT_ENABLED);

  $form['save_draft'] = array(
    '#type' => 'fieldset',
    '#title' => t('Enable "Save draft" button'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => !$enabled,
    '#group' => 'additional_settings',
    '#attached' => array(
      'js' => array(
        'save-draft' => drupal_get_path('module', 'save_draft') . '/save_draft.js',
      ),
    ),
  );

  $form['save_draft']['save_draft_enabled'] = array(
    '#title' => t('Enabled'),
    '#type' => 'checkbox',
    '#description' => t('Enable save as draft functionality for this content type.'),
    '#default_value' => $enabled,
  );
}

/**
 * Returns TRUE if the currently logged in user has permission to choose the published state for the node being edited.
 */
function save_draft_access($form, &$form_state) {
  // Determine if the user has access to publish / unpublish this node via the
  // status checkbox.
  $element = $form;
  $access = TRUE;
  foreach (array('options', 'status') as $key) {
    if (!isset($element[$key])) {
      $access = FALSE;
      break;
    }
    $element = $element[$key];
    if ((isset($element['#access']) && !$element['#access']) || !empty($element['#disabled'])) {
      $access = FALSE;
      break;
    }
  }

  // If not, but the user has the 'save draft' permission, determine if the user
  // has access to view and edit this node if it were unpublished. Don't allow a
  // user to save a draft that they won't be able to get back to.
  if (!$access && user_access('save draft')) {
    $node = clone($form_state['node']);
    $node->status = FALSE;

    // This might be a new node, and node_access() throws PHP warnings if nid
    // isn't defined.
    if (!isset($node->nid)) {
      $node->nid = NULL;
    }

    $access = node_access('update', $node) && node_access('view', $node);
  }

  return $access;
}

/**
 * Implements hook_node_type_delete().
 */
function save_draft_node_type_delete($info) {
  variable_del('save_draft_enabled_' . $info->type);
}
