<?php
/**
 * Meedan Facebook
 * 0.1 - Render Facebook comments
 * References:
 * http://developers.facebook.com/docs/reference/plugins/comments/
 * http://developers.facebook.com/docs/reference/javascript/
 *
 */

/**
 * Implements hook_theme().
 */
function meedan_facebook_theme() {
  return array(
    'facebook_commentcount' => array(
      'variables' => array('node' => NULL),
    ),
    'facebook_comments' => array(
      'variables' => array('node' => NULL),
    ),
  );
}

/**
 * Return which base path should be used to retrieve comments for a given node
 */
function _meedan_facebook_get_path($nid) {
  global $language;
  $path = 'node/' . $nid;
  $base = variable_get('meedan_facebook_base_path', 'raw');
  $alias = TRUE;
  switch($base) {
    case 'raw':
      // Does nothing, $path is correctly set
      break;
    case 'first':
      $path = db_query("SELECT alias FROM {url_alias} WHERE source = :source AND language = :language ORDER BY pid ASC", array(':source' => $path, ':language' => $language->language))->fetchField();
      $alias = FALSE;
      break;
    case 'last':
      $path = drupal_get_path_alias($path, $language->language);
      $alias = FALSE;
      break;
  }
  return url($path, array('absolute' => TRUE, 'language' => (object) array('language' => FALSE), 'alias' => $alias));
}

/**
 * Add FB app ID in an HTML meta tag.
 */
function meedan_facebook_add_metatag() {
  $app_id = variable_get('meedan_facebook_appid', variable_get('fboauth_id', ''));
  drupal_add_html_head(array(
    '#tag' => 'meta',
    '#attributes' => array(
      'property' => 'fb:app_id',
      'content' => $app_id,
    ),
  ), 'meedan_facebook_appid');
}

/**
 * Implements `facebook_commentcount` theme.
 */
function theme_facebook_commentcount($variables) {
  global $base_url;

  meedan_facebook_add_metatag();

  drupal_add_js(array('meedanFacebookComments' => array(
    'language' => meedan_facebook_get_locale(),
    'appId' => variable_get('meedan_facebook_appid', variable_get('fboauth_id', '')),
  )), 'setting');
  drupal_add_js(drupal_get_path('module', 'meedan_facebook') . '/meedan_facebook.js');

  $node = $variables['node'];
  $nid = $node->nid;
  $path = _meedan_facebook_get_path($nid);
  $output  = '<span class="fb-comments-count" data-href="' . $path . '" id="fb-commentscount-'. $nid .'">0</span>&nbsp;';
  return $output;
}

/**
 * Implements `facebook_comments` theme.
 */
function theme_facebook_comments($variables) {
  global $base_url;

  $node = $variables['node'];
  $per_page = variable_get('meedan_facebook_comments_per_page', 10);
  $nid = $node->nid;

  meedan_facebook_add_metatag();

  drupal_add_js(array('meedanFacebookComments' => array(
    'language' => meedan_facebook_get_locale(),
    'appId' => variable_get('meedan_facebook_appid', variable_get('fboauth_id', '')),
  )), 'setting');
  drupal_add_js(drupal_get_path('module', 'meedan_facebook') . '/meedan_facebook.js');

  $path = _meedan_facebook_get_path($nid);
  $output = '<div class="fb-comments" data-href="' . $path . '" data-num-posts="' . $per_page . '" data-nid="' . $nid . '" id="fb-comments-' . $nid . '" data-version="v2.3"></div>';
  return $output;
}

/**
 * Implements hook_node_view().
 */
function meedan_facebook_node_view($node, $view_mode, $langcode) {
  if (!variable_get('meedan_facebook_comments_disable', FALSE) && in_array($node->type, array_filter(variable_get('meedan_facebook_comments_types', array()))) && !empty($node->status)) {
    $node->content['custom_comments'] = array(
      '#theme' => 'facebook_comments',
      '#node' => $node,
    );
  }
}

/**
 * Implements hook_menu().
 */
function meedan_facebook_menu() {
  $items = array();

  $items['admin/config/content/facebook'] = array(
    'title' => 'Facebook Comments',
    'description' => 'Administer Facebook Comments settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('meedan_facebook_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Helper function to get a locale as Facebook expects.
 */
function meedan_facebook_get_locale($lang_code = '') {
  $languages_map = array(
    'af' => 'af_ZA',
    'ar' => 'ar_AR',
    'ay' => 'ay_BO',
    'az' => 'az_AZ',
    'be' => 'be_BY',
    'bg' => 'bg_BG',
    'bn' => 'bn_IN',
    'bs' => 'bs_BA',
    'ca' => 'ca_ES',
    'cs' => 'cs_CZ',
    'cy' => 'cy_GB',
    'da' => 'da_DK',
    'de' => 'de_DE',
    'el' => 'el_GR',
    'en' => 'en_US',
    'eo' => 'eo_EO',
    'es' => 'es_ES',
    'et' => 'et_EE',
    'eu' => 'eu_ES',
    'fa' => 'fa_IR',
    'fi' => 'fi_FI',
    'fo' => 'fo_FO',
    'fr' => 'fr_FR',
    'ga' => 'ga_IE',
    'gl' => 'gl_ES',
    'gn' => 'gn_PY',
    'gu' => 'gu_IN',
    'he' => 'he_IL',
    'hi' => 'hi_IN',
    'hr' => 'hr_HR',
    'hu' => 'hu_HU',
    'hy' => 'hy_AM',
    'id' => 'id_ID',
    'is' => 'is_IS',
    'it' => 'it_IT',
    'ja' => 'ja_JP',
    'jv' => 'jv_ID',
    'ka' => 'ka_GE',
    'kk' => 'kk_KZ',
    'km' => 'km_KH',
    'kn' => 'kn_IN',
    'ko' => 'ko_KR',
    'ku' => 'ku_TR',
    'la' => 'la_VA',
    'lt' => 'lt_LT',
    'lv' => 'lv_LV',
    'mg' => 'mg_MG',
    'mk' => 'mk_MK',
    'ml' => 'ml_IN',
    'mn' => 'mn_MN',
    'mr' => 'mr_IN',
    'ms' => 'ms_MY',
    'mt' => 'mt_MT',
    'nb' => 'nb_NO',
    'ne' => 'ne_NP',
    'nl' => 'nl_BE',
    'nn' => 'nn_NO',
    'pa' => 'pa_IN',
    'pl' => 'pl_PL',
    'ps' => 'ps_AF',
    'qu' => 'qu_PE',
    'rm' => 'rm_CH',
    'ro' => 'ro_RO',
    'ru' => 'ru_RU',
    'sa' => 'sa_IN',
    'se' => 'se_NO',
    'sk' => 'sk_SK',
    'sl' => 'sl_SI',
    'so' => 'so_SO',
    'sq' => 'sq_AL',
    'sr' => 'sr_RS',
    'sv' => 'sv_SE',
    'sw' => 'sw_KE',
    'ta' => 'ta_IN',
    'te' => 'te_IN',
    'tg' => 'tg_TJ',
    'th' => 'th_TH',
    'tl' => 'tl_ST',
    'tr' => 'tr_TR',
    'tt' => 'tt_RU',
    'uk' => 'uk_UA',
    'ur' => 'ur_PK',
    'uz' => 'uz_UZ',
    'vi' => 'vi_VN',
    'xh' => 'xh_ZA',
    'yi' => 'yi_DE',
    'zh-hans' => 'zh_CN',
    'zh-hant' => 'zh_TW',
    'zu' => 'zu_ZA',
  );
  if (empty($lang_code)) {
    global $language;
    $lang_code = $language->language;
  }
  if (isset($languages_map[$lang_code])) {
    return $languages_map[$lang_code];
  }
  else {
    return 'en_US';
  }
}

/**
 * Form function for `admin/config/content/facebook`.
 */
function meedan_facebook_admin_settings() {
  $form['meedan_facebook_comments_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Disable Facebook comments.'),
    '#default_value' => variable_get('meedan_facebook_comments_disable', FALSE),
  );
  $options = array();
  foreach (node_type_get_types() as $type) {
    $options[$type->type] = t($type->name);
  }
  $form['meedan_facebook_comments_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types'),
    '#options' => $options,
    '#default_value' => variable_get('meedan_facebook_comments_types', array()),
    '#description' => t('Activate Facebook comments for the selected content types.'),
  );
  $form['meedan_facebook_appid'] = array(
    '#type' => 'textfield',
    '#title' => t('App ID'),
    '#size' => 20, 
    '#maxlengh' => 50, 
    '#description' => t('To use Facebook Connect, a Facebook app must be created. Create your app at <a href="@url">My Apps</a> on Facebook.', 
      array(
        '@url' => 'https://developers.facebook.com/apps/',
      )
    ),
    '#default_value' => variable_get('meedan_facebook_appid', variable_get('fboauth_id', '')),
  );
  $form['meedan_facebook_comments_per_page'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of posts'),
    '#size' => 20,
    '#maxlengh' => 50, 
    '#description' => t('Number of posts to show before "view all" appears.'),
    '#default_value' => variable_get('meedan_facebook_comments_per_page', 10),
  );
  $form['meedan_facebook_base_path'] = array(
    '#type' => 'radios',
    '#title' => t('Which node URL alias to use as a base path to load comments'),
    '#default_value' => variable_get('meedan_facebook_base_path', 'raw'),
    '#options' => array('first' => t('Use the first alias found for this node'), 'last' => t('Use the last alias found for this node'), 'raw' => t('Do not use an alias, use a raw path (eg, node/123)')),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_page_build().
 */
function meedan_facebook_page_build(&$page) {
  if (!variable_get('meedan_facebook_comments_disable', FALSE)) {
    $page['page_top']['facebook_root'] = array(
      '#weight' => 25,
      '#markup' => '<div id="fb-root"></div>',
    );
  }
}
