<?php
/**
 * Meedan Facebook
 * 0.1 - Render Facebook comments
 * References:
 * http://developers.facebook.com/docs/reference/plugins/comments/
 * http://developers.facebook.com/docs/reference/javascript/
 *
 */

/**
 * Implements hook_theme().
 */
function meedan_facebook_theme() {
  return array(
    'facebook_commentcount' => array(
      'variables' => array('node' => NULL),
    ),
    'facebook_comments' => array(
      'variables' => array('node' => NULL),
    ),
  );
}

/**
 * Return which base path should be used to retrieve comments for a given node
 */
function _meedan_facebook_get_path($nid) {
  global $language;
  $path = 'node/' . $nid;
  $base = variable_get('meedan_facebook_base_path', 'raw');
  $alias = TRUE;
  switch($base) {
    case 'raw':
      // Does nothing, $path is correctly set
      break;
    case 'first':
      $path = db_query("SELECT alias FROM {url_alias} WHERE source = :source AND language = :language ORDER BY pid ASC", array(':source' => $path, ':language' => $language->language))->fetchField();
      $alias = FALSE;
      break;
    case 'last':
      $path = drupal_get_path_alias($path, $language->language);
      $alias = FALSE;
      break;
  }
  return url($path, array('absolute' => TRUE, 'language' => (object) array('language' => FALSE), 'alias' => $alias));
}

/**
 * Implements `facebook_commentcount` theme.
 */
function theme_facebook_commentcount($variables) {
  global $base_url;

  drupal_add_js(array('meedan_facebook' => array(
    'language' => meedan_facebook_get_locale(),
    'appId' => variable_get('meedan_facebook_appid', ''),
    'channelUrl' => $base_url . '/meedan_facebook/channel',
  )), 'setting');
  drupal_add_js(drupal_get_path('module', 'meedan_facebook') . '/meedan_facebook.js');

  $node = $variables['node'];
  $nid = $node->nid;
  $path = _meedan_facebook_get_path($nid);
  $output  = '<span class="fb-commentscount" data-url="'. $path .'" id="fb-commentscount-'. $nid .'">';
  $output .= t('@count Comments (Be the first!)', array('@count' => 0));
  $output .= '</span>';
  return $output;
}

/**
 * Implements `facebook_comments` theme.
 */
function theme_facebook_comments($variables) {
  global $base_url;

  $node = $variables['node'];
  $per_page = variable_get('meedan_facebook_comments_per_page', 10);
  $nid = $node->nid;

  drupal_add_js(array('meedan_facebook' => array(
    'language' => meedan_facebook_get_locale(),
    'appId' => variable_get('meedan_facebook_appid', ''),
    'channelUrl' => $base_url . '/meedan_facebook/channel',
  )), 'setting');
  drupal_add_js(drupal_get_path('module', 'meedan_facebook') . '/meedan_facebook.js');

  $path = _meedan_facebook_get_path($nid);

  $output  = '<div class="fb-comments-wrapper">';
  $output .= '<div class="fb-comments-header">';
  $output .= theme('facebook_commentcount', array('node' => $node));
  $output .= '</div>';
  $output .= '<div class="fb-comments" data-href="'.$path.'" data-num-posts="' . $per_page . '" data-nid="' . $nid . '" id="fb-comments-' . $nid . '"></div>';
  $output .= '</div>';
  return $output;
}

/**
 * Implements hook_node_view().
 */
function meedan_facebook_node_view($node, $view_mode, $langcode) {
  if (!variable_get('meedan_facebook_comments_disable', FALSE) && in_array($node->type, array_filter(variable_get('meedan_facebook_comments_types', array())))) {
    $node->content['custom_comments'] = array(
      '#theme' => 'facebook_comments',
      '#node' => $node,
    );
  }
}

/**
 * Implements hook_menu().
 */
function meedan_facebook_menu() {
  $items = array();

  $items['admin/config/content/facebook'] = array(
    'title' => 'Facebook',
    'description' => 'Administer Facebook settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('meedan_facebook_admin_settings'),
    'access arguments' => array('administer site configuration'),
  );

  $items['meedan_facebook/channel'] = array(
    'type' => MENU_CALLBACK,
    'description' => 'Facebook Custom Channel URL',
    'page callback' => 'meedan_facebook_custom_channel_url',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Helper function to get a locale as Facebook expects
 */
function meedan_facebook_get_locale() {
  global $language;
  // TODO: Change this to a more rigorous mapping based on http://www.facebook.com/translations/FacebookLocales.xml
  $language_map = array(
    'en' => 'en_US',
    'ar' => 'ar_AR',
  );
  return $language_map[$language->language];
}

/**
 * Form function for `admin/config/content/facebook`.
 */
function meedan_facebook_admin_settings() {
  $form['meedan_facebook_comments_disable'] = array(
    '#type' => 'checkbox',
    '#title' => t('Disable Facebook comments.'),
    '#default_value' => variable_get('meedan_facebook_comments_disable', FALSE),
  );
  $options = array();
  foreach (node_type_get_types() as $type) {
    $options[$type->type] = t($type->name);
  }
  $form['meedan_facebook_comments_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Content types'),
    '#options' => $options,
    '#default_value' => variable_get('meedan_facebook_comments_types', array()),
    '#description' => t('Activate Facebook comments for the selected content types.'),
  );
  $form['meedan_facebook_appid'] = array(
    '#type' => 'textfield',
    '#title' => t('App ID'),
    '#size' => 20, 
    '#maxlengh' => 50, 
    '#description' => t('To use Facebook connect, a Facebook Application must be created. Set up your app in <a href="http://www.facebook.com/developers/apps.php">my apps</a> on Facebook.') . ' ' . t('Enter your App ID here.'),
    '#default_value' => variable_get('meedan_facebook_appid', ''),
  );
  $form['meedan_facebook_comments_per_page'] = array(
    '#type' => 'textfield',
    '#title' => t('Number of posts'),
    '#size' => 20,
    '#maxlengh' => 50, 
    '#description' => t('Number of posts to show before "view all" appears.'),
    '#default_value' => variable_get('meedan_facebook_comments_per_page', 10),
  );
  $form['meedan_facebook_base_path'] = array(
    '#type' => 'radios',
    '#title' => t('Which node URL alias to use as a base path to load comments'),
    '#default_value' => variable_get('meedan_facebook_base_path', 'raw'),
    '#options' => array('first' => t('Use the first alias found for this node'), 'last' => t('Use the last alias found for this node'), 'raw' => t('Do not use an alias, use a raw path (eg, node/123)')),
  );
  return system_settings_form($form);
}

/**
 * Implements hook_page_build().
 */
function meedan_facebook_page_build(&$page) {
  if (!variable_get('meedan_facebook_comments_disable', FALSE)) {
    $page['page_top']['facebook_root'] = array(
      '#weight' => 25,
      '#markup' => '<div id="fb-root"></div>',
    );
  }
}

/**
 * The Custom Channel URL that FB.init has as an option
 */
function meedan_facebook_custom_channel_url() {
  header("Cache-Control: public, s-maxage=31536000, max-age=31536000");
  header("Expires: Sun, 1 Oct 2079 00:00:00 GMT");
  print '<script src="http://connect.facebook.net/' . meedan_facebook_get_locale() . '/all.js"></script>';
  exit;
}
