source "https://rubygems.org"

group :development do 
  gem 'susy'
  gem 'compass'
  gem 'guard'
  gem 'guard-livereload'
end

# gem "compass_twitter_bootstrap", "2.2.1" # does not exist yet at this version but you can build it yourself from commit 36624333ed on compass_twitter_bootstrap project on github.
# https://github.com/vwall/compass-twitter-bootstrap