<?php


/**
 * Link reports and stories.
 */
function meedan_reports_update_7001() {
  db_query("
    INSERT INTO {field_data_field_desk} (
      SELECT 'node', n.type, 0, n.nid, n.vid, 'und', 0, field_desk_target_id 
      FROM {checkdesk_reports_updates} ru 
      INNER JOIN {node} n ON ru.report_nid = n.nid 
      INNER JOIN {field_data_field_desk} fd ON ru.update_nid = fd.entity_id
      GROUP BY n.nid
    )
    ");
}
