<?php

/**
 * @file
 * The Node export serialize module.
 *
 * Adds serialize format to Node export.
 */

/**
 * Implements hook_node_export_format_handlers().
 *
 * @see hook_node_export_format_handlers()
 */
function node_export_serialize_node_export_format_handlers() {
  return array(
    'serialize' => array(
      '#title' => t('Serialize'),
      '#module' => 'node_export_serialize',
      '#description' => t(
        'Very robust, though not human readable, representation through <a href="!wiki">Serialization</a> using the PHP <a href="!php">serialize</a> function.', 
        array(
          '!wiki' => 'http://tools.ietf.org/html/rfc4180', 
          '!php' => 'http://en.wikipedia.org/wiki/Comma-separated_values'
        )
      ),
    ),
  );
}

/**
 * Implements hook_node_export().
 *
 * @see hook_node_export()
 */
function node_export_serialize_node_export($nodes, $format) {
  return "node_export_serialize::" . htmlspecialchars(serialize($nodes));
}

/**
 * Implements hook_node_export_import().
 *
 * @see hook_node_export_import()
 */
function node_export_serialize_node_export_import($code_string) {
  // Check for "node_export_serialize::" at the start.
  if (substr(ltrim($code_string), 0, 23) == "node_export_serialize::") {
    return unserialize(htmlspecialchars_decode(str_replace("node_export_serialize::", "", $code_string)));
  }
}
