<?php
/**
 * @file
 * Main checkdesk_multitenancy file
 */

define('CHECKDESK_MULTITENANCY_GROUP_TYPE', 'newsroom');
define('CHECKDESK_MULTITENANCY_GROUPED_TYPE', 'discussion');

function _checkdesk_multitenancy_roles() {
  $roles = array();
  foreach (user_roles(TRUE) as $rid => $name) {
    if ($rid != DRUPAL_AUTHENTICATED_RID) {
      $roles[] = $name;
    }
  }
  return $roles;
}

/**
 * Implements hook_node_info().
 */
function checkdesk_multitenancy_node_info() {
  return array(
    CHECKDESK_MULTITENANCY_GROUP_TYPE => array(
      'name' => t('Newsroom'),
      'base' => 'node_content',
      'has_title' => TRUE,
      'title_label' => t('Name'),
      'description' => t('A newsroom is a single Checkdesk instance (tenant) inside the whole Checkdesk environment.'),
      'comment' => array('status' => 2),
    )
  );
}

/**
 * Implements hook_form().
 */
function checkdesk_multitenancy_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_og_default_roles_alter().
 */
function checkdesk_multitenancy_og_default_roles_alter(&$roles) {
  $roles = _checkdesk_multitenancy_roles();
}

/**
 * Implements hook_node_insert().
 */
function checkdesk_multitenancy_node_insert($node) {
  if (og_is_group_type('node', $node->type)) {
    $og_roles = og_roles('node', $node->type);
    $rid = array_search('journalist', $og_roles);
    og_role_grant('node', $node->nid, $node->uid, $rid);
    $rid = array_search('administrator', $og_roles);
    og_role_grant('node', $node->nid, $node->uid, $rid);
  }
}

/**
 * Implements hook_og_permission_alter().
 */
function checkdesk_multitenancy_og_permission_alter(&$perms) {
  // Any member can invite other user
  $perms['invite any user']['default role'][] = OG_AUTHENTICATED_ROLE;

  // Journalists can assign roles
  $perms['manage members']['default role'][] = 'journalist';

  // Journalists can manage stories inside newsrooms
  $story_permissions = array_keys(og_list_permissions(CHECKDESK_MULTITENANCY_GROUPED_TYPE));
  foreach ($story_permissions as $name) {
    $perms[$name]['default role'] = array('journalist');
  }

  // Owners can do everything
  foreach ($perms as &$perm) {
    $perm['default role'][] = 'administrator';
  }
}
