-- Upgrade SQL for CheckDesk codebases migrating to the new
-- Meedan D7 Boilerplate system.
--
-- October 23, 2012


-- Update the system table
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE name = 'checkdesk_core';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE name = 'checkdesk_core_feature';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE name = 'checkdesk_media';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_devel';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_devel_feature';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_notifications';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_oembed';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_reports';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_sensitive_content';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE name = 'meedan_sources';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'actions_rest';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'auto_nodetitle';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'better_exposed_filters';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'better_formats';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'chosen';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'comment_goodness';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'context';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'context_layouts';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'context_ui';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'bulk_export';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_access_ruleset';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_ajax_sample';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_custom_content';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_plugin_example';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'page_manager';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'stylizer';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_export_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'ctools_plugin_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_content';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'devel';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'devel_generate';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'devel_node_access';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entity';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entity_token';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entity_feature';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entity_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entity_test_i18n';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entityreference';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'entityreference_behavior_example';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'features';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'features_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'features_translations';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'flag';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'flag_actions';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'formblock';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'geofield';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'geophp';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_comments';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_defaults';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_example';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_nodejs';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_og';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_plugins';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_rules';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'heartbeat_ui';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'jquery_update';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'libraries';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'libraries_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'link';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'maillog';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'markdown';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'file_entity';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'media_oembed';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembed';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembedcore';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembedembedly';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembedfield';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembedprovider';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'oembed_thumbnail';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'pathauto';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'remote_stream_wrapper';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'rules';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'rules_admin';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'rules_i18n';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'rules_scheduler';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'rules_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'save_draft';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'sharethis';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'strongarm';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'taskbar';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'token_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'token';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_test';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_ui';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_autocomplete_filters';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'actions_permissions';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_bulk_operations';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_fluid_grid';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_autorefresh';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_block';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_composite_exposed_form';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_display_block_path';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_filters_selective';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_flipped_table';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_perm';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_summary_taxonomy';
UPDATE system SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE name = 'views_load_more';

-- Update the registry
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE module = 'checkdesk_core';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE module = 'checkdesk_core_feature';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/custom') WHERE module = 'checkdesk_media';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_devel';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_devel_feature';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_notifications';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_oembed';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_reports';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_sensitive_content';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/meedan') WHERE module = 'meedan_sources';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'actions_rest';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'auto_nodetitle';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'better_exposed_filters';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'better_formats';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'chosen';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'comment_goodness';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'context';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'context_layouts';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'context_ui';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'bulk_export';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_access_ruleset';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_ajax_sample';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_custom_content';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_plugin_example';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'page_manager';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'stylizer';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_export_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'ctools_plugin_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_content';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'devel';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'devel_generate';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'devel_node_access';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entity';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entity_token';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entity_feature';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entity_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entity_test_i18n';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entityreference';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'entityreference_behavior_example';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'features';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'features_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'features_translations';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'flag';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'flag_actions';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'formblock';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'geofield';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'geophp';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_comments';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_defaults';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_example';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_nodejs';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_og';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_plugins';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_rules';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'heartbeat_ui';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'jquery_update';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'libraries';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'libraries_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'link';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'maillog';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'markdown';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'file_entity';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'media_oembed';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembed';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembedcore';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembedembedly';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembedfield';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembedprovider';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'oembed_thumbnail';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'pathauto';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'remote_stream_wrapper';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'rules';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'rules_admin';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'rules_i18n';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'rules_scheduler';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'rules_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'save_draft';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'sharethis';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'strongarm';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'taskbar';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'token_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'token';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_test';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_ui';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_autocomplete_filters';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'actions_permissions';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_bulk_operations';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_fluid_grid';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_autorefresh';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_block';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_composite_exposed_form';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_display_block_path';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_filters_selective';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_flipped_table';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_perm';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_summary_taxonomy';
UPDATE registry SET filename = REPLACE(filename, 'sites/all/modules', 'sites/all/modules/contrib') WHERE module = 'views_load_more';

-- Manually wipe caches
TRUNCATE `cache`;
TRUNCATE `cache_block`;
TRUNCATE `cache_bootstrap`;
TRUNCATE `cache_field`;
TRUNCATE `cache_filter`;
TRUNCATE `cache_form`;
TRUNCATE `cache_image`;
TRUNCATE `cache_libraries`;
TRUNCATE `cache_menu`;
TRUNCATE `cache_oembed`;
TRUNCATE `cache_page`;
TRUNCATE `cache_path`;
TRUNCATE `cache_rules`;
TRUNCATE `cache_token`;
TRUNCATE `cache_update`;
TRUNCATE `cache_views`;
TRUNCATE `cache_views_data`;