<?php

/**
 * Implements hook_menu().
 */
function meedan_core_menu() {
  $items = array();
  $items['admin/meedan'] = array(
    'title' => 'Meedan',
    'description' => 'Meedan settings and configuration.',
    // 'position' => 'right',
    // 'weight' => -8,
    'page callback' => 'meedan_core_admin_page',
    'access arguments' => array('access administration pages'),
  );
  return $items;
}

/**
 * A top-level menu item used to house other Meedan admin pages.
 */
function meedan_core_admin_page() {
  $item = menu_get_item();
  if ($content = system_admin_menu_block($item)) {
    $output = theme('admin_block_content', array('content' => $content));
  }
  else {
    $output = t('You do not have any administrative items.');
  }
  return $output;
}
