<?php
/**
 * @file
 * checkdesk_api_feature.features.translations.inc
 */

/**
 * Implements hook_translations_defaults().
 */
function checkdesk_api_feature_translations_defaults() {
  $translations = array();
  $translations['ar:ui']['1d9b63575b59cb4e995a92bebc1df0fa'] = array(
    'source' => 'ADD_REPORT',
    'context' => '',
    'location' => '',
    'translation' => 'troper ddA',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['ar:ui']['6cc40012f20675e7a06b28ee6eaf5f50'] = array(
    'source' => 'LANGUAGE_TOGGLE',
    'context' => '',
    'location' => '',
    'translation' => 'English',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['1d9b63575b59cb4e995a92bebc1df0fa'] = array(
    'source' => 'ADD_REPORT',
    'context' => '',
    'location' => '',
    'translation' => 'Add report',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['3c6d02842fc9755c8098ed68678bbf88'] = array(
    'source' => 'BOTTOM_CONTENT_GOES_HERE',
    'context' => '',
    'location' => '',
    'translation' => 'Bottom content goes here',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['6e5f8f74d6890a43de987cf78129c815'] = array(
    'source' => 'REALLY_BOTTOM_CONTENT_GOES_HERE',
    'context' => '',
    'location' => '',
    'translation' => 'Really bottom content goes here',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['dca11596e64e06d60620d00eabcdff31'] = array(
    'source' => 'MAIN_MENU_ITEM_HOME_TITLE',
    'context' => '',
    'location' => '',
    'translation' => 'Home',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['d333178ad8239aedaf4fa86fddbbe201'] = array(
    'source' => 'MAIN_MENU_ITEM_REPORTS_TITLE',
    'context' => '',
    'location' => '',
    'translation' => 'Reports',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['44e61918819792808488f5dc87c293ad'] = array(
    'source' => 'USER_MENU_ITEM_LOGIN_TITLE',
    'context' => '',
    'location' => '',
    'translation' => 'Log in',
    'plid' => 0,
    'plural' => 0,
  );
  $translations['en-NG:ui']['6cc40012f20675e7a06b28ee6eaf5f50'] = array(
    'source' => 'LANGUAGE_TOGGLE',
    'context' => '',
    'location' => '',
    'translation' => 'العربية',
    'plid' => 0,
    'plural' => 0,
  );
  return $translations;
}
