<?php

/**
 * Implements hook_entity_info_alter();
 */
function checkdesk_media_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['embed'] = array(
  'label' => t('Embed'),
  'custom settings' => TRUE,
  );
}

/**
 * Implements hook_wysiwyg_editor_settings_alter();
 */
function checkdesk_media_wysiwyg_editor_settings_alter(&$settings, &$context) {
  if($context['profile']->editor == 'ckeditor') {
    $settings['extraAllowedContent'] = 'img(*)[*]';
  }
}
?>