<?php

/**
 * Implements hook_entity_info_alter();
 */
function checkdesk_media_entity_info_alter(&$entity_info) {
  $entity_info['file']['view modes']['embed'] = array(
  'label' => t('Embed'),
  'custom settings' => TRUE,
  );
}

/**
 * Implements hook_wysiwyg_editor_settings_alter();
 */
function checkdesk_media_wysiwyg_editor_settings_alter(&$settings, &$context) {
  if($context['profile']->editor == 'ckeditor') {
    $settings['extraAllowedContent'] = 'img(*)[*]'; // enable img tag in CKEditor
    $settings['removePlugins'] = 'image';           // disable image properties dialog
  }
  // Set height for caption and credit fields
  if($context['profile']->format == 'captions') {
    $settings['height'] = 100;
  }
}

/**
 * Implements hook_form_form_id_alter();
 */
// function checkdesk_media_form_media_wysiwyg_format_form_alter(&$form, &$form_state) {
//   // drupal_add_css('.form-item-format {display: none;}', array('type' => 'inline')); // hide image view mode selection form item
// }


// function checkdesk_media_media_browser_plugins_alter(&$plugin_output) {
//   // dsm($plugin_output);
  
// }

/**
 * Add messages to the page.
 */
function checkdesk_media_preprocess_media_dialog_page(&$variables) {
  // Add a path to the theme so checkdesk_inject_bootstrap.js can load libraries
  $variables['basePathCheckdeskTheme'] = url(drupal_get_path('theme', 'checkdesk'), array('language' => (object) array('language' => FALSE)));
  drupal_add_js(array('basePathCheckdeskTheme' => $variables['basePathCheckdeskTheme']), 'setting');

  // add some js bits
    drupal_add_js(
      drupal_get_path('theme', 'checkdesk') . '/assets/js/media.js',
      array(
        'scope' => 'footer',
        'group' => JS_THEME,
        'weight' => '9990',
        'every_page' => FALSE,
      )
    );

  // Add css files for media browser
  // Media CSS to override the css supplied by the module
  drupal_add_css(
    drupal_get_path('theme', 'checkdesk') . '/assets/css/components/media.css',
    array(
      'scope' => 'footer',
      'group' => CSS_THEME,
      'weight' => '9990',
      'every_page' => FALSE,
    )
  );

  // Jquery UI dialog
  drupal_add_css(
    drupal_get_path('theme', 'checkdesk') . '/assets/css/replace_drupal/jquery_ui_dialog.css',
    array(
      'scope' => 'footer',
      'group' => CSS_THEME,
      'weight' => '9991',
      'every_page' => FALSE,
    )
  );

  // Tabs
  drupal_add_css(
    drupal_get_path('theme', 'checkdesk') . '/assets/css/replace_drupal/jquery_ui_tabs.css',
    array(
      'scope' => 'footer',
      'group' => CSS_THEME,
      'weight' => '9992',
      'every_page' => FALSE,
    )
  );

  



}