<?php

/**
 * Implements hook_init().
 */
function what_site_init() {
  if (user_access('can see whatsite') && $path = what_site_path()) {
    drupal_add_js($path . '/whatsite.js', array('group' => JS_THEME));
    drupal_add_js('jQuery(function () { WhatSite.apply(); });', array('type' => 'inline', 'group' => JS_THEME));
  }
}

/**
 * Implements hook_permission().
 */
function what_site_permission() {
  return array(
    'can see whatsite' =>  array(
      'title' => t('Can see WhatSite?'),
      'description' => t('Controls whether this role can see the coloured bars at the top of dev/testing sites.'),
    ),
  );
}

/**
 * Attempts to locate the directory of the WhatSite library.
 */
function what_site_path() {
  $search_paths = array(
    // Using dirname(__FILE__) gets around the problem drupal_get_path failing
    // during hook_install() and what_site_requirements().
    dirname(__FILE__) . '/WhatSite',
    'sites/all/libraries/WhatSite',
  );

  foreach ($search_paths as $path) {
    if (is_file($path . '/whatsite.js')) {
      return $path;
    }
  }

  return FALSE;
}
