<?php

/**
 * @file
 * Checkdesk nodejs integration module.
 */

/**
 * Implements hook_preprocess_views_view()
 * Add nodejs channel for my_notifications view
 */
function checkdesk_nodejs_preprocess_views_view(&$vars) {
  $view = $vars['view'];

  switch ($view->name) {
    // Override header for checkdesk nodejs module.
    // we might simply change headers interval to 0 in views but we should remove
    // headers from views completely.
    // @TODO: Review header override of views in favor of module override
    case 'my_notifications':
      global $user;
      $path = drupal_get_path('module', 'checkdesk_notifications') . '/ping.php?user=' . $user->uid;
      $vars['header'] = theme('views_autorefresh', array(
          'interval' => 0, //use nodejs
          'use_base_field' => TRUE,
          'incremental' => FALSE,
          'ping' => array('ping_base_path' => $path),
          'view' => $vars['view'],
      ));

      // Register the view nodejs channel
      nodejs_send_content_channel_token('views_autorefresh_my_notifications');
      break;

    case 'liveblog':
      $vars['header'] = theme('views_autorefresh', array(
          'interval' => 0, //use nodejs
          'ping' => array('ping_base_path' => drupal_get_path('module', 'checkdesk_core') . '/autorefresh/liveblog.php?type=discussion&field=changed'),
          'incremental' => array(
              'view_base_path' => 'liveblog/autorefresh',
              'view_display_id' => 'page_1',
              'view_name' => 'liveblog',
          ),
      ));

      // Register the view nodejs channel
      nodejs_send_content_channel_token('views_autorefresh_liveblog');
      break;

    case 'desk_reports':
      $story = isset($_GET['story']) ? $_GET['story'] : 0;
      $header = theme('views_autorefresh', array(
          'interval' => 0, //use nodejs
          'ping' => array(
              'ping_base_path' => drupal_get_path('module', 'checkdesk_core') . '/autorefresh/liveblog.php?type=media&field=created&story=' . $story
          ),
          'incremental' => array(
              'view_base_path' => 'desk-reports/autorefresh',
              'view_display_id' => 'page_1',
              'view_name' => 'desk_reports',
          ),
      ));
      $header .= '<div class="filters-summary"><p>' . format_plural($view->total_rows, '<span>1</span> result. You can drag and drop it.', '<span>@count</span> results. Drag and drop the best ones.') . '</p></div>';
      $vars['header'] = $header;
      
      // Register the view nodejs channel
      nodejs_send_content_channel_token('views_autorefresh_desk_reports');
      break;
  }
}

/**
 * Implements hook_heartbeat_activity_insert()
 * Refresh notifications when new heartbeat activity inserted
 * @todo filter which heartbeat activity to refresh the view for
 */
function checkdesk_nodejs_heartbeat_activity_insert($heartbeatActivity) {
  views_autorefresh_nodejs_refresh(array('my_notifications'));
  $commands = _checkdesk_nodejs_handle_report_activity($heartbeatActivity->message_id, $heartbeatActivity->nid);
  if (count($commands)) {
     $channels = array();
     // Update report channel
     $channels[] = 'report-activity-'. $heartbeatActivity->nid;
     if ($heartbeatActivity->nid_target) {
         // update story collaboration channel
         $channels[] = 'story-collaborate-'. $heartbeatActivity->nid_target;
     }
     foreach ($channels as $channel) {
         $message = (object) array(
            'channel' => $channel,
            'commands' => $commands,
            'callback' => 'reportReactor',
            );
        // Send the message to the channel we created
        nodejs_send_content_channel_message($message);
     }
  }
}

/**
 * Implements hook_node_view().
 */
function checkdesk_nodejs_node_view($node, $view_mode, $langcode) {
  global $user;
  if ($user->uid && $node->type == 'discussion' && $view_mode == 'checkdesk_collaborate') {
    drupal_add_js(drupal_get_path('module', 'checkdesk_nodejs') . '/js/checkdesk_nodejs.js');
    // Register nodejs channel
    $nodejs_channel = 'story-collaborate-'. $node->nid;
    nodejs_send_content_channel_token($nodejs_channel);
  }
  elseif ($node->type == 'media' && $view_mode == 'full') {
      drupal_add_js(drupal_get_path('module', 'checkdesk_nodejs') . '/js/checkdesk_nodejs.js');
      // Register nodejs channel
      $nodejs_channel = 'report-activity-'. $node->nid;
      nodejs_send_content_channel_token($nodejs_channel);
  }
}

/**
 * Implements hook_node_insert();
 */
function checkdesk_nodejs_node_insert($node) {
  _checkdesk_nodejs_handle_node($node);
}

/**
 * Implements hook_node_update();
 */
function checkdesk_nodejs_node_update($node) {
   _checkdesk_nodejs_handle_node($node);
}

/**
 * Implements hook_node_delete();
 */
function checkdesk_nodejs_node_delete($node) {
  _checkdesk_nodejs_handle_node($node);
}

/**
 * Handle all node operations
 */
function _checkdesk_nodejs_handle_node($node) {
  $views_to_update = array();
  switch ($node->type) {
    case 'media':
      $views_to_update[] = 'liveblog';
      $views_to_update[] = 'desk_reports';
      break;

    case 'discussion':
      $views_to_update[] = 'liveblog';
      break;

    case 'post':
      $views_to_update[] = 'liveblog';
      break;
  }

  views_autorefresh_nodejs_refresh($views_to_update);
}


function _checkdesk_nodejs_handle_report_activity($activity, $nid) {
    $commands = array();
    switch ($activity) {
        case 'status_report':
            $node = node_load($nid);
            $report_status = _checkdesk_report_status($node);
            $commands[] = ajax_command_insert('.media-status-report-' . $node->nid, $report_status['status'], 'replaceWith');
            break;
        case 'checkdesk_fact_checking_on':
        case 'checkdesk_fact_checking_set':
            $node = node_load($nid);
            $node_view = node_view($node);
            $node_view['comments'] = comment_node_page_additions($node);
            // update activity stream
            $report_activity = theme(
                'checkdesk_core_report_activity', array('node' => $node, 'content' => $node_view)
            );
            $commands[] = ajax_command_insert('.report-activity-node-' . $node->nid, $report_activity, 'replaceWith');
            break;
    }
    return $commands;
}