<?php

/**
 * Implements hook_library().
 */
function meedan_iframes_library() {
  $libraries = array();
  $path = drupal_get_path('module', 'meedan_iframes');
  $libraries['meedan_iframes.parent'] = array(
    'title' => 'Meedan IFRAME parent',
    'description' => 'This script to be placed in the parent page immediately following an IFRAME.',
    'version' => VERSION,
    'js' => array(
      $path . '/js/meedan_iframes.parent.min.js' => array(),
    ),
  );
  $libraries['meedan_iframes.child'] = array(
    'title' => 'Meedan IFRAME child',
    'description' => 'This script to be placed inside the IFRAME content.',
    'version' => VERSION,
    'js' => array(
      $path . '/js/meedan_iframes.child.js' => array(),
    ),
  );
  return $libraries;
}


/**
 * Implements hook_theme().
 */
function meedan_iframes_theme($existing, $type, $theme, $path) {
  return array(
    'meedan_iframe' => array(
      'variables' => array('src' => NULL, 'attributes' => NULL),
    ),
  );
}

/**
 * Default theme implementation for 'meedan_iframe'.
 */
function theme_meedan_iframe($vars) {
  $defaults = array(
    'frameborder' => "0",
    'scrolling'   => "no",
    'seamless'    => NULL,
    'id'          => 'meedan-iframe-' . substr(md5($vars['src']), 0, 6),
  );
  $attrs = array_merge($defaults, (array) $vars['attributes']);

  $parent = drupal_get_library('meedan_iframes', 'meedan_iframes.parent');

  // It is critical that these URLs are:
  // 1. Absolute, to ensure embedded IFRAMEs work on remote sites
  // 2. HTTPS, to ensure embedded IFRAMEs work and do not throw security errors
  //    on remote sites. Note, this will only work correctly when $conf['https'] = TRUE;
  // 3. Have no language set, for correct paths in all languages
  $script_src = url(key($parent['js']), array('absolute' => TRUE, 'https' => TRUE, 'language' => (object) array('language' => FALSE)));

  // The IFRAME comes first and the parent script MUST come second. The parent
  // script relies on this fact for DOM calculations.
  $output  = '<iframe src="' . $vars['src'] .'" ' . drupal_attributes($attrs) . '></iframe>';
  $output .= '<script src="' . $script_src . '"></script>';

  return $output;
}
