<?php

/**
 * Implementation of hook_menu()
 */
function meedan_reports_menu() {
  $items = array();
  $items['admin/meedan/reports'] = array(
    'title' => t('Meedan Reports'),
    'description' => t('Meedan reports for reviewing how the site is performing'),
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'position' => 'left',
    'weight' => 6,
    'file' => 'system.admin.inc', 
    'file path' => drupal_get_path('module', 'system'),
  );
  $reports = array (
    'user_registered' => t('Registered users reports'),
    //'translation_count' => t('Translated reports words'),
    //'translation_reports' => t('Translated reports'),
    'reports_count' => t('Citizen reports'),
    'different_sources' => t('Different sources reports'),
    'most_active_users' => t('Most active users reports'),
    //'detailed_citizen_reports' => t('Detailed citizen reports'),
    'active_users' => t('Active Users'),
  );
  foreach ($reports as $path => $title) {
    $items['admin/meedan/reports/'.$path] = array(
      'page callback' => 'drupal_get_form',
      'page arguments' => array('statistics_filter_form', 3),
      'title' => $title,
      'access arguments' => array('administer site configuration'),
    );
  }
  return $items;
}

/**
 * Build statistics filter form.
 */
function statistics_filter_form($form, &$form_state, $type) {
  $query = db_select('node', 'n');
  $query->addExpression('FROM_UNIXTIME(created, \'%Y\')', 'year');
  $query->distinct();
  $result = $query->execute();
  $years = array('' => t('All'));
  while ($year = $result->fetchfield()) {
    $years[$year] = $year;
  }
  $year_val = '';
  if (isset($_SESSION['report_year'])) {
    $year_val = $_SESSION['report_year'];
    $form['year_val'] = array(
      '#type' => 'hidden',
      '#value' => $year_val,
    );
    unset($_SESSION['report_year']);
  }

  $form['year'] = array(
    '#title' => t('Select year'),
    '#type' => 'select',
    '#options' => $years,
    '#weight' => -100,
    '#default_value' => $year_val,
  );
  $form['submit'] = array(
    '#value' => t('Search'),
    '#type' => 'submit',
    '#weight' => -90,
    '#submit' => array('statistics_filter_form_submit'),
  );
  $form['export']  = array(
    '#value' => t('Export CSV'),
    '#type' => 'submit',
    '#submit' => array('export_to_csv'),
  );
  $form['#stat_type'] = $type;
  return $form;
}

/**
 * Implementation of hook_theme
 */
function meedan_reports_theme() {
  return array(
    'statistics_filter_form' => array(
      'render element' => 'form',
    ),
  );
}

function statistics_filter_form_submit($form, $form_state) {
  $_SESSION['report_year'] = $form_state['values']['year'];
}

/**
 * Statistics theme form.
 */
function theme_statistics_filter_form($form) {
  require_once(drupal_get_path('module', 'meedan_reports') . '/meedan_reports_sql.inc');
  drupal_add_js(libraries_get_path('amstockchart') . '/amcharts/amstock.js');
  drupal_add_js(drupal_get_path('module', 'meedan_reports') . '/js/meedan_reports.js');
  drupal_add_js(drupal_get_path('module', 'meedan_reports') . '/js/jquery.ui.tabs.js');
  drupal_add_css(drupal_get_path('module', 'meedan_reports') .'/css/jquery-ui-1.7.3.custom.css');
  $year_val = isset($form['form']['year_val']['#value']) ? $form['form']['year_val']['#value'] : '';
  $render_report = render_report_sql($form['form']['#stat_type'], $year_val);
  $output = '';
  $output .= drupal_render_children($form['form']); 
  drupal_set_title($render_report['title']);
  $header = array('Date', 'Count');
  $row = array();
  $row_json = array();
  $results = $render_report['results'];
  $total = 0;
  foreach ($results as $result) {
    if ($form['form']['#stat_type'] == "most_active_users" || $form['form']['#stat_type'] == 'different_sources') {
      $row[] = array(str_replace("\n","<br>", $result->info), $result ->count);
    }
    else {
      $row[] = array($result->date, $result->count);
    }
    $info = isset($result->info) ? $result->info.'<br>#'.$result->count : $result->count;
    $row_json[] = array('Date' => $result->date, 'Count' => (int) $result->count, 'Info' => $info);
    $total += $result->count;
  }
  $row[] = array('' , t('Total')." $total");
  $output .= '<div id="tabs">';
  $output .= '
    <ul class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
      <li><a href="#chartView">Chart View</a></li>
      <li><a href="#tableView">Table View</a></li>
      </ul>';
  $output .= '<div id="chartView"><div id="chartContainer" style="width: 740px; height: 390px;"></div></div>';
  $output .= '<div id="tableView">'. theme('table', array('header' => $header, 'rows' => $row)) .'</div>';
  $json_obj = drupal_json_encode($row_json);
  drupal_add_js('
    jQuery(function() {
      add_chart_view('.$json_obj.', "'. $render_report['title'] .'");
    })', 'inline');

  $output .= '</div>';
  return $output;
}

/**
 * Submit handler for export CSV.
 */
function export_to_csv($form, $form_state) { 
  require_once(drupal_get_path('module', 'meedan_reports') . '/meedan_reports_sql.inc');
  $render_report = render_report_sql($form['#stat_type'], $form_state['values']['year']);
  $filename = str_replace(' ', '_', strtolower($render_report['title'])) .'.csv';
  drupal_add_http_header('Content-Type', 'text/csv');
  drupal_add_http_header('Content-Disposition', 'attachment; filename=' . $filename);
  $results = $render_report['results'];
  print  "Date,Count\r\n";
  foreach ($results as $row) {
    if ($form['#stat_type'] == "most_active_users" || $form['#stat_type'] == 'different_sources') {
      $values[0] = '"' . str_replace('"', '""', decode_entities(strip_tags($row->info))) . '"'; 
    }
    else {
      $values[0] = '"' . str_replace('"', '""', decode_entities(strip_tags($row->date))) . '"'; 
    }
    $values[1] = '"' . str_replace('"', '""', decode_entities(strip_tags($row->count))) . '"'; 

    print implode(',', $values) ."\r\n";
    unset($values);
  }
  exit();
}


