<?php

/**
* Loads the geoPHP library.
*
* @return
*   Returns the filename of the included geoPHP library when successful, FALSE
*   otherwise.
*/
function geophp_load() {
  static $static_cache = FALSE;
  
  if (!$static_cache) {
    $path = drupal_get_path('module', 'geophp');
    $file = $path.'/geoPHP/geoPHP.inc';
    if (file_exists($file)) {
      if (include_once($file)) {
        $static_cache = $file;
      }
    }
  }
  
  return $static_cache;
}

/**
* Implementation of hook_requirements().
*/
function geophp_requirements($phase) {
  $requirements = array();
  
  $geophp = geofield_load_geophp();
  
  if (geoPHP::geosInstalled()) {
    $requirements['geophp'] = array(
      'title' => t('GeoPHP and GEOS'),
      'severity' => REQUIREMENT_OK,
      'value' => t('GEOS PHP extension Installed'),
    );
  }
  else {
    $requirements['geophp'] = array(
      'title' => t('GeoPHP and GEOS'),
      'severity' => REQUIREMENT_INFO,
	    'value' => t('GeoPHP library installed and OK. However, GEOS is was not found. While not required, you will see performance improvements if you install the GEOS PHP extension. More information can be found here: %link',array('%link' => 'https://github.com/phayes/geoPHP/wiki/GEOS')),
    );
  }
  
  return $requirements;
}
