<?php

/**
 * Implements hook_menu().
 */
function checkdesk_reports_duplicates_menu() {
  $items = array();
  $items['checkdesk/duplicate-report-story'] = array(
    'page callback' => '_checkdesk_duplicate_report_story',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'checkdesk.report_duplicate.inc',
    'file path' => drupal_get_path('module', 'checkdesk_reports_duplicates') . '/includes',
  );
  $items['checkdesk/duplicate-report'] = array(
    'page callback' => '_checkdesk_detect_report_duplicate_callback',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'checkdesk.report_duplicate.inc',
    'file path' => drupal_get_path('module', 'checkdesk_reports_duplicates') . '/includes',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function checkdesk_reports_duplicates_theme() {
  $themes = array();
  $base = array(
    'file' => 'theme.inc',
    'path' => drupal_get_path('module', 'checkdesk_reports_duplicates') . '/theme',
  );
  $themes['checkdesk_reports_duplicates'] = array(
      'template' => 'duplicates_reports',
      'variables' => array(
        'reports' => NULL,
        'duplicate_report_nid' => NULL,
      ),
    ) + $base;
  return $themes;
}

/**
 * Implements hook_node_presave()
 */
function checkdesk_reports_duplicates_node_presave($node) {
  // Normalize URL before save media node
  if ($node->type == 'media') {
    $node->field_link[LANGUAGE_NONE][0]['url'] = _checkdesk_normalize_url($node->field_link[LANGUAGE_NONE][0]['url']);
  }
}

/**
 *
 * Implements hook_form_ID_alter().
 */
function checkdesk_reports_duplicates_form_media_node_form_alter(&$form, &$form_state) {
  $form['report_duplicate'] = array(
    '#markup' => '<div id="checkdesk_report_duplicate" style="display: none;"></div>',
    '#weight' => -1                                                                                                                                                                                               ,
  );
  $form['field_stories']['#prefix'] = '<div id="checkdesk_report_story_duplicate" style="display: none;"></div>';
  $setting = array('checkdesk_reports_duplicates' => array('report_nid' => empty($form['nid']['#value']) ? 0 : $form['nid']['#value']));
  drupal_add_js($setting, 'setting');
  // Validate duplicate report
  $form['#validate'][] = '_checkdesk_reports_duplicates_form_validate';
  $form['#attached']['js'][] = drupal_get_path('module', 'checkdesk_reports_duplicates') . '/js/checkdesk_reports_duplicates_form.js';
}

/**
 * Validate report against selected story
 */
function _checkdesk_reports_duplicates_form_validate($form, &$form_state) {
  $story_id = isset($form_state['values']['field_stories'][LANGUAGE_NONE][0]['target_id']) ?
    $form_state['values']['field_stories'][LANGUAGE_NONE][0]['target_id'] : 0;
  $report_id = isset($form_state['values']['nid']) ? $form_state['values']['nid'] : 0;
  $duplicate = _checkdesk_duplicate_report_story_exists($form_state['values']['field_link'][LANGUAGE_NONE][0]['url'], $report_id, $story_id);
  if ($duplicate['duplicate']) {
    form_set_error('field_link', $duplicate['msg']);
  }
}

function _checkdesk_duplicate_report_story_exists($url, $report_id, $story_id) {
  $output['duplicate'] = FALSE;
  $n_url = _checkdesk_normalize_url($url);
  $query = db_select('field_data_field_link', 'fl');
  $query->addField('fl', 'entity_id');
  $query->leftJoin('field_data_field_stories', 'fs', ' fl.entity_id = fs.entity_id');
  $query->condition('fl.field_link_url', $n_url)
    ->condition('fl.entity_id', $report_id, '<>');
  if ($story_id) {
    $query->condition('fs.field_stories_target_id', $story_id);
  }
  else {
    $query->isNull('fs.field_stories_target_id');
  }
  $query->addTag('checkdesk_duplicate');
  $result = $query->execute()->fetchField();
  if ($result) {
    $output['duplicate'] = TRUE;
    $output['msg'] = t('Report already exists !report', array(
        '!report' => l(t('View the link'), 'node/'. $result, array('attributes' => array('target'=>'_blank'))))
    );
  }
  return $output;
}

/**
 * Helper function to get duplicate reports.
 * @param string $url
 *  report url
 * @return array|bool
 * FALSE if no duplicate or
 * Associative array with report_nid => story_nid
 */
function _checkdesk_duplicate_reports($url) {
  $n_url = _checkdesk_normalize_url($url);
  $query = db_select('field_data_field_link', 'fl');
  $query->addField('fl', 'entity_id');
  $query->addField('fs', 'field_stories_target_id');
  $query->leftJoin('field_data_field_stories', 'fs', 'fl.entity_id = fs.entity_id');
  $query->condition('fl.field_link_url', $n_url);
  $query->addTag('checkdesk_duplicate');
  $result = $query->execute()->fetchAllKeyed(0);
  if (count($result)) {
    return $result;
  }
  return array();
}


/**
 * @param $report
 * @param $story_id
 * @return mixed
 */
function _checkdesk_duplicate_share_report($report, $story_id) {
  global $user;
  $new_report = clone $report;
  unset($new_report->nid, $new_report->vid, $new_report->created, $new_report->changed);
  $new_report->uid = $user->uid;
  $new_report->field_stories[LANGUAGE_NONE][]['target_id'] = $story_id;
  node_save($new_report);
  return $new_report;
}
