<?php
/**
 * @file
 * meedan_devel.strongarm.inc
 */

/**
 * Implements hook_strongarm().
 */
function meedan_devel_strongarm() {
  $export = array();

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'maillog_devel';
  $strongarm->value = 0;
  $export['maillog_devel'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'maillog_log';
  $strongarm->value = 1;
  $export['maillog_log'] = $strongarm;

  $strongarm = new stdClass();
  $strongarm->disabled = FALSE; /* Edit this to true to make a default strongarm disabled initially */
  $strongarm->api_version = 1;
  $strongarm->name = 'maillog_send';
  $strongarm->value = 0;
  $export['maillog_send'] = $strongarm;

  return $export;
}
